pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }
rootProject.name = 'SolarFormMaker'
include ':app'

gradle.beforeProject { p ->
    if (p.path == ':app') {
        p.pluginManager.withPlugin('com.android.application') {
            p.extensions.getByName('android').sourceSets.main.java.exclude '**/OfferStudioV*.java'
        }
    }
}
