package com.infinitygreenpower.solarform;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class OfferStudioActivity extends Activity {
    private final int INK=Color.rgb(18,32,45), NAVY=Color.rgb(18,50,79), EMERALD=Color.rgb(20,153,112), BG=Color.rgb(246,248,251), LINE=Color.rgb(225,231,237), MUTED=Color.rgb(104,119,132), WHITE=Color.WHITE, SOFT=Color.rgb(239,247,244), AMBER=Color.rgb(235,153,43);
    private final int PICK_IMAGES=4401;
    private LinearLayout shell, content, bottomNav;
    private final ArrayList<Product> catalog=new ArrayList<>();
    private Draft draft=new Draft();
    private int wizardStep=0;

    static class Product {
        String category,name,spec;
        Product(String c,String n,String s){category=c;name=n;spec=s;}
        String display(){return name+(spec.isEmpty()?"":" · "+spec);}
        String searchable(){return (category+" "+name+" "+spec).toLowerCase(Locale.ROOT);}
    }
    static class LineItem {
        String category,name,spec,qty,price;
        LineItem(String a,String b,String c,String d,String e){category=a;name=b;spec=c;qty=d;price=e;}
        JSONObject json(){JSONObject o=new JSONObject();try{o.put("category",category);o.put("name",name);o.put("spec",spec);o.put("qty",qty);o.put("price",price);}catch(Exception ignored){}return o;}
        static LineItem from(JSONObject o){return new LineItem(o.optString("category"),o.optString("name"),o.optString("spec"),o.optString("qty","1"),o.optString("price"));}
    }
    static class Draft {
        String id="", client="", phone="", location="", date="", system="Hybrid", capacity="", phase="Single phase", organizer="", notes="";
        boolean installation=true, transport=false;
        ArrayList<LineItem> items=new ArrayList<>();
        ArrayList<String> photos=new ArrayList<>();
        JSONObject json(){JSONObject o=new JSONObject();try{
            o.put("id",id);o.put("client",client);o.put("phone",phone);o.put("location",location);o.put("date",date);o.put("system",system);o.put("capacity",capacity);o.put("phase",phase);o.put("organizer",organizer);o.put("notes",notes);o.put("installation",installation);o.put("transport",transport);
            JSONArray a=new JSONArray();for(LineItem x:items)a.put(x.json());o.put("items",a);JSONArray p=new JSONArray();for(String x:photos)p.put(x);o.put("photos",p);
        }catch(Exception ignored){}return o;}
        static Draft from(JSONObject o){Draft d=new Draft();d.id=o.optString("id");d.client=o.optString("client");d.phone=o.optString("phone");d.location=o.optString("location");d.date=o.optString("date");d.system=o.optString("system","Hybrid");d.capacity=o.optString("capacity");d.phase=o.optString("phase","Single phase");d.organizer=o.optString("organizer");d.notes=o.optString("notes");d.installation=o.optBoolean("installation",true);d.transport=o.optBoolean("transport",false);JSONArray a=o.optJSONArray("items");if(a!=null)for(int i=0;i<a.length();i++)d.items.add(LineItem.from(a.optJSONObject(i)));JSONArray p=o.optJSONArray("photos");if(p!=null)for(int i=0;i<p.length();i++)d.photos.add(p.optString(i));return d;}
    }

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(WHITE);seedCatalog();buildShell();showHome();}

    private void seedCatalog(){
        catalog.clear();
        catalog.add(new Product("Solar Panels","Huasun HJT","610 W"));catalog.add(new Product("Solar Panels","Huasun HJT","615 W"));catalog.add(new Product("Solar Panels","Huasun HJT","620 W"));
        catalog.add(new Product("Inverters","Roypow RS6500 Hybrid","6.5 kW"));catalog.add(new Product("Inverters","Deye Hybrid Single Phase","6 kW"));catalog.add(new Product("Inverters","Deye Hybrid Single Phase","8 kW"));catalog.add(new Product("Inverters","Deye Hybrid Single Phase","12 kW"));catalog.add(new Product("Inverters","Deye Hybrid Single Phase","16 kW"));catalog.add(new Product("Inverters","Deye Hybrid Three Phase","12 kW"));catalog.add(new Product("Inverters","Deye Hybrid Three Phase","16 kW"));catalog.add(new Product("Inverters","Deye On-Grid Inverter","Custom size"));
        catalog.add(new Product("Batteries","Roypow LiFePO4","16 kWh"));catalog.add(new Product("Batteries","Deye High Voltage Battery Rack","HV"));catalog.add(new Product("BMS","Deye High Voltage BMS","HV"));
        catalog.add(new Product("Structure","Solar mounting structure","Site based"));catalog.add(new Product("Cables","Solar DC Cable","6 mm²"));catalog.add(new Product("Cables","AC Cable","Custom size"));catalog.add(new Product("Cables","Battery Cable","Custom size"));
        catalog.add(new Product("Protection","Protection / Combiner Box",""));catalog.add(new Product("Protection","DC Breaker",""));catalog.add(new Product("Protection","AC Breaker",""));catalog.add(new Product("Protection","DC SPD",""));catalog.add(new Product("Protection","AC SPD",""));catalog.add(new Product("Accessories","MC4 Connectors",""));catalog.add(new Product("Accessories","Distribution Board",""));catalog.add(new Product("Accessories","Earthing System",""));catalog.add(new Product("Accessories","Earth Rod",""));catalog.add(new Product("Accessories","Cable Tray / PVC",""));catalog.add(new Product("Service","Installation Labor",""));
    }

    private void buildShell(){
        shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(BG);
        content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setLayoutParams(new LinearLayout.LayoutParams(-1,0,1));shell.addView(content);
        bottomNav=new LinearLayout(this);bottomNav.setOrientation(LinearLayout.HORIZONTAL);bottomNav.setGravity(Gravity.CENTER);bottomNav.setBackgroundColor(WHITE);bottomNav.setPadding(dp(8),dp(7),dp(8),dp(7));bottomNav.setElevation(dp(8));shell.addView(bottomNav,new LinearLayout.LayoutParams(-1,dp(72)));
        setContentView(shell);buildBottomNav("home");
    }

    private void buildBottomNav(String active){
        bottomNav.removeAllViews();
        bottomNav.addView(navButton("⌂","Home",active.equals("home"),v->showHome()));
        bottomNav.addView(navButton("＋","New Offer",active.equals("new"),v->startNewOffer()));
        bottomNav.addView(navButton("▤","Saved",active.equals("saved"),v->showSaved()));
        bottomNav.addView(navButton("⌕","Catalog",active.equals("catalog"),v->showCatalogScreen()));
    }
    private View navButton(String icon,String label,boolean active,View.OnClickListener l){
        LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setGravity(Gravity.CENTER);b.setOnClickListener(l);b.setBackground(active?round(Color.rgb(236,247,243),18,0,0):null);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);lp.leftMargin=dp(3);lp.rightMargin=dp(3);b.setLayoutParams(lp);
        TextView i=text(icon,22,true,active?EMERALD:MUTED);i.setGravity(Gravity.CENTER);TextView t=text(label,11,active,active?EMERALD:MUTED);t.setGravity(Gravity.CENTER);b.addView(i);b.addView(t);return b;
    }

    private void clearContent(){content.removeAllViews();hideKeyboard();}

    private void showHome(){
        clearContent();buildBottomNav("home");
        ScrollView s=new ScrollView(this);LinearLayout root=vertical(dp(18));s.addView(root);content.addView(s,new LinearLayout.LayoutParams(-1,-1));
        root.addView(hero());
        TextView h=text("Quick actions",18,true,INK);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,-2);hp.topMargin=dp(22);hp.bottomMargin=dp(10);h.setLayoutParams(hp);root.addView(h);
        LinearLayout r1=row();r1.addView(actionTile("＋","Create offer","Start a new quotation",EMERALD,v->startNewOffer()));r1.addView(actionTile("▤","Saved offers",savedOffers().length()+" saved",NAVY,v->showSaved()));root.addView(r1);
        LinearLayout r2=row();r2.addView(actionTile("⌕","Product catalog",catalog.size()+" items",Color.rgb(78,99,120),v->showCatalogScreen()));r2.addView(actionTile("▧","Quick preview","Preview current draft",AMBER,v->{if(draft.items.isEmpty()&&draft.client.isEmpty())Toast.makeText(this,"Start an offer first",Toast.LENGTH_SHORT).show();else showPreview();}));root.addView(r2);
        LinearLayout tip=card();tip.setPadding(dp(16),dp(14),dp(16),dp(14));LinearLayout.LayoutParams tlp=(LinearLayout.LayoutParams)tip.getLayoutParams();tlp.topMargin=dp(18);tip.setLayoutParams(tlp);tip.addView(text("Workflow",13,true,EMERALD));tip.addView(text("Client → System → Items → Details → Preview → PDF",14,true,INK));tip.addView(text("The new app uses a guided workflow instead of one long form.",12,false,MUTED));root.addView(tip);
    }

    private View hero(){
        LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(20),dp(22),dp(20),dp(22));GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{NAVY,Color.rgb(13,111,94)});g.setCornerRadius(dp(28));h.setBackground(g);h.setElevation(dp(3));
        TextView brand=text("INFINITY GREEN POWER",13,true,Color.rgb(191,245,222));h.addView(brand);TextView title=text("Offer Studio",32,true,WHITE);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,-2);tp.topMargin=dp(5);title.setLayoutParams(tp);h.addView(title);TextView sub=text("Build polished solar offers in a guided, mobile-first workflow.",14,false,Color.rgb(229,241,238));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.topMargin=dp(5);sub.setLayoutParams(sp);h.addView(sub);
        Button b=button("Create new offer",WHITE,NAVY);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(50));bp.topMargin=dp(18);b.setLayoutParams(bp);b.setOnClickListener(v->startNewOffer());h.addView(b);return h;
    }

    private View actionTile(String icon,String title,String sub,int accent,View.OnClickListener l){
        LinearLayout c=card();c.setPadding(dp(15),dp(15),dp(15),dp(15));c.setOnClickListener(l);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(142),1);lp.leftMargin=dp(5);lp.rightMargin=dp(5);lp.bottomMargin=dp(10);c.setLayoutParams(lp);
        TextView i=text(icon,24,true,accent);i.setBackground(round(withAlpha(accent,25),16,0,0));i.setGravity(Gravity.CENTER);c.addView(i,new LinearLayout.LayoutParams(dp(46),dp(46)));TextView t=text(title,15,true,INK);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,-2);tp.topMargin=dp(10);t.setLayoutParams(tp);c.addView(t);c.addView(text(sub,12,false,MUTED));return c;
    }

    private void startNewOffer(){draft=new Draft();draft.date=new SimpleDateFormat("yyyy/MM/dd",Locale.US).format(new Date());wizardStep=0;showWizard();}
    private void showWizard(){clearContent();buildBottomNav("new");LinearLayout page=vertical(0);content.addView(page,new LinearLayout.LayoutParams(-1,-1));page.addView(topBar("New Offer","Step "+(wizardStep+1)+" of 4",v->{if(wizardStep==0)showHome();else{wizardStep--;showWizard();}}));page.addView(progress());ScrollView sc=new ScrollView(this);LinearLayout body=vertical(dp(18));sc.addView(body);page.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(wizardStep==0)clientStep(body);else if(wizardStep==1)systemStep(body);else if(wizardStep==2)itemsStep(body);else detailsStep(body);page.addView(wizardActions());}

    private View progress(){
        LinearLayout bar=row();bar.setPadding(dp(18),dp(10),dp(18),dp(8));String[] names={"Client","System","Items","Finish"};for(int i=0;i<4;i++){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);TextView dot=text(String.valueOf(i+1),12,true,i<=wizardStep?WHITE:MUTED);dot.setGravity(Gravity.CENTER);dot.setBackground(round(i<=wizardStep?EMERALD:Color.rgb(232,236,240),18,0,0));x.addView(dot,new LinearLayout.LayoutParams(dp(32),dp(32)));TextView lab=text(names[i],10,i==wizardStep,i<=wizardStep?EMERALD:MUTED);lab.setGravity(Gravity.CENTER);x.addView(lab);bar.addView(x,new LinearLayout.LayoutParams(0,-2,1));}return bar;
    }
    private void clientStep(LinearLayout body){body.addView(stepHeader("Client details","Who is this offer for?"));EditText a=field(body,"Client name","e.g. Ahmed Karim",draft.client);EditText b=field(body,"Phone","07xx xxx xxxx",draft.phone);EditText c=field(body,"Location","City / district / project location",draft.location);EditText d=field(body,"Date","YYYY/MM/DD",draft.date);tag(a,"client");tag(b,"phone");tag(c,"location");tag(d,"date");}
    private void systemStep(LinearLayout body){body.addView(stepHeader("System setup","Define the solar system configuration."));body.addView(label("System type"));body.addView(choiceRow(new String[]{"Hybrid","On-Grid","Off-Grid"},draft.system,"system"));EditText cap=field(body,"Required capacity","e.g. 8 kW",draft.capacity);tag(cap,"capacity");body.addView(label("Phase"));body.addView(choiceRow(new String[]{"Single phase","Three phase"},draft.phase,"phase"));LinearLayout note=infoBox("Tip","Use the required capacity as the customer target. Individual inverter/panel sizes are selected in the next step.");body.addView(note);}
    private void itemsStep(LinearLayout body){body.addView(stepHeader("Offer items","Add products from the catalog or create custom rows."));LinearLayout actions=row();Button cat=button("Browse catalog",NAVY,WHITE);Button custom=button("Custom item",WHITE,NAVY);custom.setBackground(round(WHITE,16,LINE,1));actions.addView(cat,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(48),1);cp.leftMargin=dp(8);custom.setLayoutParams(cp);actions.addView(custom);body.addView(actions);cat.setOnClickListener(v->showPickerDialog());custom.setOnClickListener(v->showItemEditor(null,-1));LinearLayout list=vertical(0);LinearLayout.LayoutParams llp=new LinearLayout.LayoutParams(-1,-2);llp.topMargin=dp(14);list.setLayoutParams(llp);if(draft.items.isEmpty())list.addView(empty("No items yet","Add an inverter, panels, battery, cables or any custom item."));else for(int i=0;i<draft.items.size();i++)list.addView(itemCard(i,draft.items.get(i)));body.addView(list);}
    private void detailsStep(LinearLayout body){body.addView(stepHeader("Final details","Add services, notes and site photos."));body.addView(label("Included services"));body.addView(toggleRow());EditText o=field(body,"Inspection organizer","Name of the organizer",draft.organizer);tag(o,"organizer");EditText n=fieldMulti(body,"Notes","Installation conditions, cable route, roof notes…",draft.notes);tag(n,"notes");TextView photosTitle=label("Site photos");LinearLayout.LayoutParams pt=new LinearLayout.LayoutParams(-1,-2);pt.topMargin=dp(8);photosTitle.setLayoutParams(pt);body.addView(photosTitle);Button add=button("＋ Add photos",Color.rgb(237,244,250),NAVY);add.setBackground(round(Color.rgb(237,244,250),16,0,0));body.addView(add,new LinearLayout.LayoutParams(-1,dp(48)));add.setOnClickListener(v->pickImages());LinearLayout photoList=vertical(0);LinearLayout.LayoutParams pl=new LinearLayout.LayoutParams(-1,-2);pl.topMargin=dp(10);photoList.setLayoutParams(pl);if(draft.photos.isEmpty())photoList.addView(empty("No photos attached","Attach roof, inverter area, distribution board or existing system photos."));else for(int i=0;i<draft.photos.size();i++)photoList.addView(photoRow(i,draft.photos.get(i)));body.addView(photoList);}

    private View wizardActions(){LinearLayout bar=row();bar.setPadding(dp(18),dp(10),dp(18),dp(14));bar.setBackgroundColor(WHITE);Button back=button(wizardStep==0?"Cancel":"Back",Color.rgb(241,244,247),INK);back.setBackground(round(Color.rgb(241,244,247),16,0,0));Button next=button(wizardStep==3?"Preview offer":"Continue",EMERALD,WHITE);LinearLayout.LayoutParams a=new LinearLayout.LayoutParams(0,dp(52),1);a.rightMargin=dp(8);bar.addView(back,a);bar.addView(next,new LinearLayout.LayoutParams(0,dp(52),1));back.setOnClickListener(v->{captureVisibleFields();if(wizardStep==0)showHome();else{wizardStep--;showWizard();}});next.setOnClickListener(v->{captureVisibleFields();if(wizardStep<3){wizardStep++;showWizard();}else showPreview();});return bar;}

    private void captureVisibleFields(){findAndSave(content);}
    private void findAndSave(View v){if(v instanceof EditText){EditText e=(EditText)v;Object tag=e.getTag();if(tag!=null){String k=String.valueOf(tag),x=e.getText().toString().trim();if(k.equals("client"))draft.client=x;else if(k.equals("phone"))draft.phone=x;else if(k.equals("location"))draft.location=x;else if(k.equals("date"))draft.date=x;else if(k.equals("capacity"))draft.capacity=x;else if(k.equals("organizer"))draft.organizer=x;else if(k.equals("notes"))draft.notes=x;}}if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)findAndSave(g.getChildAt(i));}}

    private View choiceRow(String[] opts,String selected,String key){LinearLayout r=row();for(String x:opts){TextView c=text(x,13,true,x.equals(selected)?EMERALD:INK);c.setGravity(Gravity.CENTER);c.setBackground(round(x.equals(selected)?SOFT:Color.rgb(247,249,251),16,x.equals(selected)?EMERALD:LINE,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(46),1);lp.leftMargin=dp(4);lp.rightMargin=dp(4);c.setLayoutParams(lp);c.setOnClickListener(v->{if(key.equals("system"))draft.system=x;else draft.phase=x;showWizard();});r.addView(c);}return r;}
    private View toggleRow(){LinearLayout r=row();r.addView(toggleCard("Installation",draft.installation,v->{draft.installation=!draft.installation;showWizard();}));r.addView(toggleCard("Transport",draft.transport,v->{draft.transport=!draft.transport;showWizard();}));return r;}
    private View toggleCard(String title,boolean on,View.OnClickListener l){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(14),dp(8),dp(14),dp(8));c.setBackground(round(on?SOFT:Color.rgb(248,249,251),16,on?EMERALD:LINE,1));c.setOnClickListener(l);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(54),1);lp.leftMargin=dp(4);lp.rightMargin=dp(4);c.setLayoutParams(lp);TextView t=text(title,13,true,on?EMERALD:INK);t.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));TextView s=text(on?"ON":"OFF",11,true,on?WHITE:MUTED);s.setGravity(Gravity.CENTER);s.setBackground(round(on?EMERALD:Color.rgb(230,234,238),12,0,0));c.addView(t);c.addView(s,new LinearLayout.LayoutParams(dp(42),dp(28)));return c;}

    private void showPickerDialog(){
        Dialog d=new Dialog(this);LinearLayout box=vertical(dp(14));EditText search=new EditText(this);search.setHint("Search panels, Deye, Roypow, cables…");search.setSingleLine(true);search.setBackground(round(Color.rgb(247,249,251),16,LINE,1));search.setPadding(dp(14),0,dp(14),0);box.addView(search,new LinearLayout.LayoutParams(-1,dp(50)));ListView list=new ListView(this);ArrayList<Product> filtered=new ArrayList<>(catalog);ArrayList<String> labels=new ArrayList<>();for(Product p:filtered)labels.add(p.category+"  •  "+p.display());ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,labels);list.setAdapter(a);LinearLayout.LayoutParams llp=new LinearLayout.LayoutParams(-1,dp(480));llp.topMargin=dp(8);box.addView(list,llp);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int af){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int st,int b,int c){String q=s.toString().toLowerCase(Locale.ROOT);filtered.clear();labels.clear();for(Product p:catalog)if(q.isEmpty()||p.searchable().contains(q)){filtered.add(p);labels.add(p.category+"  •  "+p.display());}a.notifyDataSetChanged();}});list.setOnItemClickListener((p,v,pos,id)->{Product x=filtered.get(pos);d.dismiss();showItemEditor(new LineItem(x.category,x.name,x.spec,"1",""),-1);});d.setTitle("Product catalog");d.setContentView(box);d.show();Window w=d.getWindow();if(w!=null)w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.94),WindowManager.LayoutParams.WRAP_CONTENT);
    }
    private void showItemEditor(LineItem item,int editIndex){LineItem src=item==null?new LineItem("Custom","","","1",""):item;LinearLayout box=vertical(dp(14));EditText cat=miniField("Category",src.category);EditText name=miniField("Item / model",src.name);EditText spec=miniField("Capacity / specification",src.spec);EditText qty=miniField("Quantity",src.qty);EditText price=miniField("Price (optional)",src.price);box.addView(cat);box.addView(name);box.addView(spec);box.addView(qty);box.addView(price);new AlertDialog.Builder(this).setTitle(editIndex>=0?"Edit item":"Add item").setView(box).setPositiveButton(editIndex>=0?"Save":"Add",(d,w)->{LineItem x=new LineItem(cat.getText().toString().trim(),name.getText().toString().trim(),spec.getText().toString().trim(),qty.getText().toString().trim(),price.getText().toString().trim());if(x.name.isEmpty())x.name="Custom item";if(editIndex>=0)draft.items.set(editIndex,x);else draft.items.add(x);wizardStep=2;showWizard();}).setNegativeButton("Cancel",null).show();}
    private View itemCard(int idx,LineItem it){LinearLayout c=card();c.setPadding(dp(14),dp(13),dp(14),dp(13));LinearLayout.LayoutParams cp=(LinearLayout.LayoutParams)c.getLayoutParams();cp.bottomMargin=dp(9);c.setLayoutParams(cp);LinearLayout top=row();TextView n=text(it.name,15,true,INK);n.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));top.addView(n);top.addView(iconAction("✎",NAVY,v->showItemEditor(it,idx)));top.addView(iconAction("×",Color.rgb(184,61,61),v->{draft.items.remove(idx);showWizard();}));c.addView(top);c.addView(text(it.category+(it.spec.isEmpty()?"":" · "+it.spec),12,false,MUTED));LinearLayout chips=row();chips.addView(chip("Qty "+safe(it.qty),Color.rgb(238,247,244),EMERALD));chips.addView(chip("Price "+(it.price.isEmpty()?"—":it.price),Color.rgb(252,246,236),AMBER));LinearLayout.LayoutParams chp=new LinearLayout.LayoutParams(-1,-2);chp.topMargin=dp(8);chips.setLayoutParams(chp);c.addView(chips);return c;}
    private View photoRow(int idx,String uri){LinearLayout r=card();r.setPadding(dp(12),dp(10),dp(12),dp(10));LinearLayout.LayoutParams lp=(LinearLayout.LayoutParams)r.getLayoutParams();lp.bottomMargin=dp(8);r.setLayoutParams(lp);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);TextView icon=text("▧",22,true,EMERALD);r.addView(icon,new LinearLayout.LayoutParams(dp(38),dp(38)));TextView name=text(displayName(Uri.parse(uri)),12,true,INK);name.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));r.addView(name);r.addView(iconAction("×",Color.rgb(184,61,61),v->{draft.photos.remove(idx);showWizard();}));return r;}

    private void showPreview(){captureVisibleFields();clearContent();buildBottomNav("new");LinearLayout page=vertical(0);content.addView(page,new LinearLayout.LayoutParams(-1,-1));page.addView(topBar("Offer Preview","Review before saving or exporting",v->{wizardStep=3;showWizard();}));ScrollView sc=new ScrollView(this);LinearLayout root=vertical(dp(18));sc.addView(root);page.addView(sc,new LinearLayout.LayoutParams(-1,0,1));root.addView(previewPaper());LinearLayout actions=row();actions.setPadding(dp(18),dp(10),dp(18),dp(14));Button save=button("Save offer",NAVY,WHITE);Button pdf=button("Export PDF",EMERALD,WHITE);actions.addView(save,new LinearLayout.LayoutParams(0,dp(52),1));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,dp(52),1);pp.leftMargin=dp(8);actions.addView(pdf,pp);page.addView(actions);save.setOnClickListener(v->{saveOffer();showSaved();});pdf.setOnClickListener(v->{saveOffer();createPdf();});}
    private View previewPaper(){LinearLayout p=card();p.setPadding(dp(18),dp(18),dp(18),dp(22));TextView brand=text("INFINITY GREEN POWER",12,true,EMERALD);p.addView(brand);p.addView(text("Solar System Offer",25,true,NAVY));p.addView(text("Professional quotation preview",12,false,MUTED));View line=new View(this);line.setBackgroundColor(EMERALD);LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(-1,dp(3));l.topMargin=dp(14);l.bottomMargin=dp(14);line.setLayoutParams(l);p.addView(line);p.addView(previewSection("CLIENT",new String[][]{{"Client",emptyDash(draft.client)},{"Phone",emptyDash(draft.phone)},{"Location",emptyDash(draft.location)},{"Date",emptyDash(draft.date)}}));p.addView(previewSection("SYSTEM",new String[][]{{"Type",draft.system},{"Capacity",emptyDash(draft.capacity)},{"Phase",draft.phase}}));TextView ih=text("ITEMS",11,true,EMERALD);LinearLayout.LayoutParams ihp=new LinearLayout.LayoutParams(-1,-2);ihp.topMargin=dp(16);ihp.bottomMargin=dp(6);ih.setLayoutParams(ihp);p.addView(ih);if(draft.items.isEmpty())p.addView(text("No items added",13,false,MUTED));else for(LineItem x:draft.items)p.addView(previewItem(x));p.addView(previewSection("DETAILS",new String[][]{{"Installation",draft.installation?"Included":"Not included"},{"Transport",draft.transport?"Included":"Not included"},{"Organizer",emptyDash(draft.organizer)},{"Photos",String.valueOf(draft.photos.size())}}));if(!draft.notes.isEmpty()){TextView nh=text("Notes",12,true,INK);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-1,-2);np.topMargin=dp(12);nh.setLayoutParams(np);p.addView(nh);p.addView(text(draft.notes,12,false,MUTED));}return p;}
    private View previewSection(String title,String[][] rows){LinearLayout b=vertical(0);TextView h=text(title,11,true,EMERALD);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,-2);hp.topMargin=dp(12);hp.bottomMargin=dp(5);h.setLayoutParams(hp);b.addView(h);for(String[] r:rows){LinearLayout x=row();x.setPadding(0,dp(5),0,dp(5));TextView k=text(r[0],12,false,MUTED);k.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));TextView v=text(r[1],12,true,INK);v.setGravity(Gravity.RIGHT);v.setLayoutParams(new LinearLayout.LayoutParams(0,-2,2));x.addView(k);x.addView(v);b.addView(x);}return b;}
    private View previewItem(LineItem x){LinearLayout r=row();r.setPadding(0,dp(8),0,dp(8));r.setBackground(round(Color.rgb(249,250,252),10,0,0));TextView n=text(x.name+(x.spec.isEmpty()?"":" · "+x.spec),12,true,INK);n.setLayoutParams(new LinearLayout.LayoutParams(0,-2,2));TextView q=text("× "+safe(x.qty),12,true,EMERALD);q.setGravity(Gravity.CENTER);q.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));TextView pr=text(x.price.isEmpty()?"—":x.price,12,true,NAVY);pr.setGravity(Gravity.RIGHT);pr.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));r.addView(n);r.addView(q);r.addView(pr);return r;}

    private void showSaved(){clearContent();buildBottomNav("saved");LinearLayout page=vertical(0);content.addView(page,new LinearLayout.LayoutParams(-1,-1));page.addView(topBar("Saved Offers","Your quotation history",v->showHome()));ScrollView s=new ScrollView(this);LinearLayout root=vertical(dp(18));s.addView(root);page.addView(s,new LinearLayout.LayoutParams(-1,0,1));JSONArray arr=savedOffers();if(arr.length()==0)root.addView(empty("No saved offers","Create your first offer from the New Offer tab."));else for(int i=arr.length()-1;i>=0;i--){JSONObject o=arr.optJSONObject(i);if(o!=null)root.addView(savedCard(i,Draft.from(o)));}}
    private View savedCard(int index,Draft d){LinearLayout c=card();c.setPadding(dp(15),dp(14),dp(15),dp(14));LinearLayout.LayoutParams lp=(LinearLayout.LayoutParams)c.getLayoutParams();lp.bottomMargin=dp(10);c.setLayoutParams(lp);LinearLayout top=row();TextView n=text(d.client.isEmpty()?"Unnamed client":d.client,16,true,INK);n.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));top.addView(n);TextView status=chip("Saved",SOFT,EMERALD);top.addView(status);c.addView(top);c.addView(text(d.system+" · "+(d.capacity.isEmpty()?"No capacity":d.capacity)+" · "+d.date,12,false,MUTED));c.addView(text(d.items.size()+" items · "+d.photos.size()+" photos",12,false,MUTED));LinearLayout a=row();LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,-2);ap.topMargin=dp(10);a.setLayoutParams(ap);TextView open=tagButton("Open",NAVY,Color.rgb(238,244,250),v->{draft=d;showPreview();});TextView edit=tagButton("Edit",EMERALD,SOFT,v->{draft=d;wizardStep=0;showWizard();});TextView del=tagButton("Delete",Color.rgb(184,61,61),Color.rgb(255,240,240),v->{deleteSaved(index);showSaved();});a.addView(open);a.addView(edit);a.addView(del);c.addView(a);return c;}

    private void showCatalogScreen(){clearContent();buildBottomNav("catalog");LinearLayout page=vertical(0);content.addView(page,new LinearLayout.LayoutParams(-1,-1));page.addView(topBar("Product Catalog",catalog.size()+" ready-to-use items",v->showHome()));LinearLayout tools=vertical(dp(14));EditText search=new EditText(this);search.setHint("Search catalog");search.setSingleLine(true);search.setBackground(round(WHITE,16,LINE,1));search.setPadding(dp(14),0,dp(14),0);tools.addView(search,new LinearLayout.LayoutParams(-1,dp(50)));page.addView(tools);ListView list=new ListView(this);page.addView(list,new LinearLayout.LayoutParams(-1,0,1));ArrayList<Product> filtered=new ArrayList<>(catalog);ArrayList<String> labels=new ArrayList<>();for(Product p:filtered)labels.add(p.category+"\n"+p.display());ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,labels);list.setAdapter(a);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int af){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int st,int b,int c){String q=s.toString().toLowerCase(Locale.ROOT);filtered.clear();labels.clear();for(Product p:catalog)if(q.isEmpty()||p.searchable().contains(q)){filtered.add(p);labels.add(p.category+" — "+p.display());}a.notifyDataSetChanged();}});list.setOnItemClickListener((p,v,pos,id)->Toast.makeText(this,filtered.get(pos).display(),Toast.LENGTH_SHORT).show());}

    private void saveOffer(){captureVisibleFields();if(draft.id.isEmpty())draft.id=String.valueOf(System.currentTimeMillis());SharedPreferences sp=getSharedPreferences("offer_studio",MODE_PRIVATE);JSONArray arr=savedOffers();JSONArray out=new JSONArray();boolean replaced=false;for(int i=0;i<arr.length();i++){JSONObject o=arr.optJSONObject(i);if(o!=null&&draft.id.equals(o.optString("id"))){out.put(draft.json());replaced=true;}else if(o!=null)out.put(o);}if(!replaced)out.put(draft.json());sp.edit().putString("offers",out.toString()).apply();Toast.makeText(this,"Offer saved",Toast.LENGTH_SHORT).show();}
    private JSONArray savedOffers(){try{return new JSONArray(getSharedPreferences("offer_studio",MODE_PRIVATE).getString("offers","[]"));}catch(Exception e){return new JSONArray();}}
    private void deleteSaved(int index){JSONArray arr=savedOffers(),out=new JSONArray();for(int i=0;i<arr.length();i++)if(i!=index)out.put(arr.opt(i));getSharedPreferences("offer_studio",MODE_PRIVATE).edit().putString("offers",out.toString()).apply();}

    private void pickImages(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,PICK_IMAGES);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==PICK_IMAGES&&res==RESULT_OK&&data!=null){if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount();i++)rememberUri(data.getClipData().getItemAt(i).getUri(),data.getFlags());}else if(data.getData()!=null)rememberUri(data.getData(),data.getFlags());wizardStep=3;showWizard();}}
    private void rememberUri(Uri u,int flags){try{getContentResolver().takePersistableUriPermission(u,flags&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(Exception ignored){}String s=u.toString();if(!draft.photos.contains(s))draft.photos.add(s);}

    private void createPdf(){
        try{File dir=getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS);if(dir==null)throw new Exception("Storage unavailable");dir.mkdirs();String safe=draft.client.replaceAll("[^\\p{L}\\p{N}_-]","_");if(safe.isEmpty())safe="Offer";File f=new File(dir,"IGP_Offer_"+safe+"_"+System.currentTimeMillis()+".pdf");PdfDocument doc=new PdfDocument();Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);PdfDocument.Page pg=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=pg.getCanvas();c.drawColor(WHITE);pdfHeader(c,p);int y=105;y=pdfSection(c,p,y,"CLIENT");y=pdfRow(c,p,y,"Client",emptyDash(draft.client));y=pdfRow(c,p,y,"Phone",emptyDash(draft.phone));y=pdfRow(c,p,y,"Location",emptyDash(draft.location));y=pdfRow(c,p,y,"Date",emptyDash(draft.date));y+=8;y=pdfSection(c,p,y,"SYSTEM");y=pdfRow(c,p,y,"Type",draft.system);y=pdfRow(c,p,y,"Capacity",emptyDash(draft.capacity));y=pdfRow(c,p,y,"Phase",draft.phase);y+=8;y=pdfSection(c,p,y,"ITEMS");y=pdfItems(c,p,y);y+=8;y=pdfSection(c,p,y,"DETAILS");y=pdfRow(c,p,y,"Installation",draft.installation?"Included":"Not included");y=pdfRow(c,p,y,"Transport",draft.transport?"Included":"Not included");y=pdfRow(c,p,y,"Organizer",emptyDash(draft.organizer));y=pdfRow(c,p,y,"Photos",String.valueOf(draft.photos.size()));if(!draft.notes.isEmpty()){p.setColor(INK);p.setTextSize(10);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("Notes",40,y+18,p);p.setTypeface(Typeface.DEFAULT);p.setColor(MUTED);c.drawText(trim(draft.notes,72),40,y+36,p);}pdfFooter(c,p);doc.finishPage(pg);
        for(int i=0;i<draft.photos.size();i++){Bitmap b=decode(Uri.parse(draft.photos.get(i)));if(b==null)continue;PdfDocument.Page pp=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,i+2).create());Canvas cc=pp.getCanvas();cc.drawColor(WHITE);p.setColor(NAVY);p.setTextSize(20);p.setTypeface(Typeface.DEFAULT_BOLD);cc.drawText("Site Photo "+(i+1),40,45,p);float scale=Math.min(515f/b.getWidth(),700f/b.getHeight());int nw=(int)(b.getWidth()*scale),nh=(int)(b.getHeight()*scale),left=(595-nw)/2,top=85;cc.drawBitmap(b,null,new Rect(left,top,left+nw,top+nh),null);pdfFooter(cc,p);doc.finishPage(pp);b.recycle();}
        FileOutputStream out=new FileOutputStream(f);doc.writeTo(out);out.close();doc.close();Uri u=new Uri.Builder().scheme("content").authority(getPackageName()+".provider").appendPath(f.getName()).build();Intent share=new Intent(Intent.ACTION_SEND);share.setType("application/pdf");share.putExtra(Intent.EXTRA_STREAM,u);share.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(share,"Share offer"));}catch(Exception e){Toast.makeText(this,"PDF error: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    private void pdfHeader(Canvas c,Paint p){p.setColor(NAVY);p.setTextSize(25);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("INFINITY GREEN POWER",40,42,p);p.setColor(EMERALD);p.setTextSize(13);c.drawText("SOLAR SYSTEM OFFER",40,65,p);p.setColor(EMERALD);c.drawRect(40,82,555,85,p);}
    private int pdfSection(Canvas c,Paint p,int y,String s){p.setColor(NAVY);c.drawRoundRect(40,y,555,y+24,9,9,p);p.setColor(WHITE);p.setTextSize(11);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText(s,50,y+16,p);return y+32;}
    private int pdfRow(Canvas c,Paint p,int y,String k,String v){p.setTextSize(10);p.setTypeface(Typeface.DEFAULT_BOLD);p.setColor(MUTED);c.drawText(k,45,y+15,p);p.setColor(INK);p.setTypeface(Typeface.DEFAULT);c.drawText(v,180,y+15,p);p.setColor(LINE);c.drawLine(40,y+23,555,y+23,p);return y+27;}
    private int pdfItems(Canvas c,Paint p,int y){p.setTextSize(9);p.setTypeface(Typeface.DEFAULT_BOLD);p.setColor(EMERALD);c.drawText("ITEM",45,y+15,p);c.drawText("SPEC",290,y+15,p);c.drawText("QTY",430,y+15,p);c.drawText("PRICE",490,y+15,p);y+=22;for(LineItem x:draft.items){p.setTypeface(Typeface.DEFAULT);p.setColor(INK);c.drawText(trim(x.name,34),45,y+14,p);c.drawText(trim(x.spec,18),290,y+14,p);c.drawText(safe(x.qty),435,y+14,p);c.drawText(x.price.isEmpty()?"—":trim(x.price,10),490,y+14,p);p.setColor(LINE);c.drawLine(40,y+22,555,y+22,p);y+=26;if(y>690)break;}if(draft.items.isEmpty()){p.setColor(MUTED);c.drawText("No items added",45,y+14,p);y+=25;}return y;}
    private void pdfFooter(Canvas c,Paint p){p.setColor(EMERALD);p.setTextSize(9);p.setTypeface(Typeface.DEFAULT);c.drawText("Infinity Green Power · Generated by Offer Studio",40,820,p);}

    private Bitmap decode(Uri u){try{InputStream a=getContentResolver().openInputStream(u);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeStream(a,null,o);if(a!=null)a.close();int s=1;while(o.outWidth/s>1200||o.outHeight/s>1200)s*=2;BitmapFactory.Options b=new BitmapFactory.Options();b.inSampleSize=s;InputStream in=getContentResolver().openInputStream(u);Bitmap bm=BitmapFactory.decodeStream(in,null,b);if(in!=null)in.close();return bm;}catch(Exception e){return null;}}

    private View topBar(String title,String sub,View.OnClickListener back){LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(14),dp(12),dp(14),dp(12));bar.setBackgroundColor(WHITE);TextView b=text("‹",36,false,INK);b.setGravity(Gravity.CENTER);b.setOnClickListener(back);bar.addView(b,new LinearLayout.LayoutParams(dp(44),dp(48)));LinearLayout tw=vertical(0);TextView t=text(title,20,true,INK);TextView s=text(sub,11,false,MUTED);tw.addView(t);tw.addView(s);bar.addView(tw,new LinearLayout.LayoutParams(0,-2,1));return bar;}
    private View stepHeader(String title,String sub){LinearLayout w=vertical(0);TextView t=text(title,24,true,INK);TextView s=text(sub,13,false,MUTED);w.addView(t);w.addView(s);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(18);w.setLayoutParams(lp);return w;}
    private TextView label(String s){TextView t=text(s,13,true,INK);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(7);t.setLayoutParams(lp);return t;}
    private EditText field(LinearLayout p,String label,String hint,String value){p.addView(label(label));EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setSingleLine(true);e.setTextSize(15);e.setTextColor(INK);e.setHintTextColor(Color.rgb(154,166,177));e.setBackground(round(WHITE,16,LINE,1));e.setPadding(dp(14),0,dp(14),0);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.bottomMargin=dp(14);e.setLayoutParams(lp);p.addView(e);return e;}
    private EditText fieldMulti(LinearLayout p,String label,String hint,String value){p.addView(label(label));EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextSize(15);e.setTextColor(INK);e.setHintTextColor(Color.rgb(154,166,177));e.setGravity(Gravity.TOP);e.setBackground(round(WHITE,16,LINE,1));e.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(110));lp.bottomMargin=dp(14);e.setLayoutParams(lp);p.addView(e);return e;}
    private EditText miniField(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setSingleLine(true);e.setBackground(round(Color.rgb(248,250,252),14,LINE,1));e.setPadding(dp(12),0,dp(12),0);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(48));lp.bottomMargin=dp(8);e.setLayoutParams(lp);return e;}
    private void tag(EditText e,String s){e.setTag(s);}
    private LinearLayout infoBox(String title,String body){LinearLayout b=vertical(dp(14));b.setBackground(round(Color.rgb(238,247,244),16,0,0));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(10);b.setLayoutParams(lp);b.addView(text(title,12,true,EMERALD));b.addView(text(body,12,false,Color.rgb(55,91,78)));return b;}
    private LinearLayout empty(String title,String sub){LinearLayout e=vertical(dp(18));e.setGravity(Gravity.CENTER);e.setBackground(round(Color.rgb(250,251,252),18,LINE,1));e.addView(centerText(title,14,true,INK));e.addView(centerText(sub,12,false,MUTED));return e;}
    private TextView centerText(String s,int z,boolean b,int c){TextView t=text(s,z,b,c);t.setGravity(Gravity.CENTER);return t;}
    private TextView iconAction(String s,int c,View.OnClickListener l){TextView t=text(s,19,true,c);t.setGravity(Gravity.CENTER);t.setOnClickListener(l);return t;}
    private TextView tagButton(String s,int fg,int bg,View.OnClickListener l){TextView t=text(s,12,true,fg);t.setGravity(Gravity.CENTER);t.setBackground(round(bg,12,0,0));t.setPadding(dp(11),dp(7),dp(11),dp(7));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.rightMargin=dp(7);t.setLayoutParams(lp);t.setOnClickListener(l);return t;}
    private TextView chip(String s,int bg,int fg){TextView t=text(s,11,true,fg);t.setGravity(Gravity.CENTER);t.setBackground(round(bg,12,0,0));t.setPadding(dp(9),dp(6),dp(9),dp(6));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.rightMargin=dp(7);t.setLayoutParams(lp);return t;}
    private Button button(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setTextColor(fg);b.setTextSize(14);b.setTypeface(Typeface.DEFAULT_BOLD);b.setAllCaps(false);b.setBackground(round(bg,16,0,0));return b;}
    private LinearLayout card(){LinearLayout c=vertical(0);c.setBackground(round(WHITE,20,LINE,1));c.setElevation(dp(2));c.setLayoutParams(new LinearLayout.LayoutParams(-1,-2));return c;}
    private LinearLayout vertical(int pad){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(pad,pad,pad,pad);return l;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private TextView text(String s,int size,boolean bold,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}
    private GradientDrawable round(int color,int radius,int strokeColor,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));if(stroke>0)g.setStroke(dp(stroke),strokeColor);return g;}
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private int withAlpha(int color,int alpha){return Color.argb(alpha,Color.red(color),Color.green(color),Color.blue(color));}
    private String safe(String s){return s==null||s.trim().isEmpty()?"1":s.trim();}
    private String emptyDash(String s){return s==null||s.trim().isEmpty()?"—":s.trim();}
    private String trim(String s,int n){if(s==null)return"";return s.length()<=n?s:s.substring(0,n-1)+"…";}
    private String displayName(Uri u){try{Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&i>=0){String n=c.getString(i);c.close();return n;}c.close();}}catch(Exception ignored){}String s=u.getLastPathSegment();return s==null?"image":s;}
    private void hideKeyboard(){try{View v=getCurrentFocus();if(v!=null)((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);}catch(Exception ignored){}}
}
