package com.infinitygreenpower.solarform;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class OfferMakerActivity extends Activity {
    private final int NAVY=Color.rgb(15,55,96), NAVY2=Color.rgb(28,78,126), GREEN=Color.rgb(46,151,82), BG=Color.rgb(245,248,251), TEXT=Color.rgb(27,39,51), MUTED=Color.rgb(103,119,134), BORDER=Color.rgb(220,228,236), SOFT=Color.rgb(249,251,253);
    private final int PICK_IMAGES=4401;
    private LinearLayout host, itemsBox, photosBox;
    private EditText clientName, phone, location, date, sizeKw, notes, organizer;
    private Spinner systemType, phase;
    private CheckBox installation, transport;
    private final ArrayList<Product> catalog=new ArrayList<>();
    private final ArrayList<Item> items=new ArrayList<>();
    private final ArrayList<Uri> photoUris=new ArrayList<>();
    private boolean editingExisting=false;
    private String editingId="";

    static class Product { String material,model,capacity; Product(String a,String b,String c){material=a;model=b;capacity=c;} String display(){return material+" — "+model+(capacity.isEmpty()?"":" — "+capacity);} String searchable(){return display().toLowerCase(Locale.ROOT);} }
    static class Item { String material,model,capacity,qty,price; Item(String a,String b,String c,String d,String e){material=a;model=b;capacity=c;qty=d;price=e;} }

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);seedCatalog();showHome();}

    private void seedCatalog(){
        catalog.clear();
        catalog.add(new Product("الإنفرتر","Roypow RS6500 Hybrid","6.5 kW"));
        catalog.add(new Product("الإنفرتر","Deye Hybrid - Single Phase","6 kW"));
        catalog.add(new Product("الإنفرتر","Deye Hybrid - Single Phase","8 kW"));
        catalog.add(new Product("الإنفرتر","Deye Hybrid - Single Phase","12 kW"));
        catalog.add(new Product("الإنفرتر","Deye Hybrid - Single Phase","16 kW"));
        catalog.add(new Product("الإنفرتر","Deye Hybrid - Three Phase","12 kW"));
        catalog.add(new Product("الإنفرتر","Deye Hybrid - Three Phase","16 kW"));
        catalog.add(new Product("الإنفرتر","Deye On-Grid","حدد السعة"));
        catalog.add(new Product("الألواح الشمسية","Huasun HJT","610 W"));
        catalog.add(new Product("الألواح الشمسية","Huasun HJT","615 W"));
        catalog.add(new Product("الألواح الشمسية","Huasun HJT","620 W"));
        catalog.add(new Product("البطارية","Roypow LiFePO4","16 kWh"));
        catalog.add(new Product("البطارية","Deye High Voltage Battery Rack","HV"));
        catalog.add(new Product("BMS","Deye High Voltage BMS","HV"));
        catalog.add(new Product("القواعد","هيكل تثبيت ألواح شمسية","حسب الموقع"));
        catalog.add(new Product("كيبل DC","Solar DC Cable","حدد القياس"));
        catalog.add(new Product("كيبل AC","AC Cable","حدد القياس"));
        catalog.add(new Product("كيبل البطاريات","Battery Cable","حدد القياس"));
        catalog.add(new Product("صندوق حماية / تجميع","Protection Box / Combiner",""));
        catalog.add(new Product("قاطع DC","DC Breaker",""));
        catalog.add(new Product("قاطع AC","AC Breaker",""));
        catalog.add(new Product("حماية DC","DC SPD",""));
        catalog.add(new Product("حماية AC","AC SPD",""));
        catalog.add(new Product("موصلات","MC4 Connectors",""));
        catalog.add(new Product("لوحة توزيع","Distribution Board (DB)",""));
        catalog.add(new Product("تأريض","Earthing System",""));
        catalog.add(new Product("قضيب أرضي","Earth Rod",""));
        catalog.add(new Product("مسار كيبل","Cable Tray / PVC",""));
        catalog.add(new Product("تركيب","أجور تركيب",""));
    }

    private void showHome(){
        editingExisting=false; editingId="";
        ScrollView scroll=baseScroll(); host=baseHost(); scroll.addView(host);
        host.addView(homeHeader());
        LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.HORIZONTAL);stats.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);stats.setPadding(0,dp(14),0,0);
        stats.addView(statCard(String.valueOf(savedOffers().length()),"العروض المحفوظة",NAVY));
        stats.addView(statCard(String.valueOf(catalog.size()),"مواد الكتالوج",GREEN));host.addView(stats);
        TextView quick=label("إجراءات سريعة",17,true,TEXT);LinearLayout.LayoutParams qlp=new LinearLayout.LayoutParams(-1,-2);qlp.topMargin=dp(20);quick.setLayoutParams(qlp);host.addView(quick);
        host.addView(homeAction("＋","إنشاء عرض جديد","أدخل بيانات العميل والمنظومة والمواد ثم صدّر PDF",GREEN,v->showEditor(null)));
        host.addView(homeAction("▤","العروض المحفوظة","فتح، تعديل، معاينة أو حذف عروض سابقة",NAVY,v->showSavedOffers()));
        host.addView(homeAction("⌕","كتالوج المواد","تصفح المواد المتاحة للبحث والاختيار",NAVY2,v->showCatalogScreen()));
        host.addView(homeAction("⚙","حول التطبيق","Infinity Green Power Offer Maker — إصدار احترافي",Color.rgb(92,107,121),v->showAbout()));
        setContentView(scroll);
    }

    private View homeHeader(){
        LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(round(Color.WHITE,26,BORDER,1));
        LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);top.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);top.setGravity(Gravity.CENTER_VERTICAL);
        TextView logo=label("IGP",18,true,Color.WHITE);logo.setGravity(Gravity.CENTER);logo.setBackground(round(GREEN,19,GREEN,0));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(62),dp(62));lp.leftMargin=dp(13);logo.setLayoutParams(lp);top.addView(logo);
        LinearLayout tw=new LinearLayout(this);tw.setOrientation(LinearLayout.VERTICAL);tw.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));tw.addView(label("Infinity Green Power",15,true,GREEN));tw.addView(label("Offer Maker",28,true,NAVY));tw.addView(label("إنشاء عروض أسعار الطاقة الشمسية بسرعة واحترافية",13,false,MUTED));top.addView(tw);c.addView(top);
        View line=new View(this);line.setBackgroundColor(Color.rgb(230,237,244));LinearLayout.LayoutParams vlp=new LinearLayout.LayoutParams(-1,dp(1));vlp.topMargin=dp(16);vlp.bottomMargin=dp(13);line.setLayoutParams(vlp);c.addView(line);
        c.addView(label("اختر المواد، أضف عناصر مخصصة، أرفق صور الموقع، عاين العرض ثم صدّره PDF.",13,false,MUTED));return c;
    }

    private View statCard(String value,String title,int accent){
        LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(13),dp(14),dp(13));c.setBackground(round(Color.WHITE,20,BORDER,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.leftMargin=dp(5);lp.rightMargin=dp(5);c.setLayoutParams(lp);
        TextView v=label(value,25,true,accent);v.setGravity(Gravity.CENTER);TextView t=label(title,12,false,MUTED);t.setGravity(Gravity.CENTER);c.addView(v);c.addView(t);return c;
    }

    private View homeAction(String icon,String title,String sub,int accent,View.OnClickListener listener){
        LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.HORIZONTAL);c.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(14),dp(13),dp(14),dp(13));c.setBackground(round(Color.WHITE,20,BORDER,1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.topMargin=dp(10);c.setLayoutParams(cp);
        TextView i=label(icon,22,true,Color.WHITE);i.setGravity(Gravity.CENTER);i.setBackground(round(accent,16,accent,0));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(52),dp(52));ip.leftMargin=dp(12);i.setLayoutParams(ip);c.addView(i);
        LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);txt.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));txt.addView(label(title,16,true,TEXT));txt.addView(label(sub,12,false,MUTED));c.addView(txt);
        TextView arrow=label("‹",28,false,MUTED);c.addView(arrow);c.setOnClickListener(listener);return c;
    }

    private void showEditor(JSONObject data){
        ScrollView scroll=baseScroll();host=baseHost();scroll.addView(host);host.addView(screenBar(data==null?"عرض جديد":"تعديل العرض",v->showHome()));
        host.addView(editorHero());
        LinearLayout c1=section("01","معلومات العميل","البيانات الأساسية الخاصة بالعرض");
        clientName=field(c1,"اسم العميل","اكتب اسم العميل",false,android.text.InputType.TYPE_CLASS_TEXT);phone=field(c1,"رقم الهاتف","07xx xxx xxxx",false,android.text.InputType.TYPE_CLASS_PHONE);location=field(c1,"الموقع","المدينة / المنطقة",false,android.text.InputType.TYPE_CLASS_TEXT);date=field(c1,"التاريخ","YYYY/MM/DD",false,android.text.InputType.TYPE_CLASS_TEXT);date.setText(new SimpleDateFormat("yyyy/MM/dd",Locale.US).format(new Date()));
        LinearLayout c2=section("02","معلومات المنظومة","نوع النظام والسعة المطلوبة");systemType=spinner(c2,"نوع المنظومة",new String[]{"اختر نوع المنظومة","هجين","أون كريد","أوف كريد"});sizeKw=field(c2,"السعة المطلوبة (kW)","مثال: 8",false,android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);phase=spinner(c2,"الطور",new String[]{"اختر الطور","أحادي","ثلاثي"});
        LinearLayout c3=section("03","المواد","اختيار من الكتالوج أو إضافة عناصر مخصصة");LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);Button cat=smallButton("اختيار من الكتالوج",NAVY,Color.WHITE);Button custom=smallButton("مادة مخصصة",Color.WHITE,NAVY);((GradientDrawable)custom.getBackground()).setStroke(dp(1),BORDER);r.addView(cat);r.addView(custom);c3.addView(r);itemsBox=new LinearLayout(this);itemsBox.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams ibp=new LinearLayout.LayoutParams(-1,-2);ibp.topMargin=dp(10);itemsBox.setLayoutParams(ibp);c3.addView(itemsBox);cat.setOnClickListener(v->showCatalogDialog());custom.setOnClickListener(v->showItemDialog(new Item("","","","1",""),true,-1));
        LinearLayout c4=section("04","صور الموقع / المنظومة","إرفاق صور المعاينة مع العرض");Button photos=primary("إرفاق صور من الهاتف",NAVY);LinearLayout.LayoutParams pp=(LinearLayout.LayoutParams)photos.getLayoutParams();pp.height=dp(46);photos.setLayoutParams(pp);c4.addView(photos);photosBox=new LinearLayout(this);photosBox.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams pbox=new LinearLayout.LayoutParams(-1,-2);pbox.topMargin=dp(10);photosBox.setLayoutParams(pbox);c4.addView(photosBox);photos.setOnClickListener(v->pickImages());
        LinearLayout c5=section("05","معلومات إضافية","تفاصيل العرض النهائية");LinearLayout checks=new LinearLayout(this);checks.setOrientation(LinearLayout.HORIZONTAL);checks.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);installation=new CheckBox(this);installation.setText("يشمل التركيب");transport=new CheckBox(this);transport.setText("يشمل النقل");checks.addView(installation);checks.addView(transport);c5.addView(checks);notes=field(c5,"ملاحظات","أي ملاحظات أو شروط خاصة",true,android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);organizer=field(c5,"اسم منظم الكشف","اسم منظم الكشف",false,android.text.InputType.TYPE_CLASS_TEXT);
        items.clear();photoUris.clear();if(data!=null)loadIntoEditor(data);renderItems();renderPhotos();
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams alp=new LinearLayout.LayoutParams(-1,-2);alp.topMargin=dp(14);actions.setLayoutParams(alp);Button preview=primary("معاينة العرض",GREEN);actions.addView(preview);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);LinearLayout.LayoutParams rlp=new LinearLayout.LayoutParams(-1,-2);rlp.topMargin=dp(8);row.setLayoutParams(rlp);Button save=smallButton("حفظ العرض",Color.WHITE,NAVY);Button clear=smallButton("مسح",Color.WHITE,NAVY);((GradientDrawable)save.getBackground()).setStroke(dp(1),BORDER);((GradientDrawable)clear.getBackground()).setStroke(dp(1),BORDER);row.addView(save);row.addView(clear);actions.addView(row);host.addView(actions);
        preview.setOnClickListener(v->{JSONObject o=currentOffer();showPreview(o);});save.setOnClickListener(v->{saveCurrentOffer();Toast.makeText(this,"تم حفظ العرض",Toast.LENGTH_SHORT).show();});clear.setOnClickListener(v->showEditor(null));setContentView(scroll);
    }

    private View editorHero(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(round(Color.rgb(236,247,241),20,Color.rgb(210,235,220),1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(12);c.setLayoutParams(lp);c.addView(label("نموذج عرض سعر",18,true,GREEN));c.addView(label("املأ البيانات ثم أضف المواد. يمكنك حفظ العرض أو معاينته قبل التصدير.",12,false,Color.rgb(59,96,72)));return c;}

    private void showPreview(JSONObject o){
        ScrollView scroll=baseScroll();host=baseHost();scroll.addView(host);host.addView(screenBar("معاينة العرض",v->showEditor(o)));host.addView(previewHeader());
        host.addView(previewSection("معلومات العميل",new String[]{"اسم العميل",o.optString("client"),"رقم الهاتف",o.optString("phone"),"الموقع",o.optString("location"),"التاريخ",o.optString("date")}));
        host.addView(previewSection("معلومات المنظومة",new String[]{"نوع المنظومة",o.optString("system"),"السعة المطلوبة",o.optString("kw")+(o.optString("kw").isEmpty()?"":" kW"),"الطور",o.optString("phase")}));
        LinearLayout mat=sectionPreview("المواد");JSONArray arr=o.optJSONArray("items");if(arr==null||arr.length()==0)mat.addView(empty("لا توجد مواد","أضف مادة واحدة على الأقل قبل تصدير العرض."));else for(int i=0;i<arr.length();i++){JSONObject x=arr.optJSONObject(i);mat.addView(previewItem(x));}
        host.addView(previewSection("معلومات إضافية",new String[]{"التركيب",o.optBoolean("installation")?"نعم":"لا","النقل",o.optBoolean("transport")?"نعم":"لا","منظم الكشف",o.optString("organizer"),"ملاحظات",o.optString("notes")}));
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(14);actions.setLayoutParams(lp);Button pdf=primary("إنشاء PDF ومشاركته",GREEN);Button save=primary("حفظ العرض",NAVY);LinearLayout.LayoutParams sp=(LinearLayout.LayoutParams)save.getLayoutParams();sp.topMargin=dp(8);save.setLayoutParams(sp);actions.addView(pdf);actions.addView(save);host.addView(actions);pdf.setOnClickListener(v->{saveOfferObject(o);createPdf(o);});save.setOnClickListener(v->{saveOfferObject(o);Toast.makeText(this,"تم حفظ العرض",Toast.LENGTH_SHORT).show();showHome();});setContentView(scroll);
    }

    private View previewHeader(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackground(round(Color.WHITE,22,BORDER,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(12);c.setLayoutParams(lp);TextView co=label("INFINITY GREEN POWER",15,true,GREEN);co.setGravity(Gravity.CENTER);TextView title=label("استمارة طلب عرض سعر منظومة شمسية",21,true,NAVY);title.setGravity(Gravity.CENTER);TextView sub=label("نموذج منظم قبل إصدار عرض السعر",12,false,MUTED);sub.setGravity(Gravity.CENTER);c.addView(co);c.addView(title);c.addView(sub);return c;}

    private View previewSection(String title,String[] pairs){LinearLayout c=sectionPreview(title);for(int i=0;i+1<pairs.length;i+=2)c.addView(kv(pairs[i],pairs[i+1]));return c;}
    private LinearLayout sectionPreview(String title){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(14),dp(14),dp(14));card.setBackground(round(Color.WHITE,20,BORDER,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(12);card.setLayoutParams(lp);TextView h=label(title,16,true,Color.WHITE);h.setBackground(round(NAVY,13,NAVY,0));h.setPadding(dp(12),dp(8),dp(12),dp(8));card.addView(h);return card;}
    private View kv(String k,String v){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.setPadding(dp(4),dp(9),dp(4),dp(9));TextView a=label(k,13,true,TEXT);a.setLayoutParams(new LinearLayout.LayoutParams(0,-2,.35f));TextView b=label(v==null||v.isEmpty()?"—":v,13,false,TEXT);b.setLayoutParams(new LinearLayout.LayoutParams(0,-2,.65f));r.addView(a);r.addView(b);return r;}
    private View previewItem(JSONObject x){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(round(SOFT,15,BORDER,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);c.setLayoutParams(lp);c.addView(label(x.optString("material"),14,true,TEXT));c.addView(label(x.optString("model")+" • "+x.optString("capacity")+" • الكمية: "+x.optString("qty")+(x.optString("price").isEmpty()?"":" • السعر: "+x.optString("price")),12,false,MUTED));return c;}

    private void showSavedOffers(){
        ScrollView scroll=baseScroll();host=baseHost();scroll.addView(host);host.addView(screenBar("العروض المحفوظة",v->showHome()));JSONArray a=savedOffers();if(a.length()==0){LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,-2);ep.topMargin=dp(20);View e=empty("لا توجد عروض محفوظة","أنشئ أول عرض من الصفحة الرئيسية.");e.setLayoutParams(ep);host.addView(e);}else{for(int i=a.length()-1;i>=0;i--){JSONObject o=a.optJSONObject(i);host.addView(savedOfferCard(o));}}setContentView(scroll);
    }
    private View savedOfferCard(JSONObject o){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(13),dp(14),dp(13));c.setBackground(round(Color.WHITE,20,BORDER,1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.topMargin=dp(10);c.setLayoutParams(cp);c.addView(label(o.optString("client","بدون اسم"),16,true,TEXT));c.addView(label(o.optString("date")+"  •  "+o.optString("system")+"  •  "+o.optString("kw")+" kW",12,false,MUTED));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.topMargin=dp(9);r.setLayoutParams(rp);Button open=smallButton("فتح",NAVY,Color.WHITE);Button preview=smallButton("معاينة",GREEN,Color.WHITE);Button del=smallButton("حذف",Color.rgb(160,50,45),Color.WHITE);r.addView(open);r.addView(preview);r.addView(del);c.addView(r);open.setOnClickListener(v->showEditor(o));preview.setOnClickListener(v->showPreview(o));del.setOnClickListener(v->new AlertDialog.Builder(this).setMessage("حذف هذا العرض؟").setPositiveButton("حذف",(d,w)->{deleteOffer(o.optString("id"));showSavedOffers();}).setNegativeButton("إلغاء",null).show());return c;}

    private void showCatalogScreen(){ScrollView scroll=baseScroll();host=baseHost();scroll.addView(host);host.addView(screenBar("كتالوج المواد",v->showHome()));for(Product p:catalog){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(11),dp(14),dp(11));c.setBackground(round(Color.WHITE,16,BORDER,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);c.setLayoutParams(lp);c.addView(label(p.material,14,true,TEXT));c.addView(label(p.model+(p.capacity.isEmpty()?"":" • "+p.capacity),12,false,MUTED));host.addView(c);}setContentView(scroll);}
    private void showAbout(){new AlertDialog.Builder(this).setTitle("Infinity Green Power Offer Maker").setMessage("تطبيق لإعداد عروض أسعار منظومات الطاقة الشمسية مع كتالوج مواد، عناصر مخصصة، صور الموقع، حفظ العروض، المعاينة وتصدير PDF.\n\nVersion 2.0.0").setPositiveButton("حسناً",null).show();}

    private void showCatalogDialog(){final Dialog dialog=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(14),dp(14),dp(14));box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView title=label("اختيار مادة",18,true,NAVY);box.addView(title);EditText search=new EditText(this);search.setHint("بحث: Deye, Roypow, Huasun, كيبل...");search.setTextDirection(View.TEXT_DIRECTION_RTL);search.setGravity(Gravity.RIGHT);search.setPadding(dp(12),dp(10),dp(12),dp(10));search.setBackground(round(Color.WHITE,14,BORDER,1));LinearLayout.LayoutParams slp=new LinearLayout.LayoutParams(-1,dp(48));slp.topMargin=dp(10);box.addView(search,slp);ListView list=new ListView(this);LinearLayout.LayoutParams llp=new LinearLayout.LayoutParams(-1,dp(430));llp.topMargin=dp(8);box.addView(list,llp);final ArrayList<Product> filtered=new ArrayList<>(catalog);final ArrayList<String> names=new ArrayList<>();for(Product p:filtered)names.add(p.display());final ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,names);list.setAdapter(adapter);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){String q=s.toString().trim().toLowerCase(Locale.ROOT);filtered.clear();names.clear();for(Product p:catalog)if(q.isEmpty()||p.searchable().contains(q)){filtered.add(p);names.add(p.display());}adapter.notifyDataSetChanged();}public void afterTextChanged(Editable e){}});list.setOnItemClickListener((p,v,pos,id)->{Product x=filtered.get(pos);showItemDialog(new Item(x.material,x.model,x.capacity,"1",""),false,-1);dialog.dismiss();});dialog.setContentView(box);dialog.show();Window w=dialog.getWindow();if(w!=null)w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.94),WindowManager.LayoutParams.WRAP_CONTENT);}

    private void showItemDialog(Item base,boolean materialEditable,int editIndex){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(8),dp(14),0);box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);EditText material=dialogField(box,"المادة","اسم المادة");material.setText(base.material);material.setEnabled(materialEditable);EditText model=dialogField(box,"الماركة / الموديل","الموديل");model.setText(base.model);EditText cap=dialogField(box,"السعة / القياس","السعة");cap.setText(base.capacity);EditText qty=dialogField(box,"الكمية","1");qty.setText(base.qty.isEmpty()?"1":base.qty);EditText price=dialogField(box,"السعر (اختياري)","مثال: 900");price.setText(base.price);new AlertDialog.Builder(this).setTitle(editIndex>=0?"تعديل المادة":"إضافة المادة").setView(box).setPositiveButton(editIndex>=0?"حفظ":"إضافة",(d,w)->{Item it=new Item(material.getText().toString().trim(),model.getText().toString().trim(),cap.getText().toString().trim(),qty.getText().toString().trim(),price.getText().toString().trim());if(editIndex>=0)items.set(editIndex,it);else items.add(it);renderItems();}).setNegativeButton("إلغاء",null).show();}
    private EditText dialogField(LinearLayout p,String label,String hint){p.addView(label(label,13,true,TEXT));EditText e=new EditText(this);e.setHint(hint);e.setTextDirection(View.TEXT_DIRECTION_RTL);e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setPadding(dp(12),dp(9),dp(12),dp(9));e.setBackground(round(Color.WHITE,13,BORDER,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(46));lp.bottomMargin=dp(8);e.setLayoutParams(lp);p.addView(e);return e;}
    private void renderItems(){if(itemsBox==null)return;itemsBox.removeAllViews();if(items.isEmpty()){itemsBox.addView(empty("لا توجد مواد مضافة","ابدأ بالاختيار من الكتالوج أو أضف مادة مخصصة."));return;}for(int i=0;i<items.size();i++){final int idx=i;Item it=items.get(i);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(13),dp(11),dp(13),dp(11));c.setBackground(round(SOFT,16,BORDER,1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.bottomMargin=dp(8);c.setLayoutParams(cp);LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);top.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView title=label(it.material,15,true,TEXT);title.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));top.addView(title);top.addView(tag("حذف",Color.rgb(175,45,40),Color.rgb(255,239,239),v->{items.remove(idx);renderItems();}));top.addView(tag("تعديل",NAVY,Color.rgb(238,244,251),v->showItemDialog(new Item(it.material,it.model,it.capacity,it.qty,it.price),true,idx)));c.addView(top);c.addView(label(it.model+" • "+val(it.capacity)+" • الكمية: "+val(it.qty)+(it.price.isEmpty()?"":" • السعر: "+it.price),12,false,MUTED));itemsBox.addView(c);}}

    private void pickImages(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,PICK_IMAGES);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==PICK_IMAGES&&res==RESULT_OK&&data!=null){if(data.getClipData()!=null){ClipData cd=data.getClipData();for(int i=0;i<cd.getItemCount();i++)addPhoto(cd.getItemAt(i).getUri(),data.getFlags());}else if(data.getData()!=null)addPhoto(data.getData(),data.getFlags());renderPhotos();}}
    private void addPhoto(Uri u,int flags){try{getContentResolver().takePersistableUriPermission(u,flags&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(Exception ignored){}for(Uri x:photoUris)if(x.toString().equals(u.toString()))return;photoUris.add(u);}
    private void renderPhotos(){if(photosBox==null)return;photosBox.removeAllViews();if(photoUris.isEmpty()){photosBox.addView(empty("لا توجد صور مرفقة","يمكن إرفاق عدة صور للموقع أو المنظومة."));return;}for(int i=0;i<photoUris.size();i++){final int idx=i;LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.setPadding(dp(12),dp(9),dp(12),dp(9));r.setBackground(round(SOFT,14,BORDER,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(7);r.setLayoutParams(lp);TextView n=label("📷 "+displayName(photoUris.get(i)),12,false,TEXT);n.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));r.addView(n);r.addView(tag("حذف",Color.rgb(175,45,40),Color.rgb(255,239,239),v->{photoUris.remove(idx);renderPhotos();}));photosBox.addView(r);}}

    private JSONObject currentOffer(){JSONObject o=new JSONObject();try{o.put("id",editingExisting?editingId:UUID.randomUUID().toString());o.put("client",txt(clientName));o.put("phone",txt(phone));o.put("location",txt(location));o.put("date",txt(date));o.put("system",spin(systemType));o.put("kw",txt(sizeKw));o.put("phase",spin(phase));o.put("installation",installation.isChecked());o.put("transport",transport.isChecked());o.put("notes",txt(notes));o.put("organizer",txt(organizer));JSONArray ia=new JSONArray();for(Item it:items){JSONObject x=new JSONObject();x.put("material",it.material);x.put("model",it.model);x.put("capacity",it.capacity);x.put("qty",it.qty);x.put("price",it.price);ia.put(x);}o.put("items",ia);JSONArray pa=new JSONArray();for(Uri u:photoUris)pa.put(u.toString());o.put("photos",pa);}catch(Exception ignored){}return o;}
    private void loadIntoEditor(JSONObject o){editingExisting=true;editingId=o.optString("id",UUID.randomUUID().toString());clientName.setText(o.optString("client"));phone.setText(o.optString("phone"));location.setText(o.optString("location"));date.setText(o.optString("date"));sizeKw.setText(o.optString("kw"));notes.setText(o.optString("notes"));organizer.setText(o.optString("organizer"));setSpin(systemType,o.optString("system"));setSpin(phase,o.optString("phase"));installation.setChecked(o.optBoolean("installation"));transport.setChecked(o.optBoolean("transport"));JSONArray ia=o.optJSONArray("items");if(ia!=null)for(int i=0;i<ia.length();i++){JSONObject x=ia.optJSONObject(i);items.add(new Item(x.optString("material"),x.optString("model"),x.optString("capacity"),x.optString("qty"),x.optString("price")));}JSONArray pa=o.optJSONArray("photos");if(pa!=null)for(int i=0;i<pa.length();i++)photoUris.add(Uri.parse(pa.optString(i)));}
    private void saveCurrentOffer(){saveOfferObject(currentOffer());}
    private void saveOfferObject(JSONObject o){JSONArray a=savedOffers();JSONArray out=new JSONArray();boolean replaced=false;String id=o.optString("id");for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null&&x.optString("id").equals(id)){out.put(o);replaced=true;}else out.put(x);}if(!replaced)out.put(o);getSharedPreferences("offers",0).edit().putString("list",out.toString()).apply();editingExisting=true;editingId=id;}
    private JSONArray savedOffers(){try{return new JSONArray(getSharedPreferences("offers",0).getString("list","[]"));}catch(Exception e){return new JSONArray();}}
    private void deleteOffer(String id){JSONArray a=savedOffers();JSONArray out=new JSONArray();for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null&&!x.optString("id").equals(id))out.put(x);}getSharedPreferences("offers",0).edit().putString("list",out.toString()).apply();}

    private void createPdf(JSONObject o){try{File dir=getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS);if(dir==null)throw new Exception("Storage unavailable");if(!dir.exists())dir.mkdirs();String safe=o.optString("client","client").replaceAll("[^\\p{L}\\p{N}_-]","_");File file=new File(dir,"IGP_Offer_"+safe+"_"+System.currentTimeMillis()+".pdf");PdfDocument doc=new PdfDocument();Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);PdfDocument.Page page=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=page.getCanvas();c.drawColor(Color.WHITE);drawPdfHeader(c,p);int y=100;y=pdfSection(c,p,y,"1  معلومات العميل");y=pdfLine(c,p,"اسم العميل",o.optString("client"),y);y=pdfLine(c,p,"رقم الهاتف",o.optString("phone"),y);y=pdfLine(c,p,"الموقع",o.optString("location"),y);y=pdfLine(c,p,"التاريخ",o.optString("date"),y);y=pdfSection(c,p,y+7,"2  معلومات المنظومة");y=pdfLine(c,p,"نوع المنظومة",o.optString("system"),y);y=pdfLine(c,p,"السعة المطلوبة",o.optString("kw")+(o.optString("kw").isEmpty()?"":" kW"),y);y=pdfLine(c,p,"الطور",o.optString("phase"),y);y=pdfSection(c,p,y+7,"3  المواد الرئيسية");y=pdfItems(c,p,y,o.optJSONArray("items"));y=pdfSection(c,p,y+8,"4  معلومات إضافية");y=pdfLine(c,p,"التركيب",o.optBoolean("installation")?"نعم":"لا",y);y=pdfLine(c,p,"النقل",o.optBoolean("transport")?"نعم":"لا",y);y=pdfLine(c,p,"اسم منظم الكشف",o.optString("organizer"),y);y=pdfLine(c,p,"ملاحظات",trim(o.optString("notes"),60),y);pdfFooter(c,p);doc.finishPage(page);JSONArray photos=o.optJSONArray("photos");if(photos!=null)for(int i=0;i<photos.length();i++){Bitmap bmp=decode(Uri.parse(photos.optString(i)));if(bmp==null)continue;PdfDocument.Page pg=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,i+2).create());Canvas cc=pg.getCanvas();cc.drawColor(Color.WHITE);p.setColor(NAVY);p.setTextSize(20);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextAlign(Paint.Align.RIGHT);cc.drawText("صور الموقع / المنظومة",560,45,p);float scale=Math.min(500f/bmp.getWidth(),680f/bmp.getHeight());int nw=(int)(bmp.getWidth()*scale),nh=(int)(bmp.getHeight()*scale),left=(595-nw)/2,top=95+(680-nh)/2;cc.drawBitmap(bmp,null,new Rect(left,top,left+nw,top+nh),null);pdfFooter(cc,p);doc.finishPage(pg);bmp.recycle();}FileOutputStream out=new FileOutputStream(file);doc.writeTo(out);out.close();doc.close();Uri uri=new Uri.Builder().scheme("content").authority(getPackageName()+".provider").appendPath(file.getName()).build();Intent share=new Intent(Intent.ACTION_SEND);share.setType("application/pdf");share.putExtra(Intent.EXTRA_STREAM,uri);share.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(share,"مشاركة العرض"));}catch(Exception e){Toast.makeText(this,"تعذر إنشاء PDF: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    private void drawPdfHeader(Canvas c,Paint p){p.setColor(NAVY);p.setTextAlign(Paint.Align.RIGHT);p.setTextSize(22);p.setTypeface(Typeface.create("sans",Typeface.BOLD));c.drawText("استمارة طلب عرض سعر منظومة شمسية",560,38,p);p.setColor(GREEN);p.setTextSize(14);c.drawText("INFINITY GREEN POWER",560,60,p);p.setColor(GREEN);c.drawRect(35,78,560,81,p);}
    private int pdfSection(Canvas c,Paint p,int y,String s){p.setColor(NAVY);c.drawRoundRect(35,y,560,y+25,8,8,p);p.setColor(Color.WHITE);p.setTextSize(12);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextAlign(Paint.Align.RIGHT);c.drawText(s,550,y+17,p);return y+34;}
    private int pdfLine(Canvas c,Paint p,String k,String v,int y){p.setColor(TEXT);p.setTextSize(10.5f);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextAlign(Paint.Align.RIGHT);c.drawText(k+" :",555,y+15,p);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));c.drawText(v==null||v.isEmpty()?"—":v,430,y+15,p);p.setColor(Color.rgb(229,235,241));c.drawLine(35,y+24,560,y+24,p);return y+28;}
    private int pdfItems(Canvas c,Paint p,int y,JSONArray a){int[] xs={560,410,275,185,95,35};p.setColor(GREEN);c.drawRect(35,y,560,y+26,p);p.setColor(Color.WHITE);p.setTextSize(9.5f);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextAlign(Paint.Align.CENTER);String[] h={"المادة","الماركة / الموديل","السعة / القياس","الكمية","السعر"};for(int i=0;i<h.length;i++)c.drawText(h[i],(xs[i]+xs[i+1])/2f,y+17,p);y+=26;if(a==null||a.length()==0){p.setColor(SOFT);c.drawRect(35,y,560,y+30,p);p.setColor(MUTED);c.drawText("لا توجد مواد",297,y+19,p);return y+34;}for(int j=0;j<a.length();j++){JSONObject x=a.optJSONObject(j);p.setColor(j%2==0?Color.WHITE:SOFT);c.drawRect(35,y,560,y+28,p);p.setColor(BORDER);for(int xx:xs)c.drawLine(xx,y,xx,y+28,p);c.drawLine(35,y+28,560,y+28,p);p.setColor(TEXT);p.setTextSize(8.5f);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));p.setTextAlign(Paint.Align.CENTER);String[] vals={trim(x.optString("material"),14),trim(x.optString("model"),16),trim(x.optString("capacity"),12),trim(x.optString("qty"),7),trim(x.optString("price"),9)};for(int i=0;i<vals.length;i++)c.drawText(vals[i],(xs[i]+xs[i+1])/2f,y+17,p);y+=28;}return y;}
    private void pdfFooter(Canvas c,Paint p){p.setColor(GREEN);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(9);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));c.drawText("Infinity Green Power • Offer Maker",297,820,p);}
    private Bitmap decode(Uri u){try{InputStream is=getContentResolver().openInputStream(u);BitmapFactory.Options b=new BitmapFactory.Options();b.inJustDecodeBounds=true;BitmapFactory.decodeStream(is,null,b);if(is!=null)is.close();int sample=1;while(b.outWidth/sample>1100||b.outHeight/sample>1100)sample*=2;BitmapFactory.Options o=new BitmapFactory.Options();o.inSampleSize=sample;InputStream is2=getContentResolver().openInputStream(u);Bitmap bmp=BitmapFactory.decodeStream(is2,null,o);if(is2!=null)is2.close();return bmp;}catch(Exception e){return null;}}

    private ScrollView baseScroll(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(BG);return s;}
    private LinearLayout baseHost(){LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);h.setPadding(dp(16),dp(16),dp(16),dp(28));return h;}
    private View screenBar(String title,View.OnClickListener back){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView t=label(title,22,true,NAVY);t.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));r.addView(t);TextView b=label("‹",34,false,NAVY);b.setPadding(dp(12),0,dp(12),0);b.setOnClickListener(back);r.addView(b);return r;}
    private LinearLayout section(String num,String title,String sub){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(15),dp(15),dp(15));c.setBackground(round(Color.WHITE,21,BORDER,1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.topMargin=dp(13);c.setLayoutParams(cp);LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.HORIZONTAL);h.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);h.setGravity(Gravity.CENTER_VERTICAL);TextView badge=label(num,12,true,Color.WHITE);badge.setGravity(Gravity.CENTER);badge.setBackground(round(NAVY,11,NAVY,0));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(38),dp(26));bp.leftMargin=dp(10);badge.setLayoutParams(bp);h.addView(badge);LinearLayout tw=new LinearLayout(this);tw.setOrientation(LinearLayout.VERTICAL);tw.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));tw.addView(label(title,17,true,TEXT));tw.addView(label(sub,12,false,MUTED));h.addView(tw);c.addView(h);View line=new View(this);line.setBackgroundColor(Color.rgb(232,238,244));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(1));lp.topMargin=dp(11);lp.bottomMargin=dp(11);line.setLayoutParams(lp);c.addView(line);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);c.addView(body);host.addView(c);return body;}
    private EditText field(LinearLayout p,String label,String hint,boolean multi,int type){p.addView(label(label,13,true,TEXT));EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setTextColor(TEXT);e.setHintTextColor(Color.rgb(150,163,176));e.setTextDirection(View.TEXT_DIRECTION_RTL);e.setGravity(multi?Gravity.TOP|Gravity.RIGHT:Gravity.CENTER_VERTICAL|Gravity.RIGHT);e.setPadding(dp(13),dp(10),dp(13),dp(10));e.setBackground(round(Color.WHITE,14,BORDER,1));e.setInputType(type);if(multi)e.setSingleLine(false);else e.setSingleLine(true);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,multi?dp(100):dp(50));lp.bottomMargin=dp(11);e.setLayoutParams(lp);p.addView(e);return e;}
    private Spinner spinner(LinearLayout p,String label,String[] vals){p.addView(label(label,13,true,TEXT));Spinner s=new Spinner(this,Spinner.MODE_DROPDOWN);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,vals);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);s.setAdapter(a);s.setBackground(round(Color.WHITE,14,BORDER,1));s.setPadding(dp(10),dp(4),dp(10),dp(4));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50));lp.bottomMargin=dp(11);s.setLayoutParams(lp);p.addView(s);return s;}
    private Button primary(String text,int bg){Button b=new Button(this);b.setText(text);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(bg,17,bg,0));b.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(54)));return b;}
    private Button smallButton(String text,int bg,int fg){Button b=new Button(this);b.setText(text);b.setTextColor(fg);b.setTextSize(12);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(bg,14,bg==Color.WHITE?BORDER:bg,bg==Color.WHITE?1:0));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(43),1);lp.leftMargin=dp(4);lp.rightMargin=dp(4);b.setLayoutParams(lp);return b;}
    private TextView tag(String text,int fg,int bg,View.OnClickListener l){TextView t=label(text,11,true,fg);t.setBackground(round(bg,10,bg,0));t.setPadding(dp(9),dp(5),dp(9),dp(5));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.leftMargin=dp(6);t.setLayoutParams(lp);t.setOnClickListener(l);return t;}
    private View empty(String title,String sub){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(13),dp(14),dp(13));c.setBackground(round(SOFT,15,BORDER,1));c.addView(label(title,14,true,TEXT));c.addView(label(sub,12,false,MUTED));return c;}
    private TextView label(String s,int size,boolean bold,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setTextDirection(View.TEXT_DIRECTION_RTL);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}
    private GradientDrawable round(int fill,int radius,int strokeColor,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke>0)d.setStroke(dp(stroke),strokeColor);return d;}
    private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    private String txt(EditText e){return e.getText().toString().trim();}
    private String spin(Spinner s){String v=String.valueOf(s.getSelectedItem());return v.startsWith("اختر")?"":v;}
    private void setSpin(Spinner s,String v){for(int i=0;i<s.getCount();i++)if(String.valueOf(s.getItemAtPosition(i)).equals(v)){s.setSelection(i);break;}}
    private String val(String s){return s==null||s.trim().isEmpty()?"—":s;}
    private String trim(String s,int n){if(s==null)return"";s=s.trim();return s.length()<=n?s:s.substring(0,n-1)+"…";}
    private String displayName(Uri u){try{Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){int idx=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&idx>=0){String n=c.getString(idx);c.close();return n;}c.close();}}catch(Exception ignored){}return u.getLastPathSegment()==null?"image":u.getLastPathSegment();}
}
