package com.infinitygreenpower.solarform;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.provider.Settings;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;

import org.json.*;

import java.io.*;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.*;

/**
 * IGP Organizer Form v6.0.0 — clean rebuild.
 * No inheritance from any previous OfferStudio UI activity.
 * Preserves package/signing, existing SharedPreferences keys and catalog assets.
 */
public class OrganizerRebuildActivity extends Activity {
    private static final int PICK_PHOTOS=6101, PICK_LOGO=6102, SAVE_PDF=6103;
    private static final int BG=Color.rgb(244,248,252), TEAL=Color.rgb(28,196,163), TEAL_DARK=Color.rgb(18,158,132);
    private static final int NAVY=Color.rgb(19,50,76), MUTED=Color.rgb(118,132,146), BORDER=Color.rgb(224,230,236);
    private static final int RED=Color.rgb(190,66,66), AMBER=Color.rgb(189,128,35);

    private final DecimalFormat money=new DecimalFormat("#,##0.##");
    private final ArrayList<Product> catalog=new ArrayList<>();
    private final ArrayList<LineItem> items=new ArrayList<>();
    private final ArrayList<String> photos=new ArrayList<>();
    private final HashSet<String> includedPhotos=new HashSet<>();
    private Draft draft=new Draft();
    private LinearLayout root,body,bottom;
    private String screen="home", catalogFilter="ALL";
    private int step=0;
    private File pendingPdf;
    private SharedPreferences prefs,settingsPrefs;

    static class Product { String category,name; Product(String c,String n){category=c;name=n;} }
    static class LineItem { String category="",name="",qty="1",price=""; }
    static class Draft {
        String id="",client="",phone="",location="",date="",system="Hybrid",capacity="",phase="Single Phase",organizer="",notes="";
        boolean installation=true,transport=false;
    }

    @Override public void onCreate(Bundle state){
        super.onCreate(state);
        getWindow().setStatusBarColor(Color.WHITE);
        getWindow().setNavigationBarColor(Color.WHITE);
        if(Build.VERSION.SDK_INT>=23)getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
        prefs=getSharedPreferences("offer_studio",MODE_PRIVATE);
        settingsPrefs=getSharedPreferences("offer_studio_settings",MODE_PRIVATE);
        loadCatalog();
        installDefaultLogo();
        resetDraft();
        buildShell();
        showHome();
    }

    private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    private String lang(){return settingsPrefs.getString("lang","ar");}
    private boolean rtl(){return !"en".equals(lang());}
    private String tx(String en,String ar,String ku){return"ar".equals(lang())?ar:("ku".equals(lang())?ku:en);}
    private String currency(){return settingsPrefs.getString("currency","USD");}
    private String company(){return settingsPrefs.getString("company_name","Infinity Green Power");}

    private GradientDrawable shape(int fill,int stroke,int radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));if(stroke!=0)g.setStroke(dp(1),stroke);return g;}
    private TextView tv(String s,int sp,boolean bold,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);t.setTypeface(bold?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);t.setGravity(rtl()?Gravity.RIGHT:Gravity.LEFT);return t;}
    private TextView centerText(String s,int sp,boolean bold,int color){TextView t=tv(s,sp,bold,color);t.setGravity(Gravity.CENTER);return t;}
    private Button button(String s,int kind){
        Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(13);b.setTypeface(Typeface.DEFAULT_BOLD);b.setGravity(Gravity.CENTER);b.setMinHeight(0);b.setMinimumHeight(0);b.setPadding(dp(12),0,dp(12),0);if(Build.VERSION.SDK_INT>=21){b.setStateListAnimator(null);b.setElevation(0);}
        int fill=Color.WHITE,stroke=BORDER,fg=NAVY;
        if(kind==1){fill=TEAL;stroke=TEAL;fg=Color.WHITE;}else if(kind==2){fill=Color.WHITE;stroke=TEAL;fg=TEAL_DARK;}else if(kind==3){fill=Color.rgb(241,247,251);stroke=Color.rgb(206,221,232);fg=NAVY;}else if(kind==4){fill=Color.rgb(255,246,246);stroke=Color.rgb(240,201,201);fg=RED;}else if(kind==5){fill=NAVY;stroke=NAVY;fg=Color.WHITE;}
        b.setTextColor(fg);b.setBackground(shape(fill,stroke,16));return b;
    }
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(shape(Color.WHITE,BORDER,22));if(Build.VERSION.SDK_INT>=21)c.setElevation(dp(1));return c;}
    private TextView pill(String s,int fill,int fg){TextView p=centerText(s,11,true,fg);p.setPadding(dp(11),dp(6),dp(11),dp(6));p.setBackground(shape(fill,0,16));return p;}
    private EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextSize(15);e.setSingleLine(true);e.setPadding(dp(14),0,dp(14),0);e.setBackground(shape(Color.rgb(249,251,253),BORDER,15));e.setGravity(rtl()?Gravity.RIGHT|Gravity.CENTER_VERTICAL:Gravity.LEFT|Gravity.CENTER_VERTICAL);return e;}
    private EditText multiField(String hint,String value,int lines){EditText e=field(hint,value);e.setSingleLine(false);e.setMinLines(lines);e.setGravity((rtl()?Gravity.RIGHT:Gravity.LEFT)|Gravity.TOP);e.setPadding(dp(14),dp(12),dp(14),dp(12));return e;}
    private void addSpace(LinearLayout p,int h){Space s=new Space(this);p.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}

    private void buildShell(){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setLayoutDirection(rtl()?View.LAYOUT_DIRECTION_RTL:View.LAYOUT_DIRECTION_LTR);setContentView(root);
        FrameLayout frame=new FrameLayout(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);frame.addView(body,new FrameLayout.LayoutParams(-1,-1));root.addView(frame,new LinearLayout.LayoutParams(-1,0,1));
        bottom=new LinearLayout(this);bottom.setOrientation(LinearLayout.HORIZONTAL);bottom.setGravity(Gravity.CENTER);bottom.setPadding(dp(6),dp(6),dp(6),dp(7));bottom.setBackgroundColor(Color.WHITE);root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(76)));buildBottom();
    }

    private void buildBottom(){
        bottom.removeAllViews();
        addNav("⌂",tx("Home","الرئيسية","سەرەکی"),"home",()->showHome());
        addNav("▤",tx("Catalog","الكتالوج","کاتەلۆگ"),"catalog",()->showCatalog());
        addCenterNew();
        addNav("▣",tx("Saved","محفوظ","پاشەکەوتکراو"),"saved",()->showSaved());
        addNav("⚙",tx("Settings","الإعدادات","ڕێکخستنەکان"),"settings",()->showSettings());
    }
    private void addNav(String icon,String label,String id,Runnable run){LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.VERTICAL);n.setGravity(Gravity.CENTER);TextView i=centerText(icon,21,true,id.equals(screen)?TEAL:NAVY);TextView l=centerText(label,10,id.equals(screen),id.equals(screen)?TEAL:MUTED);n.addView(i);n.addView(l);n.setOnClickListener(v->run.run());bottom.addView(n,new LinearLayout.LayoutParams(0,-1,1));}
    private void addCenterNew(){LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.VERTICAL);n.setGravity(Gravity.CENTER);TextView plus=centerText("+",28,false,Color.WHITE);plus.setBackground(shape(TEAL,0,30));n.addView(plus,new LinearLayout.LayoutParams(dp(52),dp(52)));TextView l=centerText(tx("New","جديد","نوێ"),9,false,MUTED);n.addView(l);n.setOnClickListener(v->{resetDraft();step=0;showWizard();});bottom.addView(n,new LinearLayout.LayoutParams(0,-1,1));}

    private void clear(String newScreen){screen=newScreen;body.removeAllViews();buildBottom();}
    private LinearLayout pageScroll(){ScrollView s=new ScrollView(this);s.setFillViewport(true);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(18),dp(16),dp(18),dp(26));s.addView(p);body.addView(s,new LinearLayout.LayoutParams(-1,-1));return p;}
    private void title(LinearLayout p,String main,String sub){TextView m=tv(main,27,true,NAVY);p.addView(m);if(sub!=null&&!sub.isEmpty()){TextView s=tv(sub,12,false,MUTED);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(3);p.addView(s,lp);}addSpace(p,14);}

    /* HOME */
    private void showHome(){clear("home");LinearLayout p=pageScroll();
        LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);top.setGravity(Gravity.CENTER_VERTICAL);TextView brand=tv(company(),18,true,NAVY);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));TextView mark=pill("IGP",Color.rgb(231,250,246),TEAL_DARK);top.addView(mark);p.addView(top);addSpace(p,18);
        TextView hello=tv(tx("Organizer workspace","مساحة عمل المنظم","شوێنی کاری ڕێکخەر"),24,true,NAVY);p.addView(hello);p.addView(tv(tx("Fast, consistent preliminary solar forms","استمارات أولية سريعة ومنظمة للمنظومات الشمسية","فۆرمی سەرەتایی خێرا و ڕێکخراو"),12,false,MUTED));addSpace(p,16);
        LinearLayout hero=card();hero.setBackground(shape(TEAL,0,24));TextView h1=tv(tx("Create today’s form","أنشئ استمارة اليوم","فۆرمی ئەمڕۆ دروست بکە"),20,true,Color.WHITE);hero.addView(h1);hero.addView(tv(tx("Client → System → Materials → PDF","العميل ← المنظومة ← المواد ← PDF","کڕیار ← سیستەم ← ماددە ← PDF"),12,false,Color.WHITE));addSpace(hero,14);Button start=button(tx("+  New organizer form","+  استمارة جديدة","+  فۆرمی نوێ"),5);start.setOnClickListener(v->{resetDraft();step=0;showWizard();});hero.addView(start,new LinearLayout.LayoutParams(-1,dp(50)));p.addView(hero);addSpace(p,20);
        LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.addView(statCard(tx("Saved forms","الاستمارات","فۆرمەکان"),String.valueOf(savedArray().length())),new LinearLayout.LayoutParams(0,dp(96),1));Space gap=new Space(this);row.addView(gap,new LinearLayout.LayoutParams(dp(10),1));row.addView(statCard(tx("Catalog items","مواد الكتالوج","ماددەی کاتەلۆگ"),String.valueOf(catalog.size())),new LinearLayout.LayoutParams(0,dp(96),1));p.addView(row);addSpace(p,20);
        LinearLayout section=new LinearLayout(this);section.setOrientation(LinearLayout.HORIZONTAL);section.setGravity(Gravity.CENTER_VERTICAL);section.addView(tv(tx("Recent forms","أحدث الاستمارات","نوێترین فۆرمەکان"),18,true,NAVY),new LinearLayout.LayoutParams(0,-2,1));TextView all=tv(tx("View all","عرض الكل","هەموو ببینە"),12,true,TEAL_DARK);all.setOnClickListener(v->showSaved());section.addView(all);p.addView(section);addSpace(p,9);renderRecent(p,3);
    }
    private LinearLayout statCard(String label,String value){LinearLayout c=card();c.addView(tv(value,24,true,TEAL_DARK));c.addView(tv(label,11,false,MUTED));return c;}
    private void renderRecent(LinearLayout p,int max){JSONArray a=savedArray();int count=0;for(int i=a.length()-1;i>=0&&count<max;i--){JSONObject o=a.optJSONObject(i);if(o==null)continue;p.addView(savedMiniCard(o));addSpace(p,9);count++;}if(count==0){LinearLayout e=card();e.addView(tv(tx("No forms yet","لا توجد استمارات بعد","هێشتا هیچ فۆرمێک نییە"),14,true,NAVY));e.addView(tv(tx("Start with the + button below.","ابدأ بزر + في الأسفل.","بە دوگمەی + دەست پێ بکە."),11,false,MUTED));p.addView(e);}}
    private View savedMiniCard(JSONObject o){LinearLayout c=card();LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);String client=o.optString("client",tx("Unnamed client","عميل بدون اسم","کڕیاری بێ ناو"));LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);text.addView(tv(client,15,true,NAVY));text.addView(tv(o.optString("location","")+"  ·  "+o.optString("date",""),11,false,MUTED));r.addView(text,new LinearLayout.LayoutParams(0,-2,1));r.addView(pill(o.optString("capacity","—"),Color.rgb(233,249,245),TEAL_DARK));c.addView(r);c.setOnClickListener(v->{loadDraft(o);showPreview();});return c;}

    /* WIZARD */
    private void showWizard(){clear("new");LinearLayout p=pageScroll();wizardHeader(p);if(step==0)clientStep(p);else if(step==1)systemStep(p);else if(step==2)itemsStep(p);else finalStep(p);}
    private void wizardHeader(LinearLayout p){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);TextView back=centerText("‹",34,false,NAVY);back.setOnClickListener(v->{if(step>0){captureStep();step--;showWizard();}else showHome();});r.addView(back,new LinearLayout.LayoutParams(dp(42),dp(44)));r.addView(tv(tx("New form","عرض جديد","فۆرمی نوێ"),22,true,NAVY),new LinearLayout.LayoutParams(0,-2,1));p.addView(r);addSpace(p,10);LinearLayout steps=new LinearLayout(this);steps.setOrientation(LinearLayout.HORIZONTAL);String[] names={tx("Client","العميل","کڕیار"),tx("System","المنظومة","سیستەم"),tx("Materials","المواد","ماددە"),tx("Finish","النهاية","کۆتایی")};for(int i=0;i<4;i++){TextView s=centerText((i+1)+"  "+names[i],10,true,i==step?Color.WHITE:MUTED);s.setBackground(shape(i==step?TEAL:Color.WHITE,i==step?0:BORDER,16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(38),1);lp.leftMargin=dp(3);lp.rightMargin=dp(3);steps.addView(s,lp);}p.addView(steps);addSpace(p,20);}

    private EditText fClient,fPhone,fLocation,fDate,fCapacity,fOrganizer,fCustomNote;
    private Spinner fSystem,fPhase;
    private CheckBox fInstall,fTransport;
    private EditText fDayFrom,fDayTo,fNightAmp,fNightHours,fEmergencyAmp,fEmergencyDuration;

    private void clientStep(LinearLayout p){title(p,tx("Client details","بيانات العميل","زانیاری کڕیار"),tx("Record the visit details once.","أدخل بيانات الزيارة مرة واحدة.","زانیاری سەردان تۆمار بکە."));LinearLayout c=card();fClient=labeled(c,tx("Client name","اسم العميل","ناوی کڕیار"),draft.client);fPhone=labeled(c,tx("Phone","رقم الهاتف","تەلەفۆن"),draft.phone);fLocation=labeled(c,tx("Location","الموقع","شوێن"),draft.location);fDate=labeled(c,tx("Date","التاريخ","بەروار"),draft.date);p.addView(c);navButtons(p,true);}
    private EditText labeled(LinearLayout c,String label,String value){c.addView(tv(label,11,true,MUTED));EditText e=field(label,value);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.topMargin=dp(5);lp.bottomMargin=dp(12);c.addView(e,lp);return e;}

    private void systemStep(LinearLayout p){title(p,tx("System details","معلومات المنظومة","زانیاری سیستەم"),tx("Set the customer target, not the final engineering design.","حدد طلب العميل وليس التصميم الهندسي النهائي.","داواکاری کڕیار دیاری بکە."));LinearLayout c=card();c.addView(tv(tx("System type","نوع المنظومة","جۆری سیستەم"),11,true,MUTED));fSystem=new Spinner(this);String[] systems={tx("Hybrid","هجين","هایبرید"),tx("On-Grid","أون كريد","ئۆن گرید"),tx("Off-Grid","أوف كريد","ئۆف گرید")};fSystem.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,systems));fSystem.setSelection(draft.system.toLowerCase().contains("on")?1:(draft.system.toLowerCase().contains("off")?2:0));c.addView(fSystem,new LinearLayout.LayoutParams(-1,dp(48)));c.addView(tv(tx("Required capacity","السعة المطلوبة","توانای پێویست"),11,true,MUTED));fCapacity=field(tx("Example: 16 kW","مثال: 16 كيلو واط","نموونە: 16 kW"),draft.capacity);c.addView(fCapacity,new LinearLayout.LayoutParams(-1,dp(52)));addSpace(c,10);LinearLayout quick=new LinearLayout(this);quick.setOrientation(LinearLayout.HORIZONTAL);String[] q={"5","8","10","12","16","20","30"};for(String x:q){TextView ch=pill(x+" kW",Color.rgb(238,249,246),TEAL_DARK);ch.setGravity(Gravity.CENTER);ch.setOnClickListener(v->fCapacity.setText(x+" kW"));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(34),1);lp.leftMargin=dp(2);lp.rightMargin=dp(2);quick.addView(ch,lp);}c.addView(quick);addSpace(c,12);c.addView(tv(tx("Phase","الطور","فاز"),11,true,MUTED));fPhase=new Spinner(this);String[] phases={tx("Single phase","أحادي","یەک فاز"),tx("Three phase","ثلاثي","سێ فاز")};fPhase.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,phases));fPhase.setSelection(draft.phase.toLowerCase().contains("three")||draft.phase.contains("ثلاث")?1:0);c.addView(fPhase,new LinearLayout.LayoutParams(-1,dp(48)));p.addView(c);navButtons(p,false);}

    private void itemsStep(LinearLayout p){title(p,tx("Materials","مواد العرض","ماددەکان"),tx("Add only the required item names, quantities and optional estimated prices.","أضف المواد المطلوبة والكمية والسعر التقديري إن وجد.","تەنها ماددە و بڕ و نرخی خەمڵاندراو زیاد بکە."));LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button cat=button(tx("Browse catalog","اختيار من الكتالوج","لە کاتەلۆگ"),5);Button custom=button(tx("Custom item","مادة مخصصة","ماددەی تایبەت"),2);actions.addView(cat,new LinearLayout.LayoutParams(0,dp(50),1));Space gs=new Space(this);actions.addView(gs,new LinearLayout.LayoutParams(dp(8),1));actions.addView(custom,new LinearLayout.LayoutParams(0,dp(50),1));cat.setOnClickListener(v->showItemPicker(-1));custom.setOnClickListener(v->editItem(-1,null));p.addView(actions);addSpace(p,14);for(int i=0;i<items.size();i++){p.addView(itemCard(i,items.get(i)));addSpace(p,10);}if(items.isEmpty()){LinearLayout e=card();e.addView(tv(tx("No materials added yet","لم تتم إضافة مواد بعد","هێشتا ماددە زیاد نەکراوە"),14,true,NAVY));e.addView(tv(tx("Use the catalog or add a custom item.","استخدم الكتالوج أو أضف مادة مخصصة.","کاتەلۆگ بەکاربهێنە یان ماددەی تایبەت زیاد بکە."),11,false,MUTED));p.addView(e);}addSpace(p,10);LinearLayout total=card();total.addView(tv(tx("Estimated total","المجموع التقديري","کۆی خەمڵاندراو"),11,true,MUTED));total.addView(tv(currency()+" "+money.format(grandTotal()),22,true,TEAL_DARK));p.addView(total);navButtons(p,false);}
    private View itemCard(final int index,LineItem it){LinearLayout c=card();c.setPadding(dp(14),dp(13),dp(14),dp(13));LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(tv(it.name,16,true,NAVY),new LinearLayout.LayoutParams(0,-2,1));top.addView(pill(it.qty+" ×",Color.rgb(238,249,246),TEAL_DARK));c.addView(top);if(!it.price.isEmpty()){addSpace(c,5);c.addView(tv(tx("Unit price","السعر","نرخ")+": "+currency()+" "+it.price+"   ·   "+tx("Total","المجموع","کۆ")+": "+currency()+" "+money.format(lineTotal(it)),11,false,MUTED));}addSpace(c,10);LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.HORIZONTAL);Button edit=button(tx("Edit","تعديل","دەستکاری"),3),replace=button(tx("Replace","استبدال","گۆڕین"),2),del=button(tx("Delete","حذف","سڕینەوە"),4);a.addView(edit,new LinearLayout.LayoutParams(0,dp(40),1));a.addView(replace,new LinearLayout.LayoutParams(0,dp(40),1));a.addView(del,new LinearLayout.LayoutParams(0,dp(40),1));edit.setOnClickListener(v->editItem(index,it));replace.setOnClickListener(v->showItemPicker(index));del.setOnClickListener(v->{items.remove(index);showWizard();});c.addView(a);return c;}

    private void finalStep(LinearLayout p){title(p,tx("Additional information","معلومات إضافية","زانیاری زیاتر"),tx("Services, organizer, load note and site photos.","الخدمات والمنظم وملاحظة التحميل وصور الموقع.","خزمەتگوزاری و ڕێکخەر و تێبینی بار و وێنە."));LinearLayout services=card();services.addView(tv(tx("Included services","الخدمات المشمولة","خزمەتگوزارییەکان"),15,true,NAVY));fInstall=new CheckBox(this);fInstall.setText(tx("Installation included","التركيب مشمول","دامەزراندن ناوخۆیە"));fInstall.setChecked(draft.installation);fTransport=new CheckBox(this);fTransport.setText(tx("Transport included","النقل مشمول","گواستنەوە ناوخۆیە"));fTransport.setChecked(draft.transport);services.addView(fInstall);services.addView(fTransport);p.addView(services);addSpace(p,10);
        LinearLayout org=card();org.addView(tv(tx("Inspection organizer","منظم الكشف","ڕێکخەری پشکنین"),15,true,NAVY));fOrganizer=field(tx("Organizer name","اسم المنظم","ناوی ڕێکخەر"),draft.organizer);org.addView(fOrganizer,new LinearLayout.LayoutParams(-1,dp(52)));Button choose=button(tx("Choose organizer","اختيار منظم الكشف","ڕێکخەر هەڵبژێرە"),2);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(44));cp.topMargin=dp(8);org.addView(choose,cp);choose.setOnClickListener(v->chooseOrganizer());p.addView(org);addSpace(p,10);
        buildLoadNoteCard(p);addSpace(p,10);buildPhotoCard(p);addSpace(p,10);
        Button draftBtn=button(tx("Save draft","حفظ كمسودة","وەک ڕەشنووس پاشەکەوت"),3);draftBtn.setOnClickListener(v->{captureStep();saveCurrent();Toast.makeText(this,tx("Draft saved","تم حفظ المسودة","ڕەشنووس پاشەکەوت کرا"),Toast.LENGTH_SHORT).show();});p.addView(draftBtn,new LinearLayout.LayoutParams(-1,dp(48)));navButtons(p,false);
    }
    private void buildLoadNoteCard(LinearLayout p){LinearLayout c=card();c.addView(tv(tx("Load capacity note","ملاحظة قدرة التحمل","تێبینی توانای بار"),15,true,NAVY));c.addView(tv(tx("Fill only the values; the sentence is generated automatically.","املأ القيم فقط وسيتم إنشاء النص تلقائياً.","تەنها نرخەکان پڕ بکەرەوە؛ دەق خۆکار دروست دەبێت."),11,false,MUTED));addSpace(c,8);fDayFrom=labeled(c,tx("Daytime amps — from","أمبير النهار — من","ئەمپێری ڕۆژ — لە"),noteVal("dayFrom","20"));fDayTo=labeled(c,tx("Daytime amps — to","أمبير النهار — إلى","ئەمپێری ڕۆژ — بۆ"),noteVal("dayTo","40"));fNightAmp=labeled(c,tx("Night amps","أمبير الليل","ئەمپێری شەو"),noteVal("nightAmp","10"));fNightHours=labeled(c,tx("Night duration (hours)","مدة الليل (ساعات)","ماوەی شەو (کاتژمێر)"),noteVal("nightHours","5"));fEmergencyAmp=labeled(c,tx("Emergency amps","أمبير الضرورة","ئەمپێری پێویستی"),noteVal("emAmp","50"));fEmergencyDuration=labeled(c,tx("Emergency duration","مدة الضرورة","ماوەی پێویستی"),noteVal("emDur",tx("2 hours","ساعتين","2 کاتژمێر")));fCustomNote=multiField(tx("Optional custom note","ملاحظة إضافية اختيارية","تێبینی زیادەی ئارەزوومەندانە"),customNoteFrom(draft.notes),2);c.addView(fCustomNote,new LinearLayout.LayoutParams(-1,dp(86)));p.addView(c);}
    private void buildPhotoCard(LinearLayout p){LinearLayout c=card();c.addView(tv(tx("Site photos","صور الموقع","وێنەی شوێن"),15,true,NAVY));Button add=button(tx("+ Add photos","+ إضافة صور","+ وێنە زیاد بکە"),2);add.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,PICK_PHOTOS);});c.addView(add,new LinearLayout.LayoutParams(-1,dp(44)));for(int i=0;i<photos.size();i++){String u=photos.get(i);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);CheckBox cb=new CheckBox(this);cb.setChecked(includedPhotos.contains(u));final String uri=u;cb.setOnCheckedChangeListener((b,on)->{if(on)includedPhotos.add(uri);else includedPhotos.remove(uri);});r.addView(cb);r.addView(tv(tx("Site photo ","صورة الموقع ","وێنەی شوێن ")+(i+1),12,false,NAVY),new LinearLayout.LayoutParams(0,-2,1));Button x=button("×",4);final int ix=i;x.setOnClickListener(v->{String rem=photos.remove(ix);includedPhotos.remove(rem);showWizard();});r.addView(x,new LinearLayout.LayoutParams(dp(42),dp(36)));c.addView(r);}p.addView(c);}

    private void navButtons(LinearLayout p,boolean first){addSpace(p,18);LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.HORIZONTAL);Button next=button(step==3?tx("Preview form","معاينة الاستمارة","پێشبینینی فۆرم"):tx("Continue","متابعة","بەردەوام"),1);Button back=button(tx("Back","رجوع","گەڕانەوە"),0);n.addView(next,new LinearLayout.LayoutParams(0,dp(54),1));Space g=new Space(this);n.addView(g,new LinearLayout.LayoutParams(dp(8),1));n.addView(back,new LinearLayout.LayoutParams(0,dp(54),1));next.setOnClickListener(v->{captureStep();if(!validateStep())return;if(step<3){step++;showWizard();}else showPreview();});back.setOnClickListener(v->{captureStep();if(step>0){step--;showWizard();}else showHome();});p.addView(n);}

    private void captureStep(){if(step==0&&fClient!=null){draft.client=fClient.getText().toString().trim();draft.phone=fPhone.getText().toString().trim();draft.location=fLocation.getText().toString().trim();draft.date=fDate.getText().toString().trim();}else if(step==1&&fCapacity!=null){draft.capacity=fCapacity.getText().toString().trim();int s=fSystem.getSelectedItemPosition();draft.system=s==1?"On-Grid":s==2?"Off-Grid":"Hybrid";draft.phase=fPhase.getSelectedItemPosition()==1?"Three Phase":"Single Phase";}else if(step==3&&fOrganizer!=null){draft.organizer=fOrganizer.getText().toString().trim();draft.installation=fInstall.isChecked();draft.transport=fTransport.isChecked();draft.notes=buildNote();}}
    private boolean validateStep(){String err="";if(step==0){if(draft.client.isEmpty())err=tx("Client name is required","اسم العميل مطلوب","ناوی کڕیار پێویستە");else if(draft.phone.isEmpty())err=tx("Phone is required","رقم الهاتف مطلوب","تەلەفۆن پێویستە");else if(draft.location.isEmpty())err=tx("Location is required","الموقع مطلوب","شوێن پێویستە");}else if(step==1&&draft.capacity.isEmpty())err=tx("Capacity is required","السعة مطلوبة","توانا پێویستە");else if(step==2&&items.isEmpty())err=tx("Add at least one material","أضف مادة واحدة على الأقل","لانیکەم یەک ماددە زیاد بکە");else if(step==3&&draft.organizer.isEmpty())err=tx("Organizer is required","منظم الكشف مطلوب","ڕێکخەر پێویستە");if(!err.isEmpty()){Toast.makeText(this,err,Toast.LENGTH_LONG).show();return false;}return true;}

    /* CATALOG */
    private void showCatalog(){clear("catalog");LinearLayout p=pageScroll();title(p,tx("Material catalog","كتالوج المواد","کاتەلۆگی ماددە"),catalog.size()+" "+tx("items","مادة","ماددە"));EditText search=field(tx("Search item name…","ابحث باسم المادة…","بە ناوی ماددە بگەڕێ…"),"");p.addView(search,new LinearLayout.LayoutParams(-1,dp(54)));addSpace(p,10);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout chips=new LinearLayout(this);chips.setOrientation(LinearLayout.HORIZONTAL);hs.addView(chips);p.addView(hs,new LinearLayout.LayoutParams(-1,dp(46)));LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);p.addView(list);String[] filters={"ALL","PANELS","INVERTER","BATTERY","STRUCTURE","ACCESSORY","INSTALL"};for(String f:filters){TextView ch=pill(catLabel(f),f.equals(catalogFilter)?TEAL:Color.WHITE,f.equals(catalogFilter)?Color.WHITE:NAVY);ch.setOnClickListener(v->{catalogFilter=f;showCatalog();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(36));lp.leftMargin=dp(3);lp.rightMargin=dp(3);chips.addView(ch,lp);}Runnable render=()->renderCatalogList(list,search.getText().toString().trim().toLowerCase(Locale.ROOT));search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){render.run();}public void afterTextChanged(Editable e){}});render.run();}
    private String catLabel(String f){if(f.equals("ALL"))return tx("All","الكل","هەموو");if(f.equals("PANELS"))return tx("Panels","ألواح","پانێڵ");if(f.equals("INVERTER"))return tx("Inverters","إنفرترات","ئینڤێرتەر");if(f.equals("BATTERY"))return tx("Batteries","بطاريات","باتری");if(f.equals("STRUCTURE"))return tx("Structures","هياكل","هەیکەل");if(f.equals("ACCESSORY"))return tx("Accessories","ملحقات","پێداویستی");return tx("Installation","تركيب/نقل","دامەزراندن");}
    private String catGroup(Product x){String c=(x.category+" "+x.name).toLowerCase(Locale.ROOT);if(c.contains("panel"))return"PANELS";if(c.contains("inverter"))return"INVERTER";if(c.contains("battery")||c.contains("bms"))return"BATTERY";if(c.contains("structure")||c.contains("rack"))return"STRUCTURE";if(c.contains("install")||c.contains("delivery")||c.contains("transport"))return"INSTALL";return"ACCESSORY";}
    private void renderCatalogList(LinearLayout list,String q){list.removeAllViews();for(Product x:catalog){if(!catalogFilter.equals("ALL")&&!catGroup(x).equals(catalogFilter))continue;if(!q.isEmpty()&&!x.name.toLowerCase(Locale.ROOT).contains(q))continue;LinearLayout c=card();LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);txt.addView(tv(x.name,14,true,NAVY));txt.addView(tv(x.category,10,false,MUTED));r.addView(txt,new LinearLayout.LayoutParams(0,-2,1));TextView add=pill("+",Color.rgb(232,250,246),TEAL_DARK);r.addView(add,new LinearLayout.LayoutParams(dp(40),dp(34)));c.addView(r);c.setOnClickListener(v->{LineItem it=new LineItem();it.name=x.name;it.category=x.category;items.add(it);Toast.makeText(this,tx("Added","تمت الإضافة","زیادکرا"),Toast.LENGTH_SHORT).show();});list.addView(c);addSpace(list,8);}}

    private void showItemPicker(final int replaceIndex){final Dialog d=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(14),dp(14),dp(14));box.setBackgroundColor(Color.WHITE);EditText search=field(tx("Search item name…","ابحث باسم المادة…","بە ناوی ماددە بگەڕێ…"),"");box.addView(search,new LinearLayout.LayoutParams(-1,dp(54)));ListView lv=new ListView(this);box.addView(lv,new LinearLayout.LayoutParams(-1,0,1));final ArrayList<Product> result=new ArrayList<>();final ArrayList<String> names=new ArrayList<>();final ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,names);lv.setAdapter(ad);Runnable r=()->{String q=search.getText().toString().trim().toLowerCase(Locale.ROOT);result.clear();names.clear();for(Product x:catalog)if(q.isEmpty()||x.name.toLowerCase(Locale.ROOT).contains(q)){result.add(x);names.add(x.name);}ad.notifyDataSetChanged();};search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){r.run();}public void afterTextChanged(Editable e){}});lv.setOnItemClickListener((a,v,pos,id)->{Product x=result.get(pos);if(replaceIndex>=0){LineItem old=items.get(replaceIndex);old.name=x.name;old.category=x.category;}else{LineItem it=new LineItem();it.name=x.name;it.category=x.category;items.add(it);}d.dismiss();showWizard();});r.run();d.setContentView(box);Window w=d.getWindow();if(w!=null){w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.92f),(int)(getResources().getDisplayMetrics().heightPixels*.82f));w.setBackgroundDrawableResource(android.R.color.transparent);}d.show();if(w!=null)w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.92f),(int)(getResources().getDisplayMetrics().heightPixels*.82f));}
    private void editItem(final int index,LineItem existing){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(8),dp(18),0);EditText name=field(tx("Item name","اسم المادة","ناوی ماددە"),existing==null?"":existing.name);EditText qty=field(tx("Quantity","الكمية","بڕ"),existing==null?"1":existing.qty);EditText price=field(tx("Unit price (optional)","سعر الوحدة (اختياري)","نرخی یەکە (ئارەزوومەندانە)"),existing==null?"":existing.price);box.addView(name,new LinearLayout.LayoutParams(-1,dp(52)));addSpace(box,8);box.addView(qty,new LinearLayout.LayoutParams(-1,dp(52)));addSpace(box,8);box.addView(price,new LinearLayout.LayoutParams(-1,dp(52)));new AlertDialog.Builder(this).setTitle(existing==null?tx("Custom item","مادة مخصصة","ماددەی تایبەت"):tx("Edit item","تعديل المادة","دەستکاری ماددە")).setView(box).setPositiveButton(tx("Save","حفظ","پاشەکەوت"),(d,w)->{LineItem it=existing==null?new LineItem():existing;it.name=name.getText().toString().trim();it.qty=qty.getText().toString().trim().isEmpty()?"1":qty.getText().toString().trim();it.price=price.getText().toString().trim();if(existing==null)items.add(it);showWizard();}).setNegativeButton(tx("Cancel","إلغاء","هەڵوەشاندنەوە"),null).show();}

    /* SAVED */
    private void showSaved(){clear("saved");LinearLayout p=pageScroll();title(p,tx("Saved forms","الاستمارات المحفوظة","فۆرمە پاشەکەوتکراوەکان"),tx("Search, preview, edit or duplicate.","ابحث أو عاين أو عدل أو انسخ.","بگەڕێ، پێشبینین، دەستکاری یان دووبارە."));EditText search=field(tx("Search client, phone or location…","ابحث بالعميل أو الهاتف أو الموقع…","بە کڕیار، تەلەفۆن یان شوێن بگەڕێ…"),"");p.addView(search,new LinearLayout.LayoutParams(-1,dp(54)));addSpace(p,12);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);p.addView(list);Runnable r=()->renderSaved(list,search.getText().toString().trim().toLowerCase(Locale.ROOT));search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){r.run();}public void afterTextChanged(Editable e){}});r.run();}
    private void renderSaved(LinearLayout list,String q){list.removeAllViews();JSONArray a=savedArray();for(int i=a.length()-1;i>=0;i--){JSONObject o=a.optJSONObject(i);if(o==null)continue;String hay=(o.optString("client")+" "+o.optString("phone")+" "+o.optString("location")+" "+o.optString("date")).toLowerCase(Locale.ROOT);if(!q.isEmpty()&&!hay.contains(q))continue;list.addView(savedCard(o));addSpace(list,10);}}
    private View savedCard(JSONObject o){LinearLayout c=card();LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);txt.addView(tv(o.optString("client",tx("Unnamed","بدون اسم","بێ ناو")),16,true,NAVY));txt.addView(tv(o.optString("phone","")+"  ·  "+o.optString("location",""),11,false,MUTED));txt.addView(tv(o.optString("date","")+"  ·  "+tx("Organizer","المنظم","ڕێکخەر")+": "+o.optString("organizer","—"),10,false,MUTED));head.addView(txt,new LinearLayout.LayoutParams(0,-2,1));head.addView(pill(o.optString("capacity","—"),Color.rgb(232,249,245),TEAL_DARK));c.addView(head);addSpace(c,10);LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.HORIZONTAL);Button preview=button(tx("Preview","معاينة","پێشبینین"),1),edit=button(tx("Edit","تعديل","دەستکاری"),3),dup=button(tx("Duplicate","نسخ","دووبارە"),2),del=button(tx("Delete","حذف","سڕینەوە"),4);a.addView(preview,new LinearLayout.LayoutParams(0,dp(40),1));a.addView(edit,new LinearLayout.LayoutParams(0,dp(40),1));a.addView(dup,new LinearLayout.LayoutParams(0,dp(40),1));a.addView(del,new LinearLayout.LayoutParams(0,dp(40),1));preview.setOnClickListener(v->{loadDraft(o);showPreview();});edit.setOnClickListener(v->{loadDraft(o);step=0;showWizard();});dup.setOnClickListener(v->{loadDraft(o);draft.id="";draft.date=today();step=0;showWizard();});del.setOnClickListener(v->confirmDelete(o.optString("id")));c.addView(a);return c;}
    private void confirmDelete(String id){new AlertDialog.Builder(this).setTitle(tx("Delete form?","حذف الاستمارة؟","فۆرم بسڕدرێتەوە؟")).setMessage(tx("This cannot be undone.","لا يمكن التراجع.","ناتوانرێت پاشگەز ببیتەوە.")).setPositiveButton(tx("Delete","حذف","سڕینەوە"),(d,w)->{JSONArray a=savedArray(),out=new JSONArray();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&!id.equals(o.optString("id")))out.put(o);}prefs.edit().putString("offers",out.toString()).apply();showSaved();}).setNegativeButton(tx("Cancel","إلغاء","هەڵوەشاندنەوە"),null).show();}

    /* SETTINGS */
    private void showSettings(){clear("settings");LinearLayout p=pageScroll();title(p,tx("Settings","الإعدادات","ڕێکخستنەکان"),tx("Company, app and PDF preferences.","إعدادات الشركة والتطبيق وPDF.","ڕێکخستنی کۆمپانیا و ئەپ و PDF."));LinearLayout companyCard=card();final EditText cName=labeled(companyCard,tx("Company name","اسم الشركة","ناوی کۆمپانیا"),company());Button logo=button(tx("Choose PDF logo","اختيار شعار PDF","لۆگۆی PDF هەڵبژێرە"),2);logo.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,PICK_LOGO);});companyCard.addView(logo,new LinearLayout.LayoutParams(-1,dp(46)));p.addView(companyCard);addSpace(p,10);LinearLayout app=card();app.addView(tv(tx("Language","اللغة","زمان"),11,true,MUTED));Spinner language=new Spinner(this);String[] langs={"English","العربية","کوردی"};language.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,langs));language.setSelection("ar".equals(lang())?1:("ku".equals(lang())?2:0));app.addView(language,new LinearLayout.LayoutParams(-1,dp(48)));app.addView(tv(tx("Currency","العملة","دراو"),11,true,MUTED));Spinner cur=new Spinner(this);cur.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"USD","IQD"}));cur.setSelection("IQD".equals(currency())?1:0);app.addView(cur,new LinearLayout.LayoutParams(-1,dp(48)));CheckBox prices=new CheckBox(this);prices.setText(tx("Show prices in PDF","إظهار الأسعار في PDF","نرخ لە PDF پیشان بدە"));prices.setChecked(settingsPrefs.getBoolean("showPrices",true));CheckBox total=new CheckBox(this);total.setText(tx("Show estimated total","إظهار المجموع التقديري","کۆی خەمڵاندراو پیشان بدە"));total.setChecked(settingsPrefs.getBoolean("pdf_show_total",true));CheckBox photoPdf=new CheckBox(this);photoPdf.setText(tx("Include selected site photos","تضمين صور الموقع المحددة","وێنە هەڵبژێردراوەکان ناوخۆ بکە"));photoPdf.setChecked(settingsPrefs.getBoolean("include_photos_pdf",true));app.addView(prices);app.addView(total);app.addView(photoPdf);p.addView(app);addSpace(p,10);Button organizers=button(tx("Manage organizer profiles","إدارة منظمي الكشف","بەڕێوەبردنی ڕێکخەران"),3);organizers.setOnClickListener(v->manageOrganizers());p.addView(organizers,new LinearLayout.LayoutParams(-1,dp(48)));addSpace(p,10);Button save=button(tx("Save settings","حفظ الإعدادات","ڕێکخستنەکان پاشەکەوت بکە"),1);save.setOnClickListener(v->{String L=language.getSelectedItemPosition()==1?"ar":language.getSelectedItemPosition()==2?"ku":"en";settingsPrefs.edit().putString("lang",L).putString("currency",String.valueOf(cur.getSelectedItem())).putString("company_name",cName.getText().toString().trim()).putBoolean("showPrices",prices.isChecked()).putBoolean("pdf_show_total",total.isChecked()).putBoolean("include_photos_pdf",photoPdf.isChecked()).apply();recreate();});p.addView(save,new LinearLayout.LayoutParams(-1,dp(54)));}

    private void chooseOrganizer(){String[] arr=organizerArray();if(arr.length==0){manageOrganizers();return;}new AlertDialog.Builder(this).setTitle(tx("Choose organizer","اختيار منظم الكشف","ڕێکخەر هەڵبژێرە")).setItems(arr,(d,w)->fOrganizer.setText(arr[w])).setPositiveButton(tx("Manage","إدارة","بەڕێوەبردن"),(d,w)->manageOrganizers()).show();}
    private String[] organizerArray(){String raw=settingsPrefs.getString("organizers","");if(raw.trim().isEmpty())return new String[0];String[] x=raw.split("\\n");ArrayList<String> a=new ArrayList<>();for(String s:x)if(!s.trim().isEmpty())a.add(s.trim());return a.toArray(new String[0]);}
    private void manageOrganizers(){EditText e=multiField(tx("One organizer per line","منظم واحد في كل سطر","هەر ڕێکخەر لە هێڵێک"),settingsPrefs.getString("organizers",""),5);new AlertDialog.Builder(this).setTitle(tx("Organizer profiles","منظمو الكشف","ڕێکخەران")).setView(e).setPositiveButton(tx("Save","حفظ","پاشەکەوت"),(d,w)->settingsPrefs.edit().putString("organizers",e.getText().toString()).apply()).setNegativeButton(tx("Cancel","إلغاء","هەڵوەشاندنەوە"),null).show();}

    /* PREVIEW / PDF */
    private void showPreview(){clear("preview");captureStep();LinearLayout p=pageScroll();title(p,tx("Form preview","معاينة الاستمارة","پێشبینینی فۆرم"),tx("Review before saving or sharing the PDF.","راجع البيانات قبل حفظ أو مشاركة PDF.","پێش پاشەکەوت یان هاوبەشکردنی PDF پێداچوونەوە بکە."));p.addView(summaryCard(tx("Client","العميل","کڕیار"),draft.client+"\n"+draft.phone+"\n"+draft.location));addSpace(p,8);p.addView(summaryCard(tx("System","المنظومة","سیستەم"),draft.system+" · "+draft.capacity+" · "+draft.phase));addSpace(p,8);p.addView(summaryCard(tx("Materials","المواد","ماددە"),items.size()+" "+tx("items","مواد","ماددە")+"\n"+tx("Estimated total","المجموع التقديري","کۆی خەمڵاندراو")+": "+currency()+" "+money.format(grandTotal())));addSpace(p,8);p.addView(summaryCard(tx("Load note","ملاحظة التحميل","تێبینی بار"),draft.notes));addSpace(p,16);Button saveForm=button(tx("Save form","حفظ الاستمارة","فۆرم پاشەکەوت بکە"),3);saveForm.setOnClickListener(v->{saveCurrent();Toast.makeText(this,tx("Saved","تم الحفظ","پاشەکەوت کرا"),Toast.LENGTH_SHORT).show();});p.addView(saveForm,new LinearLayout.LayoutParams(-1,dp(48)));addSpace(p,8);LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button share=button(tx("Share PDF","مشاركة PDF","PDF هاوبەش بکە"),1),savePdf=button(tx("Save PDF","حفظ PDF","PDF پاشەکەوت بکە"),2);actions.addView(share,new LinearLayout.LayoutParams(0,dp(52),1));Space g=new Space(this);actions.addView(g,new LinearLayout.LayoutParams(dp(8),1));actions.addView(savePdf,new LinearLayout.LayoutParams(0,dp(52),1));share.setOnClickListener(v->{saveCurrent();File f=makePdf();if(f!=null)sharePdf(f);});savePdf.setOnClickListener(v->{saveCurrent();pendingPdf=makePdf();if(pendingPdf!=null){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,pendingPdf.getName());startActivityForResult(i,SAVE_PDF);}});p.addView(actions);addSpace(p,8);Button edit=button(tx("Back to edit","العودة للتعديل","گەڕانەوە بۆ دەستکاری"),0);edit.setOnClickListener(v->{step=3;showWizard();});p.addView(edit,new LinearLayout.LayoutParams(-1,dp(50)));}
    private View summaryCard(String title,String value){LinearLayout c=card();c.addView(tv(title,12,true,TEAL_DARK));TextView v=tv(value,14,false,NAVY);v.setPadding(0,dp(7),0,0);c.addView(v);return c;}

    private File makePdf(){try{File dir=getExternalFilesDir(android.os.Environment.DIRECTORY_DOCUMENTS);if(dir==null)return null;File out=new File(dir,fileName());PdfDocument doc=new PdfDocument();PdfWriter w=new PdfWriter(doc);w.newPage(true);w.section(tx("Client","العميل","کڕیار"),120);w.row(tx("Client","العميل","کڕیار"),draft.client);w.row(tx("Phone","الهاتف","تەلەفۆن"),draft.phone);w.row(tx("Location","الموقع","شوێن"),draft.location);w.row(tx("Date","التاريخ","بەروار"),draft.date);w.section(tx("System","المنظومة","سیستەم"),100);w.row(tx("Type","النوع","جۆر"),draft.system);w.row(tx("Capacity","السعة","توانا"),draft.capacity);w.row(tx("Phase","الطور","فاز"),draft.phase);w.section(tx("Materials","المواد","ماددە"),Math.min(240,50+items.size()*28));w.itemsHeader();for(LineItem it:items)w.item(it);if(settingsPrefs.getBoolean("pdf_show_total",true))w.total(grandTotal());w.section(tx("Organizer details","بيانات المنظم","زانیاری ڕێکخەر"),100);w.row(tx("Installation","التركيب","دامەزراندن"),draft.installation?tx("Included","مشمول","ناوخۆیە"):tx("Not included","غير مشمول","ناوخۆ نییە"));w.row(tx("Transport","النقل","گواستنەوە"),draft.transport?tx("Included","مشمول","ناوخۆیە"):tx("Not included","غير مشمول","ناوخۆ نییە"));w.row(tx("Organizer","منظم الكشف","ڕێکخەر"),draft.organizer);w.section(tx("Load / notes","التحميل / الملاحظات","بار / تێبینی"),150);w.paragraph(draft.notes);w.finish();if(settingsPrefs.getBoolean("include_photos_pdf",true))for(String u:photos)if(includedPhotos.contains(u))appendPhoto(doc,Uri.parse(u));FileOutputStream fos=new FileOutputStream(out);doc.writeTo(fos);fos.close();doc.close();return out;}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();return null;}}
    private class PdfWriter{PdfDocument doc;PdfDocument.Page page;Canvas c;Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);int n=0,y;PdfWriter(PdfDocument d){doc=d;}void newPage(boolean full){if(page!=null)finishPage();page=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,++n).create());c=page.getCanvas();c.drawColor(Color.WHITE);if(full)header();else{draw(tx("Form continued","تكملة الاستمارة","بەردەوامی فۆرم"),rtl()?555:40,45,17,true,NAVY);p.setColor(TEAL);c.drawRect(40,60,555,63,p);y=78;}}void header(){Bitmap logo=loadLogo();if(logo!=null){float s=Math.min(92f/logo.getWidth(),55f/logo.getHeight());int w=(int)(logo.getWidth()*s),h=(int)(logo.getHeight()*s);c.drawBitmap(logo,null,new Rect(rtl()?555-w:40,24,rtl()?555:40+w,24+h),null);}draw(company().toUpperCase(Locale.ROOT),rtl()?440:145,42,21,true,NAVY);draw(tx("Organizer Preliminary Solar Form","استمارة أولية للمنظومة الشمسية","فۆرمی سەرەتایی سیستەمی خۆرەوی"),rtl()?440:145,66,11,true,TEAL_DARK);p.setColor(TEAL);c.drawRect(40,89,555,92,p);y=108;}void section(String s,int need){if(y>120&&790-y<Math.max(75,need)){newPage(false);}p.setColor(NAVY);c.drawRoundRect(40,y,555,y+24,8,8,p);draw(s,rtl()?545:50,y+16,10,true,Color.WHITE);y+=32;}void ensure(int h){if(y+h>790)newPage(false);}void row(String k,String v){ensure(27);draw(k,rtl()?545:45,y+15,9,true,MUTED);draw(v,rtl()?360:180,y+15,10,false,NAVY);p.setColor(BORDER);c.drawLine(40,y+23,555,y+23,p);y+=27;}void itemsHeader(){ensure(24);draw(tx("ITEM","المادة","ماددە"),rtl()?545:45,y+14,8,true,TEAL_DARK);draw(tx("QTY","الكمية","بڕ"),rtl()?205:355,y+14,8,true,TEAL_DARK);if(settingsPrefs.getBoolean("showPrices",true)){draw(tx("PRICE","السعر","نرخ"),rtl()?145:425,y+14,8,true,TEAL_DARK);draw(tx("TOTAL","المجموع","کۆ"),rtl()?75:500,y+14,8,true,TEAL_DARK);}y+=22;}void item(LineItem it){ensure(27);draw(trim(it.name,46),rtl()?545:45,y+15,9,false,NAVY);draw(it.qty,rtl()?205:355,y+15,9,false,NAVY);if(settingsPrefs.getBoolean("showPrices",true)){draw(it.price,rtl()?145:425,y+15,9,false,NAVY);draw(money.format(lineTotal(it)),rtl()?75:500,y+15,9,false,NAVY);}p.setColor(BORDER);c.drawLine(40,y+23,555,y+23,p);y+=27;}void total(BigDecimal x){ensure(30);draw(tx("Estimated total","المجموع التقديري","کۆی خەمڵاندراو")+": "+currency()+" "+money.format(x),rtl()?545:45,y+18,12,true,TEAL_DARK);y+=30;}void paragraph(String s){for(String line:wrap(s,rtl()?70:82)){ensure(20);draw(line,rtl()?545:45,y+14,9,false,NAVY);y+=19;}}void finish(){finishPage();}void finishPage(){if(page==null)return;draw(company()+" · Organizer Form",rtl()?555:40,820,8,false,TEAL_DARK);doc.finishPage(page);page=null;}void draw(String s,float x,float yy,float size,boolean bold,int color){p.setColor(color);p.setTextSize(size);p.setTypeface(bold?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);p.setTextAlign(rtl()?Paint.Align.RIGHT:Paint.Align.LEFT);c.drawText(s==null?"":s,x,yy,p);}String trim(String s,int m){if(s==null)return"";return s.length()>m?s.substring(0,m-1)+"…":s;}}

    private ArrayList<String> wrap(String s,int max){ArrayList<String> out=new ArrayList<>();if(s==null||s.trim().isEmpty()){out.add("—");return out;}for(String raw:s.split("\\n")){String line="";for(String word:raw.trim().split("\\s+")){if((line+" "+word).trim().length()>max){out.add(line);line=word;}else line=(line+" "+word).trim();}if(!line.isEmpty())out.add(line);}return out;}
    private void appendPhoto(PdfDocument doc,Uri u){try{InputStream in=getContentResolver().openInputStream(u);Bitmap b=BitmapFactory.decodeStream(in);if(in!=null)in.close();if(b==null)return;PdfDocument.Page pg=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,doc.getPages().size()+1).create());Canvas c=pg.getCanvas();c.drawColor(Color.WHITE);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(NAVY);p.setTextSize(18);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText(tx("Site photo","صورة الموقع","وێنەی شوێن"),40,50,p);float scale=Math.min(515f/b.getWidth(),730f/b.getHeight());int w=(int)(b.getWidth()*scale),h=(int)(b.getHeight()*scale);int left=(595-w)/2;c.drawBitmap(b,null,new Rect(left,75,left+w,75+h),null);doc.finishPage(pg);b.recycle();}catch(Exception ignored){}}
    private void sharePdf(File f){Uri u=new Uri.Builder().scheme("content").authority(getPackageName()+".provider").appendPath(f.getName()).build();Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/pdf");i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,tx("Share PDF","مشاركة PDF","PDF هاوبەش بکە")));}

    /* STORAGE / MIGRATION */
    private void resetDraft(){draft=new Draft();draft.date=today();draft.installation=settingsPrefs.getBoolean("installation",true);draft.transport=settingsPrefs.getBoolean("transport",false);items.clear();photos.clear();includedPhotos.clear();}
    private String today(){return new SimpleDateFormat("yyyy/MM/dd",Locale.US).format(new Date());}
    private JSONArray savedArray(){try{return new JSONArray(prefs.getString("offers","[]"));}catch(Exception e){return new JSONArray();}}
    private void saveCurrent(){try{if(draft.id.isEmpty())draft.id=String.valueOf(System.currentTimeMillis());JSONObject o=toJson();JSONArray a=savedArray(),out=new JSONArray();boolean replaced=false;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null&&draft.id.equals(x.optString("id"))){out.put(o);replaced=true;}else if(x!=null)out.put(x);}if(!replaced)out.put(o);prefs.edit().putString("offers",out.toString()).apply();}catch(Exception ignored){}}
    private JSONObject toJson()throws Exception{JSONObject o=new JSONObject();o.put("id",draft.id);o.put("client",draft.client);o.put("phone",draft.phone);o.put("location",draft.location);o.put("date",draft.date);o.put("system",draft.system);o.put("capacity",draft.capacity);o.put("phase",draft.phase);o.put("organizer",draft.organizer);o.put("notes",draft.notes);o.put("installation",draft.installation);o.put("transport",draft.transport);JSONArray its=new JSONArray();for(LineItem it:items){JSONObject x=new JSONObject();x.put("category",it.category);x.put("name",it.name);x.put("spec","");x.put("qty",it.qty);x.put("price",it.price);its.put(x);}o.put("items",its);JSONArray ph=new JSONArray();for(String s:photos)ph.put(s);o.put("photos",ph);return o;}
    private void loadDraft(JSONObject o){resetDraft();draft.id=o.optString("id","");draft.client=o.optString("client","");draft.phone=o.optString("phone","");draft.location=o.optString("location","");draft.date=o.optString("date",today());draft.system=o.optString("system","Hybrid");draft.capacity=o.optString("capacity","");draft.phase=o.optString("phase","Single Phase");draft.organizer=o.optString("organizer","");draft.notes=o.optString("notes","");draft.installation=o.optBoolean("installation",true);draft.transport=o.optBoolean("transport",false);JSONArray its=o.optJSONArray("items");if(its!=null)for(int i=0;i<its.length();i++){JSONObject x=its.optJSONObject(i);if(x==null)continue;LineItem it=new LineItem();it.category=x.optString("category","");it.name=x.optString("name","");it.qty=x.optString("qty","1");it.price=x.optString("price","");items.add(it);}JSONArray ph=o.optJSONArray("photos");if(ph!=null)for(int i=0;i<ph.length();i++){String s=ph.optString(i,"");if(!s.isEmpty()){photos.add(s);includedPhotos.add(s);}}}
    private BigDecimal n(String s,BigDecimal d){try{return new BigDecimal(s==null||s.trim().isEmpty()?d.toPlainString():s.replace(",","").replace("$","").trim());}catch(Exception e){return d;}}
    private BigDecimal lineTotal(LineItem i){return n(i.qty,BigDecimal.ONE).multiply(n(i.price,BigDecimal.ZERO));}
    private BigDecimal grandTotal(){BigDecimal x=BigDecimal.ZERO;for(LineItem i:items)x=x.add(lineTotal(i));return x;}

    private void loadCatalog(){catalog.clear();for(int part=1;part<=6;part++){try{BufferedReader br=new BufferedReader(new InputStreamReader(getAssets().open("catalog_v4_"+part+".tsv")));String line;while((line=br.readLine())!=null){String[] s=line.split("\\t",-1);if(s.length>=2&&!s[1].trim().isEmpty())catalog.add(new Product(s[0].trim(),s[1].trim()));}br.close();}catch(Exception ignored){}}}

    private String buildNote(){String cap=draft.capacity.replace("kW","").replace("كيلو واط","").trim();String sys=draft.system;String d1=fDayFrom==null?"":fDayFrom.getText().toString().trim(),d2=fDayTo==null?"":fDayTo.getText().toString().trim(),na=fNightAmp==null?"":fNightAmp.getText().toString().trim(),nh=fNightHours==null?"":fNightHours.getText().toString().trim(),ea=fEmergencyAmp==null?"":fEmergencyAmp.getText().toString().trim(),ed=fEmergencyDuration==null?"":fEmergencyDuration.getText().toString().trim(),custom=fCustomNote==null?"":fCustomNote.getText().toString().trim();String base=tx("Solar system with capacity "+cap+" kW, type "+sys+", supports:\n- Daytime from "+d1+" to "+d2+" A\n- Night "+na+" A for "+nh+" hours\n- Emergency "+ea+" A for "+ed,"منظومة شمسية بقدرة "+cap+" كيلو واط نوع "+systemArabic(sys)+" يتحمل كالآتي:\n- بالنهار من "+d1+" الى "+d2+" امبير\n- بالليل "+na+" امبير لمدة "+nh+" ساعات\n- وفي حالات الضرورة يتحمل "+ea+" امبير لمدة "+ed,"سیستەمی خۆرەوی بە توانای "+cap+" kW جۆری "+sys+" بار هەڵدەگرێت:\n- لە ڕۆژدا "+d1+" تا "+d2+" ئەمپێر\n- لە شەودا "+na+" ئەمپێر بۆ "+nh+" کاتژمێر\n- لە پێویستیدا "+ea+" ئەمپێر بۆ "+ed);if(!custom.isEmpty())base+="\n"+custom;return base;}
    private String systemArabic(String s){if(s.equals("Hybrid"))return"هجين";if(s.equals("On-Grid"))return"أون كريد";if(s.equals("Off-Grid"))return"أوف كريد";return s;}
    private String noteVal(String key,String def){String s=draft.notes;if(s==null)return def;try{if(key.equals("dayFrom")){int x=s.indexOf("بالنهار من ");if(x>=0){String q=s.substring(x+11);return q.split(" ")[0];}}if(key.equals("dayTo")){int x=s.indexOf(" الى ");if(x>=0){String q=s.substring(x+5);return q.split(" ")[0];}}if(key.equals("nightAmp")){int x=s.indexOf("بالليل ");if(x>=0){String q=s.substring(x+7);return q.split(" ")[0];}}if(key.equals("nightHours")){int x=s.indexOf("لمدة ");if(x>=0){String q=s.substring(x+5);return q.split(" ")[0];}}if(key.equals("emAmp")){int x=s.indexOf("يتحمل ",s.indexOf("الضرورة"));if(x>=0){String q=s.substring(x+6);return q.split(" ")[0];}}}catch(Exception ignored){}return def;}
    private String customNoteFrom(String s){if(s==null)return"";String[] lines=s.split("\\n");if(lines.length<=4)return"";StringBuilder b=new StringBuilder();for(int i=4;i<lines.length;i++){if(b.length()>0)b.append("\n");b.append(lines[i]);}return b.toString();}

    private String fileName(){String c=draft.client.replaceAll("[^A-Za-z0-9\\u0600-\\u06FF_-]+","_");if(c.isEmpty())c="Client";String cap=draft.capacity.replaceAll("[^A-Za-z0-9]+","");return c+"_"+(cap.isEmpty()?"Solar":cap)+"_"+draft.date.replace("/","-")+".pdf";}
    private void installDefaultLogo(){if(settingsPrefs.getString("logo_uri","").length()>0)return;try{InputStream in=getAssets().open("igp_default_logo.b64");ByteArrayOutputStream t=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))>0)t.write(b,0,n);in.close();byte[] img=android.util.Base64.decode(t.toByteArray(),android.util.Base64.DEFAULT);File f=new File(getFilesDir(),"igp_default_company_logo.jpg");FileOutputStream out=new FileOutputStream(f);out.write(img);out.close();settingsPrefs.edit().putString("logo_uri",Uri.fromFile(f).toString()).apply();}catch(Exception ignored){}}
    private Bitmap loadLogo(){String s=settingsPrefs.getString("logo_uri","");if(s.isEmpty())return null;try{InputStream in=getContentResolver().openInputStream(Uri.parse(s));Bitmap b=BitmapFactory.decodeStream(in);if(in!=null)in.close();return b;}catch(Exception e){return null;}}

    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null)return;try{if(req==PICK_PHOTOS){ClipData clip=data.getClipData();if(clip!=null){for(int i=0;i<clip.getItemCount();i++){Uri u=clip.getItemAt(i).getUri();getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);String s=u.toString();if(!photos.contains(s)){photos.add(s);includedPhotos.add(s);}}}else if(data.getData()!=null){Uri u=data.getData();getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);String s=u.toString();if(!photos.contains(s)){photos.add(s);includedPhotos.add(s);}}showWizard();}else if(req==PICK_LOGO&&data.getData()!=null){Uri u=data.getData();getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);settingsPrefs.edit().putString("logo_uri",u.toString()).apply();Toast.makeText(this,tx("Logo saved","تم حفظ الشعار","لۆگۆ پاشەکەوت کرا"),Toast.LENGTH_SHORT).show();}else if(req==SAVE_PDF&&data.getData()!=null&&pendingPdf!=null){InputStream in=new FileInputStream(pendingPdf);OutputStream out=getContentResolver().openOutputStream(data.getData());byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);in.close();if(out!=null)out.close();Toast.makeText(this,tx("PDF saved","تم حفظ PDF","PDF پاشەکەوت کرا"),Toast.LENGTH_SHORT).show();}}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}

    @Override public void onBackPressed(){if(screen.equals("preview")){step=3;showWizard();return;}if(screen.equals("new")){captureStep();if(step>0){step--;showWizard();}else showHome();return;}if(!screen.equals("home")){showHome();return;}showHome();}
}
