package com.infinitygreenpower.solarform;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.pdf.PdfDocument;import android.net.Uri;import android.view.*;import android.widget.*;import java.io.*;import java.lang.reflect.*;import java.math.BigDecimal;import java.text.DecimalFormat;import java.util.*;

public class OrganizerRebuildV62Activity extends OrganizerRebuildV61Activity{
 private final Handler h=new Handler(Looper.getMainLooper()); private ViewTreeObserver.OnGlobalLayoutListener gl; private File pending; private static final int SAVE62=6203; private final DecimalFormat fmt=new DecimalFormat("#,##0.##");
 @Override public void onCreate(Bundle b){super.onCreate(b);View r=findViewById(android.R.id.content);if(r!=null){gl=()->{h.removeCallbacks(polish);h.postDelayed(polish,40);};r.getViewTreeObserver().addOnGlobalLayoutListener(gl);}h.postDelayed(polish,70);}
 @Override protected void onDestroy(){View r=findViewById(android.R.id.content);if(r!=null&&gl!=null&&r.getViewTreeObserver().isAlive())r.getViewTreeObserver().removeOnGlobalLayoutListener(gl);h.removeCallbacks(polish);super.onDestroy();}
 private int d(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private String lang(){return getSharedPreferences("offer_studio_settings",MODE_PRIVATE).getString("lang","ar");} private boolean rtl(){return!"en".equals(lang());} private String t(String e,String a,String k){return"ar".equals(lang())?a:("ku".equals(lang())?k:e);} private boolean eq(String s,String e,String a,String k){return s.equals(e)||s.equals(a)||s.equals(k);}
 private final Runnable polish=()->{View r=findViewById(android.R.id.content);if(r!=null)walk(r);};
 private void walk(View v){if(v instanceof Button)small((Button)v);if(v instanceof CheckBox)smallCheck((CheckBox)v);if(v instanceof LinearLayout&&serviceCard((ViewGroup)v)){v.setVisibility(View.GONE);return;}if(v instanceof Button){Button b=(Button)v;String s=String.valueOf(b.getText()).trim();if(eq(s,"Share PDF","مشاركة PDF","PDF هاوبەش بکە"))b.setOnClickListener(x->{File f=pdf();if(f!=null)share(f);});else if(eq(s,"Save PDF","حفظ PDF","PDF پاشەکەوت بکە"))b.setOnClickListener(x->{pending=pdf();if(pending!=null){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,pending.getName());startActivityForResult(i,SAVE62);}});}if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)walk(g.getChildAt(i));}}
 private void small(Button b){b.setTextSize(10);b.setPadding(d(6),0,d(6),0);b.setMinHeight(0);b.setMinimumHeight(0);ViewGroup.LayoutParams q=b.getLayoutParams();if(q instanceof LinearLayout.LayoutParams){LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)q;if(p.height>0&&p.height>d(34))p.height=d(34);p.leftMargin=Math.min(p.leftMargin,d(2));p.rightMargin=Math.min(p.rightMargin,d(2));p.topMargin=Math.min(p.topMargin,d(2));p.bottomMargin=Math.min(p.bottomMargin,d(2));b.setLayoutParams(p);}}
 private void smallCheck(CheckBox c){c.setTextSize(10);c.setScaleX(.76f);c.setScaleY(.76f);c.setPadding(0,0,0,0);c.setMinHeight(0);c.setMinimumHeight(0);}
 private boolean serviceCard(ViewGroup g){boolean title=false,svc=false;for(int i=0;i<g.getChildCount();i++){View v=g.getChildAt(i);if(v instanceof TextView){String s=String.valueOf(((TextView)v).getText()).trim();if(eq(s,"Included services","الخدمات المشمولة","خزمەتگوزارییەکان"))title=true;if(eq(s,"Installation included","التركيب مشمول","دامەزراندن ناوخۆیە")||eq(s,"Transport included","النقل مشمول","گواستنەوە ناوخۆیە"))svc=true;}}return title&&svc;}
 @SuppressWarnings("unchecked") private ArrayList<Object> items(){try{Field f=OrganizerRebuildActivity.class.getDeclaredField("items");f.setAccessible(true);return(ArrayList<Object>)f.get(this);}catch(Exception e){return new ArrayList<>();}} private Object draft(){try{Field f=OrganizerRebuildActivity.class.getDeclaredField("draft");f.setAccessible(true);return f.get(this);}catch(Exception e){return null;}} private String f(Object o,String n){try{Field x=o.getClass().getDeclaredField(n);x.setAccessible(true);Object v=x.get(o);return v==null?"":String.valueOf(v);}catch(Exception e){return"";}} private BigDecimal num(String s){try{return new BigDecimal(s==null||s.trim().isEmpty()?"0":s.replace(",","").replace("$","").trim());}catch(Exception e){return BigDecimal.ZERO;}} private BigDecimal total(Object o){BigDecimal q=num(f(o,"qty"));if(q.signum()==0)q=BigDecimal.ONE;return q.multiply(num(f(o,"price")));} private BigDecimal grand(){BigDecimal x=BigDecimal.ZERO;for(Object o:items())x=x.add(total(o));return x;}
 private File pdf(){Object dft=draft();if(dft==null)return null;try{File dir=getExternalFilesDir(android.os.Environment.DIRECTORY_DOCUMENTS);String cl=f(dft,"client").replaceAll("[^A-Za-z0-9\\u0600-\\u06FF_-]+","_");if(cl.isEmpty())cl="Client";File out=new File(dir,cl+"_"+f(dft,"date").replace("/","-")+".pdf");PdfDocument doc=new PdfDocument();PdfDocument.Page pg=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=pg.getCanvas();Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);c.drawColor(Color.WHITE);int y=46;draw(c,p,getSharedPreferences("offer_studio_settings",MODE_PRIVATE).getString("company_name","Infinity Green Power"),40,y,20,true);y+=34;y=section(c,p,t("Client","العميل","کڕیار"),y);y=row(c,p,t("Client","العميل","کڕیار"),f(dft,"client"),y);y=row(c,p,t("Phone","الهاتف","تەلەفۆن"),f(dft,"phone"),y);y=row(c,p,t("Location","الموقع","شوێن"),f(dft,"location"),y);y=row(c,p,t("Date","التاريخ","بەروار"),f(dft,"date"),y);y=section(c,p,t("System","المنظومة","سیستەم"),y);y=row(c,p,t("Type","النوع","جۆر"),f(dft,"system"),y);y=row(c,p,t("Capacity","السعة","توانا"),f(dft,"capacity"),y);y=row(c,p,t("Phase","الطور","فاز"),f(dft,"phase"),y);y=section(c,p,t("Materials","المواد","ماددە"),y);for(Object it:items()){String line=f(it,"name")+"   × "+f(it,"qty");if(getSharedPreferences("offer_studio_settings",MODE_PRIVATE).getBoolean("showPrices",true))line+="   "+f(it,"price");draw(c,p,line,40,y,9,false);y+=22;}if(getSharedPreferences("offer_studio_settings",MODE_PRIVATE).getBoolean("pdf_show_total",true)){draw(c,p,t("Estimated total","المجموع التقديري","کۆی خەمڵاندراو")+": "+getSharedPreferences("offer_studio_settings",MODE_PRIVATE).getString("currency","USD")+" "+fmt.format(grand()),40,y,11,true);y+=28;}y=section(c,p,t("Organizer","منظم الكشف","ڕێکخەر"),y);y=row(c,p,t("Organizer","منظم الكشف","ڕێکخەر"),f(dft,"organizer"),y);y=section(c,p,t("Load / notes","التحميل / الملاحظات","بار / تێبینی"),y);for(String line:wrap(f(dft,"notes"),72)){draw(c,p,line,40,y,9,false);y+=18;}doc.finishPage(pg);FileOutputStream os=new FileOutputStream(out);doc.writeTo(os);os.close();doc.close();return out;}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();return null;}}
 private int section(Canvas c,Paint p,String s,int y){p.setColor(Color.rgb(19,50,76));c.drawRoundRect(40,y,555,y+23,7,7,p);p.setColor(Color.WHITE);draw(c,p,s,50,y+16,10,true);return y+31;} private int row(Canvas c,Paint p,String k,String v,int y){draw(c,p,k,45,y+15,9,true);draw(c,p,v,180,y+15,10,false);p.setColor(Color.rgb(224,230,236));c.drawLine(40,y+22,555,y+22,p);return y+26;} private void draw(Canvas c,Paint p,String s,float x,float y,float z,boolean b){p.setColor(Color.rgb(19,50,76));p.setTextSize(z);p.setTypeface(b?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);p.setTextAlign(Paint.Align.LEFT);c.drawText(s==null?"":s,x,y,p);} private ArrayList<String> wrap(String s,int max){ArrayList<String>o=new ArrayList<>();for(String raw:(s==null?"":s).split("\\n")){String q="";for(String w:raw.split("\\s+")){if((q+" "+w).trim().length()>max){if(!q.isEmpty())o.add(q);q=w;}else q=(q+" "+w).trim();}if(!q.isEmpty())o.add(q);}return o;}
 private void share(File f){Uri u=new Uri.Builder().scheme("content").authority(getPackageName()+".provider").appendPath(f.getName()).build();Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/pdf");i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,t("Share PDF","مشاركة PDF","PDF هاوبەش بکە")));}
 @Override protected void onActivityResult(int req,int res,Intent data){if(req==SAVE62){if(res==RESULT_OK&&data!=null&&data.getData()!=null&&pending!=null)try{InputStream in=new FileInputStream(pending);OutputStream out=getContentResolver().openOutputStream(data.getData());byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);in.close();if(out!=null)out.close();}catch(Exception ignored){}return;}super.onActivityResult(req,res,data);}
}
