package com.infinitygreenpower.solarform;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class ProfessionalMainActivity extends Activity {
    private static final int PICK_IMAGES = 9001;
    private final int NAVY=Color.rgb(15,53,91), GREEN=Color.rgb(42,151,88), BG=Color.rgb(244,247,251), TEXT=Color.rgb(26,39,52), MUTED=Color.rgb(101,119,137), BORDER=Color.rgb(218,227,236);
    private LinearLayout root, itemsBox, photosBox;
    private EditText clientName, phone, location, date, sizeKw, notes, organizer;
    private Spinner systemType, phase;
    private CheckBox installation, transport;
    private final ArrayList<Item> items=new ArrayList<>();
    private final ArrayList<String> photos=new ArrayList<>();
    private final ArrayList<Product> catalog=new ArrayList<>();

    static class Product { String type,model,capacity; Product(String t,String m,String c){type=t;model=m;capacity=c;} String display(){return type+" — "+model+(capacity.isEmpty()?"":" — "+capacity);} }
    static class Item { String type,model,capacity,qty,price; Item(String t,String m,String c,String q,String p){type=t;model=m;capacity=c;qty=q;price=p;} }

    @Override public void onCreate(Bundle b){ super.onCreate(b); getWindow().setStatusBarColor(NAVY); seedCatalog(); buildUi(); loadDraft(); }

    private void seedCatalog(){
        addP("الألواح الشمسية","Huasun HJT","610 W"); addP("الألواح الشمسية","Huasun HJT","615 W"); addP("الألواح الشمسية","Huasun HJT","620 W");
        addP("الإنفرتر","Roypow RS6500 Hybrid","6.5 kW"); addP("الإنفرتر","Deye Hybrid - Single Phase","6 kW"); addP("الإنفرتر","Deye Hybrid - Single Phase","8 kW"); addP("الإنفرتر","Deye Hybrid - Single Phase","12 kW"); addP("الإنفرتر","Deye Hybrid - Single Phase","16 kW"); addP("الإنفرتر","Deye Hybrid - Three Phase","12 kW"); addP("الإنفرتر","Deye Hybrid - Three Phase","16 kW"); addP("الإنفرتر","Deye On-Grid Inverter","حدد السعة");
        addP("البطارية","Roypow LiFePO4","16 kWh"); addP("البطارية","Deye High Voltage Battery Rack","HV"); addP("BMS","Deye High Voltage BMS","HV");
        addP("القواعد","هيكل تثبيت ألواح شمسية","حسب الموقع"); addP("كيبل DC","Solar DC Cable","حدد القياس"); addP("كيبل AC","AC Cable","حدد القياس"); addP("كيبل البطاريات","Battery Cable","حدد القياس"); addP("صندوق حماية / تجميع","Protection Box / Combiner",""); addP("قاطع DC","DC Breaker",""); addP("قاطع AC","AC Breaker",""); addP("حماية DC","DC SPD",""); addP("حماية AC","AC SPD",""); addP("موصلات","MC4 Connectors",""); addP("لوحة توزيع","Distribution Board (DB)",""); addP("تأريض","Earthing System",""); addP("قضيب أرضي","Earth Rod",""); addP("مسار كيبل","Cable Tray / PVC",""); addP("تركيب","أجور تركيب","");
    }
    private void addP(String t,String m,String c){catalog.add(new Product(t,m,c));}

    private void buildUi(){
        ScrollView scroll=new ScrollView(this); scroll.setFillViewport(true); scroll.setBackgroundColor(BG);
        root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); root.setPadding(dp(16),dp(16),dp(16),dp(28)); scroll.addView(root);
        root.addView(headerCard());
        LinearLayout quick=card(); quick.addView(title("إنشاء عرض سعر جديد",18)); quick.addView(sub("املأ البيانات، اختر المواد، أرفق صور الموقع ثم أنشئ ملف PDF.")); root.addView(quick);

        LinearLayout c1=section("01","معلومات العميل","بيانات العميل وموقع المشروع");
        clientName=input(c1,"اسم العميل","اكتب اسم العميل",false); phone=input(c1,"رقم الهاتف","07xx xxx xxxx",false); location=input(c1,"الموقع","المدينة / المنطقة",false); date=input(c1,"التاريخ","YYYY/MM/DD",false); date.setText(new SimpleDateFormat("yyyy/MM/dd",Locale.US).format(new Date()));

        LinearLayout c2=section("02","معلومات المنظومة","حدد نوع النظام والسعة المطلوبة");
        systemType=spinner(c2,"نوع المنظومة",new String[]{"اختر نوع المنظومة","هجين","أون كريد","أوف كريد"}); sizeKw=input(c2,"السعة المطلوبة (kW)","مثال: 8",false); phase=spinner(c2,"الطور",new String[]{"اختر الطور","أحادي","ثلاثي"});

        LinearLayout c3=section("03","المواد المطلوبة","كتالوج سريع مع إمكانية إضافة مواد مخصصة");
        LinearLayout addRow=new LinearLayout(this); addRow.setOrientation(LinearLayout.HORIZONTAL); addRow.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); Button catalogBtn=actionButton("اختيار من الكتالوج",NAVY,Color.WHITE); Button customBtn=actionButton("مادة مخصصة",Color.WHITE,NAVY); ((GradientDrawable)customBtn.getBackground()).setStroke(dp(1),BORDER); addRow.addView(catalogBtn); addRow.addView(customBtn); c3.addView(addRow);
        itemsBox=new LinearLayout(this); itemsBox.setOrientation(LinearLayout.VERTICAL); LinearLayout.LayoutParams ib=new LinearLayout.LayoutParams(-1,-2); ib.topMargin=dp(10); itemsBox.setLayoutParams(ib); c3.addView(itemsBox); renderItems(); catalogBtn.setOnClickListener(v->showCatalog()); customBtn.setOnClickListener(v->editItem(new Item("","","","1",""),-1,true));

        LinearLayout c4=section("04","صور الموقع / المنظومة","أضف صور الألواح أو اللوحة أو مكان الإنفرتر والبطاريات");
        Button photoBtn=primary("إرفاق صور من الهاتف",NAVY); LinearLayout.LayoutParams pb=(LinearLayout.LayoutParams)photoBtn.getLayoutParams(); pb.height=dp(46); photoBtn.setLayoutParams(pb); c4.addView(photoBtn); photosBox=new LinearLayout(this); photosBox.setOrientation(LinearLayout.VERTICAL); LinearLayout.LayoutParams phlp=new LinearLayout.LayoutParams(-1,-2); phlp.topMargin=dp(10); photosBox.setLayoutParams(phlp); c4.addView(photosBox); renderPhotos(); photoBtn.setOnClickListener(v->pickImages());

        LinearLayout c5=section("05","معلومات إضافية","خيارات التركيب والنقل والملاحظات");
        LinearLayout checks=new LinearLayout(this); checks.setOrientation(LinearLayout.HORIZONTAL); checks.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); installation=new CheckBox(this); installation.setText("يشمل التركيب"); transport=new CheckBox(this); transport.setText("يشمل النقل"); checks.addView(installation); checks.addView(transport); c5.addView(checks); notes=input(c5,"ملاحظات","أي ملاحظات إضافية",true); organizer=input(c5,"اسم منظم الكشف","اسم الشخص المسؤول عن المعاينة",false);

        Button pdf=primary("إنشاء PDF ومشاركته",GREEN); LinearLayout.LayoutParams pp=(LinearLayout.LayoutParams)pdf.getLayoutParams(); pp.topMargin=dp(16); pdf.setLayoutParams(pp); root.addView(pdf);
        LinearLayout bottom=new LinearLayout(this); bottom.setOrientation(LinearLayout.HORIZONTAL); bottom.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); LinearLayout.LayoutParams bl=new LinearLayout.LayoutParams(-1,-2); bl.topMargin=dp(10); bottom.setLayoutParams(bl); Button save=actionButton("حفظ المسودة",Color.WHITE,NAVY); Button clear=actionButton("نموذج جديد",Color.WHITE,NAVY); ((GradientDrawable)save.getBackground()).setStroke(dp(1),BORDER); ((GradientDrawable)clear.getBackground()).setStroke(dp(1),BORDER); bottom.addView(save); bottom.addView(clear); root.addView(bottom);
        pdf.setOnClickListener(v->{saveDraft();createPdf();}); save.setOnClickListener(v->{saveDraft();Toast.makeText(this,"تم حفظ المسودة",Toast.LENGTH_SHORT).show();}); clear.setOnClickListener(v->new AlertDialog.Builder(this).setMessage("هل تريد بدء نموذج جديد؟").setPositiveButton("نعم",(d,w)->clearForm()).setNegativeButton("إلغاء",null).show());
        setContentView(scroll);
    }

    private View headerCard(){ LinearLayout c=card(); LinearLayout r=new LinearLayout(this); r.setOrientation(LinearLayout.HORIZONTAL); r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); r.setGravity(Gravity.CENTER_VERTICAL); TextView logo=new TextView(this); logo.setText("IGP"); logo.setTextColor(Color.WHITE); logo.setTextSize(18); logo.setTypeface(Typeface.DEFAULT_BOLD); logo.setGravity(Gravity.CENTER); logo.setBackground(round(GREEN,18,GREEN,0)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(58),dp(58)); lp.leftMargin=dp(12); logo.setLayoutParams(lp); r.addView(logo); LinearLayout tx=new LinearLayout(this); tx.setOrientation(LinearLayout.VERTICAL); tx.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1)); TextView co=title("Infinity Green Power",15); co.setTextColor(GREEN); TextView tt=title("Solar Offer Form",24); tt.setTextColor(NAVY); TextView ss=sub("نموذج معاينة وتجهيز عرض السعر"); tx.addView(co); tx.addView(tt); tx.addView(ss); r.addView(tx); c.addView(r); LinearLayout chips=new LinearLayout(this); chips.setOrientation(LinearLayout.HORIZONTAL); chips.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2); cp.topMargin=dp(12); chips.setLayoutParams(cp); chips.addView(chip("بحث مواد",Color.rgb(238,244,251),NAVY)); chips.addView(chip("صور الموقع",Color.rgb(234,248,240),GREEN)); chips.addView(chip("PDF",Color.rgb(238,244,251),NAVY)); c.addView(chips); return c; }
    private LinearLayout section(String n,String t,String s){ LinearLayout c=card(); LinearLayout h=new LinearLayout(this); h.setOrientation(LinearLayout.HORIZONTAL); h.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); h.setGravity(Gravity.CENTER_VERTICAL); TextView badge=new TextView(this); badge.setText(n); badge.setTextColor(Color.WHITE); badge.setTypeface(Typeface.DEFAULT_BOLD); badge.setGravity(Gravity.CENTER); badge.setBackground(round(NAVY,12,NAVY,0)); LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(38),dp(26)); bp.leftMargin=dp(10); badge.setLayoutParams(bp); h.addView(badge); LinearLayout tx=new LinearLayout(this); tx.setOrientation(LinearLayout.VERTICAL); tx.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1)); tx.addView(title(t,18)); tx.addView(sub(s)); h.addView(tx); c.addView(h); View line=new View(this); line.setBackgroundColor(Color.rgb(232,238,245)); LinearLayout.LayoutParams vl=new LinearLayout.LayoutParams(-1,dp(1)); vl.topMargin=dp(12); vl.bottomMargin=dp(12); line.setLayoutParams(vl); c.addView(line); LinearLayout body=new LinearLayout(this); body.setOrientation(LinearLayout.VERTICAL); c.addView(body); root.addView(c); return body; }
    private LinearLayout card(){ LinearLayout c=new LinearLayout(this); c.setOrientation(LinearLayout.VERTICAL); c.setPadding(dp(16),dp(16),dp(16),dp(16)); c.setBackground(round(Color.WHITE,24,BORDER,1)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2); lp.topMargin=dp(14); c.setLayoutParams(lp); if(Build.VERSION.SDK_INT>=21)c.setElevation(dp(2)); return c; }
    private TextView title(String s,int z){ TextView v=new TextView(this); v.setText(s); v.setTextSize(z); v.setTextColor(TEXT); v.setTypeface(Typeface.DEFAULT_BOLD); v.setGravity(Gravity.RIGHT); return v; }
    private TextView sub(String s){ TextView v=new TextView(this); v.setText(s); v.setTextSize(12); v.setTextColor(MUTED); v.setGravity(Gravity.RIGHT); return v; }
    private TextView chip(String s,int bg,int fg){ TextView v=new TextView(this); v.setText(s); v.setTextSize(12); v.setTextColor(fg); v.setPadding(dp(10),dp(7),dp(10),dp(7)); v.setBackground(round(bg,14,bg,0)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2); lp.leftMargin=dp(8); v.setLayoutParams(lp); return v; }
    private EditText input(LinearLayout p,String label,String hint,boolean multi){ TextView l=title(label,14); LinearLayout.LayoutParams ll=new LinearLayout.LayoutParams(-1,-2); ll.bottomMargin=dp(6); l.setLayoutParams(ll); p.addView(l); EditText e=new EditText(this); e.setHint(hint); e.setTextSize(15); e.setTextColor(TEXT); e.setHintTextColor(Color.rgb(151,166,180)); e.setTextDirection(View.TEXT_DIRECTION_RTL); e.setGravity(multi?Gravity.TOP|Gravity.RIGHT:Gravity.CENTER_VERTICAL|Gravity.RIGHT); e.setBackground(round(Color.WHITE,16,BORDER,1)); e.setPadding(dp(14),dp(12),dp(14),dp(12)); if(multi)e.setSingleLine(false); else e.setSingleLine(true); LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,multi?dp(110):dp(52)); ep.bottomMargin=dp(12); e.setLayoutParams(ep); p.addView(e); return e; }
    private Spinner spinner(LinearLayout p,String label,String[] values){ TextView l=title(label,14); LinearLayout.LayoutParams ll=new LinearLayout.LayoutParams(-1,-2); ll.bottomMargin=dp(6); l.setLayoutParams(ll); p.addView(l); Spinner s=new Spinner(this); ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,values); a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item); s.setAdapter(a); s.setBackground(round(Color.WHITE,16,BORDER,1)); LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(52)); sp.bottomMargin=dp(12); s.setLayoutParams(sp); p.addView(s); return s; }
    private Button primary(String s,int c){ Button b=new Button(this); b.setText(s); b.setTextColor(Color.WHITE); b.setTextSize(15); b.setTypeface(Typeface.DEFAULT_BOLD); b.setBackground(round(c,18,c,0)); b.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(54))); return b; }
    private Button actionButton(String s,int bg,int fg){ Button b=new Button(this); b.setText(s); b.setTextColor(fg); b.setTextSize(13); b.setTypeface(Typeface.DEFAULT_BOLD); b.setBackground(round(bg,16,bg,0)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(46),1); lp.leftMargin=dp(4); lp.rightMargin=dp(4); b.setLayoutParams(lp); return b; }
    private GradientDrawable round(int fill,int radius,int stroke,int sw){ GradientDrawable d=new GradientDrawable(); d.setColor(fill); d.setCornerRadius(dp(radius)); if(sw>0)d.setStroke(dp(sw),stroke); return d; }

    private void renderItems(){ itemsBox.removeAllViews(); if(items.isEmpty()){itemsBox.addView(empty("لا توجد مواد مضافة","ابدأ بالاختيار من الكتالوج أو إضافة مادة مخصصة."));return;} for(int i=0;i<items.size();i++){final int idx=i;Item it=items.get(i);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(12),dp(14),dp(12));c.setBackground(round(Color.rgb(251,253,255),18,BORDER,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(10);c.setLayoutParams(lp);LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);top.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView t=title(it.type,16);t.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));top.addView(t);TextView del=tag("حذف",Color.rgb(179,38,30),Color.rgb(255,240,240));TextView edit=tag("تعديل",NAVY,Color.rgb(238,244,251));del.setOnClickListener(v->{items.remove(idx);renderItems();});edit.setOnClickListener(v->editItem(new Item(it.type,it.model,it.capacity,it.qty,it.price),idx,true));top.addView(del);top.addView(edit);c.addView(top);if(!emptyS(it.model)){TextView m=sub(it.model);LinearLayout.LayoutParams ml=new LinearLayout.LayoutParams(-1,-2);ml.topMargin=dp(4);ml.bottomMargin=dp(8);m.setLayoutParams(ml);c.addView(m);}LinearLayout chips=new LinearLayout(this);chips.setOrientation(LinearLayout.HORIZONTAL);chips.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);chips.addView(chip("السعة: "+val(it.capacity),Color.rgb(238,244,251),NAVY));chips.addView(chip("الكمية: "+val(it.qty),Color.rgb(234,248,240),GREEN));chips.addView(chip("السعر: "+(emptyS(it.price)?"—":it.price),Color.rgb(255,247,232),Color.rgb(138,90,0)));c.addView(chips);itemsBox.addView(c);} }
    private TextView tag(String s,int fg,int bg){TextView v=new TextView(this);v.setText(s);v.setTextColor(fg);v.setTextSize(12);v.setTypeface(Typeface.DEFAULT_BOLD);v.setPadding(dp(10),dp(6),dp(10),dp(6));v.setBackground(round(bg,12,bg,0));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.leftMargin=dp(8);v.setLayoutParams(lp);return v;}
    private View empty(String t,String s){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(14),dp(14),dp(14),dp(14));b.setBackground(round(Color.rgb(250,252,254),16,BORDER,1));b.addView(title(t,14));b.addView(sub(s));return b;}

    private void showCatalog(){ AlertDialog.Builder b=new AlertDialog.Builder(this);b.setTitle("اختيار مادة من الكتالوج");LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(10),dp(14),dp(10));EditText search=new EditText(this);search.setHint("ابحث: Deye, Huasun, Roypow, كيبل...");search.setBackground(round(Color.WHITE,14,BORDER,1));search.setPadding(dp(12),dp(10),dp(12),dp(10));search.setTextDirection(View.TEXT_DIRECTION_RTL);box.addView(search,new LinearLayout.LayoutParams(-1,dp(48)));ListView list=new ListView(this);ArrayList<Product> filtered=new ArrayList<>(catalog);ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,names(filtered));list.setAdapter(a);LinearLayout.LayoutParams ll=new LinearLayout.LayoutParams(-1,dp(420));ll.topMargin=dp(10);box.addView(list,ll);b.setView(box);b.setNegativeButton("إغلاق",null);AlertDialog d=b.create();search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int aft){}public void onTextChanged(CharSequence s,int st,int before,int count){}public void afterTextChanged(Editable e){String q=e.toString().trim().toLowerCase(Locale.ROOT);filtered.clear();for(Product p:catalog){String h=(p.type+" "+p.model+" "+p.capacity).toLowerCase(Locale.ROOT);if(q.isEmpty()||h.contains(q))filtered.add(p);}a.clear();a.addAll(names(filtered));a.notifyDataSetChanged();}});list.setOnItemClickListener((p,v,pos,id)->{Product x=filtered.get(pos);d.dismiss();editItem(new Item(x.type,x.model,x.capacity,"1",""),-1,false);});d.show(); }
    private ArrayList<String> names(ArrayList<Product> p){ArrayList<String> n=new ArrayList<>();for(Product x:p)n.add(x.display());return n;}
    private void editItem(Item base,int index,boolean typeEditable){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(8),dp(16),0);EditText type=dialogF(box,"المادة","اسم المادة");type.setText(base.type);type.setEnabled(typeEditable);EditText model=dialogF(box,"الماركة / الموديل","مثال: Deye 8kW");model.setText(base.model);EditText cap=dialogF(box,"السعة / القياس","مثال: 620W أو 16kWh");cap.setText(base.capacity);EditText qty=dialogF(box,"الكمية","1");qty.setText(emptyS(base.qty)?"1":base.qty);EditText price=dialogF(box,"السعر (اختياري)","مثال: 900");price.setText(base.price);new AlertDialog.Builder(this).setTitle(index>=0?"تعديل المادة":"إضافة مادة").setView(box).setPositiveButton(index>=0?"حفظ":"إضافة",(d,w)->{Item it=new Item(type.getText().toString().trim(),model.getText().toString().trim(),cap.getText().toString().trim(),qty.getText().toString().trim(),price.getText().toString().trim());if(emptyS(it.type)){Toast.makeText(this,"اكتب اسم المادة",Toast.LENGTH_SHORT).show();return;}if(index>=0)items.set(index,it);else items.add(it);renderItems();}).setNegativeButton("إلغاء",null).show();}
    private EditText dialogF(LinearLayout p,String l,String h){p.addView(title(l,13));EditText e=new EditText(this);e.setHint(h);e.setTextDirection(View.TEXT_DIRECTION_RTL);e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setBackground(round(Color.WHITE,14,BORDER,1));e.setPadding(dp(12),dp(10),dp(12),dp(10));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(46));lp.bottomMargin=dp(8);e.setLayoutParams(lp);p.addView(e);return e;}

    private void pickImages(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,PICK_IMAGES);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==PICK_IMAGES&&res==RESULT_OK&&data!=null){if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount();i++)addPhoto(data.getClipData().getItemAt(i).getUri(),data.getFlags());}else if(data.getData()!=null)addPhoto(data.getData(),data.getFlags());renderPhotos();saveDraft();}}
    private void addPhoto(Uri u,int flags){try{getContentResolver().takePersistableUriPermission(u,flags&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(Exception ignored){}String s=u.toString();if(!photos.contains(s))photos.add(s);}
    private void renderPhotos(){photosBox.removeAllViews();if(photos.isEmpty()){photosBox.addView(empty("لا توجد صور مرفقة","يمكنك إضافة صورة أو أكثر للموقع."));return;}for(int i=0;i<photos.size();i++){final int idx=i;LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(12),dp(10),dp(12),dp(10));r.setBackground(round(Color.rgb(251,253,255),16,BORDER,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(8);r.setLayoutParams(lp);TextView t=new TextView(this);t.setText("📷 "+displayName(Uri.parse(photos.get(i))));t.setTextColor(TEXT);t.setTextSize(13);t.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));r.addView(t);TextView del=tag("حذف",Color.rgb(179,38,30),Color.rgb(255,240,240));del.setOnClickListener(v->{photos.remove(idx);renderPhotos();});r.addView(del);photosBox.addView(r);}}

    private void saveDraft(){SharedPreferences.Editor e=getSharedPreferences("proDraft",0).edit();e.putString("client",txt(clientName));e.putString("phone",txt(phone));e.putString("location",txt(location));e.putString("date",txt(date));e.putString("kw",txt(sizeKw));e.putString("notes",txt(notes));e.putString("organizer",txt(organizer));e.putInt("system",systemType.getSelectedItemPosition());e.putInt("phase",phase.getSelectedItemPosition());e.putBoolean("installation",installation.isChecked());e.putBoolean("transport",transport.isChecked());e.putString("items",serializeItems());e.putString("photos",join(photos));e.apply();}
    private void loadDraft(){SharedPreferences p=getSharedPreferences("proDraft",0);clientName.setText(p.getString("client",""));phone.setText(p.getString("phone",""));location.setText(p.getString("location",""));String d=p.getString("date","");if(!emptyS(d))date.setText(d);sizeKw.setText(p.getString("kw",""));notes.setText(p.getString("notes",""));organizer.setText(p.getString("organizer",""));systemType.setSelection(p.getInt("system",0));phase.setSelection(p.getInt("phase",0));installation.setChecked(p.getBoolean("installation",false));transport.setChecked(p.getBoolean("transport",false));items.clear();String si=p.getString("items","");if(!emptyS(si)){for(String row:si.split("\\u001E")){String[] c=row.split("\\u001F",-1);if(c.length>=5)items.add(new Item(c[0],c[1],c[2],c[3],c[4]));}}photos.clear();String sp=p.getString("photos","");if(!emptyS(sp)){for(String s:sp.split("\\u001E"))if(!emptyS(s))photos.add(s);}renderItems();renderPhotos();}
    private void clearForm(){getSharedPreferences("proDraft",0).edit().clear().apply();clientName.setText("");phone.setText("");location.setText("");sizeKw.setText("");notes.setText("");organizer.setText("");systemType.setSelection(0);phase.setSelection(0);installation.setChecked(false);transport.setChecked(false);date.setText(new SimpleDateFormat("yyyy/MM/dd",Locale.US).format(new Date()));items.clear();photos.clear();renderItems();renderPhotos();}
    private String serializeItems(){StringBuilder s=new StringBuilder();for(Item i:items){if(s.length()>0)s.append('\u001E');s.append(clean(i.type)).append('\u001F').append(clean(i.model)).append('\u001F').append(clean(i.capacity)).append('\u001F').append(clean(i.qty)).append('\u001F').append(clean(i.price));}return s.toString();}
    private String join(ArrayList<String> a){StringBuilder s=new StringBuilder();for(String x:a){if(s.length()>0)s.append('\u001E');s.append(x);}return s.toString();}
    private String clean(String s){return s==null?"":s.replace("\u001E"," ").replace("\u001F"," ");}

    private void createPdf(){try{File dir=getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS);if(dir==null)throw new IOException("Storage unavailable");if(!dir.exists())dir.mkdirs();String safe=txt(clientName).replaceAll("[^\\p{L}\\p{N}_-]","_");if(emptyS(safe))safe="client";File file=new File(dir,"SolarForm_"+safe+"_"+System.currentTimeMillis()+".pdf");PdfDocument doc=new PdfDocument();Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);PdfDocument.Page page=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=page.getCanvas();c.drawColor(Color.WHITE);p.setTextAlign(Paint.Align.RIGHT);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextSize(23);p.setColor(NAVY);c.drawText("استمارة طلب عرض سعر منظومة شمسية",560,42,p);p.setTextSize(13);p.setColor(GREEN);c.drawText("Infinity Green Power",560,64,p);int y=95;y=pdfSection(c,p,y,"معلومات العميل");y=pdfLine(c,p,"اسم العميل",txt(clientName),y);y=pdfLine(c,p,"رقم الهاتف",txt(phone),y);y=pdfLine(c,p,"الموقع",txt(location),y);y=pdfLine(c,p,"التاريخ",txt(date),y);y=pdfSection(c,p,y+6,"معلومات المنظومة");y=pdfLine(c,p,"نوع المنظومة",spin(systemType),y);y=pdfLine(c,p,"السعة المطلوبة",txt(sizeKw)+(emptyS(txt(sizeKw))?"":" kW"),y);y=pdfLine(c,p,"الطور",spin(phase),y);y=pdfSection(c,p,y+6,"المواد المطلوبة");for(Item it:items){y=pdfLine(c,p,it.type,(emptyS(it.model)?"":it.model)+" | "+val(it.capacity)+" | Qty: "+val(it.qty)+(emptyS(it.price)?"":" | $"+it.price),y);}y=pdfSection(c,p,y+6,"معلومات إضافية");y=pdfLine(c,p,"التركيب",installation.isChecked()?"نعم":"لا",y);y=pdfLine(c,p,"النقل",transport.isChecked()?"نعم":"لا",y);y=pdfLine(c,p,"منظم الكشف",txt(organizer),y);y=pdfLine(c,p,"عدد الصور",String.valueOf(photos.size()),y);pdfLine(c,p,"ملاحظات",txt(notes),y);doc.finishPage(page);for(int i=0;i<photos.size();i++){Bitmap bm=decode(Uri.parse(photos.get(i)));if(bm==null)continue;PdfDocument.Page pg=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,i+2).create());Canvas pc=pg.getCanvas();pc.drawColor(Color.WHITE);p.setTextAlign(Paint.Align.RIGHT);p.setTextSize(20);p.setColor(NAVY);pc.drawText("صورة الموقع / المنظومة",560,42,p);float sc=Math.min(500f/bm.getWidth(),700f/bm.getHeight());int nw=(int)(bm.getWidth()*sc),nh=(int)(bm.getHeight()*sc),left=(595-nw)/2,top=90+(700-nh)/2;pc.drawBitmap(bm,null,new Rect(left,top,left+nw,top+nh),null);doc.finishPage(pg);bm.recycle();}FileOutputStream o=new FileOutputStream(file);doc.writeTo(o);o.close();doc.close();Uri uri=new Uri.Builder().scheme("content").authority(getPackageName()+".provider").appendPath(file.getName()).build();Intent sh=new Intent(Intent.ACTION_SEND);sh.setType("application/pdf");sh.putExtra(Intent.EXTRA_STREAM,uri);sh.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(sh,"مشاركة النموذج"));}catch(Exception ex){Toast.makeText(this,"تعذر إنشاء PDF: "+ex.getMessage(),Toast.LENGTH_LONG).show();}}
    private int pdfSection(Canvas c,Paint p,int y,String s){p.setColor(NAVY);c.drawRoundRect(35,y,560,y+24,10,10,p);p.setColor(Color.WHITE);p.setTextSize(12);p.setTextAlign(Paint.Align.RIGHT);p.setTypeface(Typeface.create("sans",Typeface.BOLD));c.drawText(s,550,y+17,p);return y+34;}
    private int pdfLine(Canvas c,Paint p,String l,String v,int y){p.setColor(TEXT);p.setTextSize(10);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextAlign(Paint.Align.RIGHT);c.drawText(l+" :",555,y+15,p);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));String z=emptyS(v)?"—":v;if(z.length()>55)z=z.substring(0,54)+"…";c.drawText(z,430,y+15,p);p.setColor(Color.rgb(230,238,244));c.drawLine(35,y+24,560,y+24,p);return y+28;}
    private Bitmap decode(Uri u){try{InputStream is=getContentResolver().openInputStream(u);BitmapFactory.Options b=new BitmapFactory.Options();b.inJustDecodeBounds=true;BitmapFactory.decodeStream(is,null,b);if(is!=null)is.close();int sample=1;while(b.outWidth/sample>1200||b.outHeight/sample>1200)sample*=2;BitmapFactory.Options o=new BitmapFactory.Options();o.inSampleSize=sample;InputStream is2=getContentResolver().openInputStream(u);Bitmap bm=BitmapFactory.decodeStream(is2,null,o);if(is2!=null)is2.close();return bm;}catch(Exception e){return null;}}
    private String displayName(Uri u){try{Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&i>=0){String n=c.getString(i);c.close();return n;}c.close();}}catch(Exception ignored){}return u.getLastPathSegment()==null?"image":u.getLastPathSegment();}
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+0.5f);} private String txt(EditText e){return e.getText().toString().trim();} private boolean emptyS(String s){return s==null||s.trim().isEmpty();} private String val(String s){return emptyS(s)?"—":s;} private String spin(Spinner s){String v=String.valueOf(s.getSelectedItem());return v.startsWith("اختر")?"":v;}
}