package com.infinitygreenpower.solarform;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class ProfessionalActivity extends Activity {
    private final int NAVY=Color.rgb(18,61,107), GREEN=Color.rgb(46,155,93), BG=Color.rgb(244,247,251), TEXT=Color.rgb(27,39,51), MUTED=Color.rgb(105,121,137), BORDER=Color.rgb(218,228,238);
    private final int PICK_IMAGES=3301;
    private LinearLayout root, itemsBox, photosBox;
    private EditText clientName, phone, location, date, sizeKw, notes, organizer;
    private Spinner systemType, phase;
    private CheckBox installation, transport;
    private final ArrayList<Product> catalog=new ArrayList<>();
    private final ArrayList<Item> items=new ArrayList<>();
    private final ArrayList<Uri> photoUris=new ArrayList<>();

    static class Product { String material,model,capacity; Product(String a,String b,String c){material=a;model=b;capacity=c;} String display(){return material+" — "+model+(capacity.isEmpty()?"":" — "+capacity);} String searchable(){return display().toLowerCase(Locale.ROOT);} }
    static class Item { String material,model,capacity,qty,price; Item(String a,String b,String c,String d,String e){material=a;model=b;capacity=c;qty=d;price=e;} }

    @Override public void onCreate(Bundle b){ super.onCreate(b); getWindow().setStatusBarColor(NAVY); seedCatalog(); buildUi(); loadDraft(); }

    private void seedCatalog(){
        catalog.add(new Product("الألواح الشمسية","Huasun HJT","610 W")); catalog.add(new Product("الألواح الشمسية","Huasun HJT","615 W")); catalog.add(new Product("الألواح الشمسية","Huasun HJT","620 W"));
        catalog.add(new Product("الإنفرتر","Roypow RS6500 Hybrid","6.5 kW")); catalog.add(new Product("الإنفرتر","Deye Hybrid - Single Phase","6 kW")); catalog.add(new Product("الإنفرتر","Deye Hybrid - Single Phase","8 kW")); catalog.add(new Product("الإنفرتر","Deye Hybrid - Single Phase","12 kW")); catalog.add(new Product("الإنفرتر","Deye Hybrid - Single Phase","16 kW")); catalog.add(new Product("الإنفرتر","Deye Hybrid - Three Phase","12 kW")); catalog.add(new Product("الإنفرتر","Deye Hybrid - Three Phase","16 kW"));
        catalog.add(new Product("البطارية","Roypow LiFePO4","16 kWh")); catalog.add(new Product("البطارية","Deye High Voltage Battery Rack","HV")); catalog.add(new Product("BMS","Deye High Voltage BMS","HV"));
        catalog.add(new Product("القواعد","هيكل تثبيت ألواح شمسية","حسب الموقع")); catalog.add(new Product("كيبل DC","Solar DC Cable","حدد القياس")); catalog.add(new Product("كيبل AC","AC Cable","حدد القياس")); catalog.add(new Product("كيبل البطاريات","Battery Cable","حدد القياس")); catalog.add(new Product("صندوق حماية / تجميع","Protection Box / Combiner","")); catalog.add(new Product("قاطع DC","DC Breaker","")); catalog.add(new Product("قاطع AC","AC Breaker","")); catalog.add(new Product("حماية DC","DC SPD","")); catalog.add(new Product("حماية AC","AC SPD","")); catalog.add(new Product("موصلات","MC4 Connectors","")); catalog.add(new Product("لوحة توزيع","Distribution Board (DB)","")); catalog.add(new Product("تأريض","Earthing System","")); catalog.add(new Product("قضيب أرضي","Earth Rod","")); catalog.add(new Product("مسار كيبل","Cable Tray / PVC","")); catalog.add(new Product("تركيب","أجور تركيب",""));
    }

    private void buildUi(){
        ScrollView scroll=new ScrollView(this); scroll.setFillViewport(true); scroll.setBackgroundColor(BG);
        root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); root.setPadding(dp(16),dp(16),dp(16),dp(28)); scroll.addView(root,new ScrollView.LayoutParams(-1,-2));
        root.addView(header());

        LinearLayout s1=section("01","معلومات العميل","البيانات الأساسية الخاصة بالطلب");
        clientName=field(s1,"اسم العميل","اكتب اسم العميل",false,android.text.InputType.TYPE_CLASS_TEXT); phone=field(s1,"رقم الهاتف","07xx xxx xxxx",false,android.text.InputType.TYPE_CLASS_PHONE); location=field(s1,"الموقع","المدينة / المنطقة",false,android.text.InputType.TYPE_CLASS_TEXT); date=field(s1,"التاريخ","YYYY/MM/DD",false,android.text.InputType.TYPE_CLASS_TEXT); date.setText(new SimpleDateFormat("yyyy/MM/dd",Locale.US).format(new Date()));

        LinearLayout s2=section("02","معلومات المنظومة","نوع النظام والسعة المطلوبة");
        systemType=spinner(s2,"نوع المنظومة",new String[]{"اختر نوع المنظومة","هجين","أون كريد","أوف كريد"}); sizeKw=field(s2,"السعة المطلوبة (kW)","مثال: 8",false,android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL); phase=spinner(s2,"الطور",new String[]{"اختر الطور","أحادي","ثلاثي"});

        LinearLayout s3=section("03","المواد المطلوبة","ابحث واختر كما في تطبيقات إنشاء النماذج");
        TextView hint=small("أضف المواد كبطاقات واضحة، ثم عدّل الكمية والسعر عند الحاجة."); s3.addView(hint);
        LinearLayout actionRow=new LinearLayout(this); actionRow.setOrientation(LinearLayout.HORIZONTAL); actionRow.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
        Button catalogBtn=smallButton("اختيار من الكتالوج",NAVY,Color.WHITE); Button customBtn=smallButton("مادة مخصصة",Color.WHITE,NAVY); ((GradientDrawable)customBtn.getBackground()).setStroke(dp(1),BORDER); actionRow.addView(catalogBtn); actionRow.addView(customBtn); s3.addView(actionRow);
        itemsBox=new LinearLayout(this); itemsBox.setOrientation(LinearLayout.VERTICAL); LinearLayout.LayoutParams ibp=new LinearLayout.LayoutParams(-1,-2); ibp.topMargin=dp(10); itemsBox.setLayoutParams(ibp); s3.addView(itemsBox); renderItems(); catalogBtn.setOnClickListener(v->showCatalog()); customBtn.setOnClickListener(v->showItemDialog(new Item("","","","1",""),true,-1));

        LinearLayout s4=section("04","صور الموقع / المنظومة","إرفاق صور المعاينة مع الطلب");
        Button photoBtn=primary("إرفاق صور من الهاتف",NAVY); LinearLayout.LayoutParams pb=(LinearLayout.LayoutParams)photoBtn.getLayoutParams(); pb.height=dp(46); photoBtn.setLayoutParams(pb); s4.addView(photoBtn); photosBox=new LinearLayout(this); photosBox.setOrientation(LinearLayout.VERTICAL); LinearLayout.LayoutParams phlp=new LinearLayout.LayoutParams(-1,-2); phlp.topMargin=dp(10); photosBox.setLayoutParams(phlp); s4.addView(photosBox); renderPhotos(); photoBtn.setOnClickListener(v->pickImages());

        LinearLayout s5=section("05","معلومات إضافية","تفاصيل تساعد على تجهيز العرض النهائي");
        LinearLayout checks=new LinearLayout(this); checks.setOrientation(LinearLayout.HORIZONTAL); checks.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); installation=new CheckBox(this); installation.setText("يشمل التركيب"); transport=new CheckBox(this); transport.setText("يشمل النقل"); checks.addView(installation); checks.addView(transport); s5.addView(checks);
        notes=field(s5,"ملاحظات","أي ملاحظات إضافية عن الطلب أو الموقع",true,android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE); organizer=field(s5,"اسم منظم الكشف","اسم الشخص المسؤول عن المعاينة",false,android.text.InputType.TYPE_CLASS_TEXT);

        LinearLayout bottom=new LinearLayout(this); bottom.setOrientation(LinearLayout.VERTICAL); LinearLayout.LayoutParams blp=new LinearLayout.LayoutParams(-1,-2); blp.topMargin=dp(14); bottom.setLayoutParams(blp); Button pdf=primary("إنشاء PDF ومشاركته",GREEN); bottom.addView(pdf); LinearLayout br=new LinearLayout(this); br.setOrientation(LinearLayout.HORIZONTAL); br.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); LinearLayout.LayoutParams brp=new LinearLayout.LayoutParams(-1,-2); brp.topMargin=dp(8); br.setLayoutParams(brp); Button save=smallButton("حفظ المسودة",Color.WHITE,NAVY); Button clear=smallButton("نموذج جديد",Color.WHITE,NAVY); ((GradientDrawable)save.getBackground()).setStroke(dp(1),BORDER); ((GradientDrawable)clear.getBackground()).setStroke(dp(1),BORDER); br.addView(save); br.addView(clear); bottom.addView(br); root.addView(bottom);
        save.setOnClickListener(v->{saveDraft();Toast.makeText(this,"تم حفظ المسودة",Toast.LENGTH_SHORT).show();}); pdf.setOnClickListener(v->{saveDraft();createPdf();}); clear.setOnClickListener(v->new AlertDialog.Builder(this).setMessage("هل تريد مسح جميع البيانات؟").setPositiveButton("نعم",(d,w)->clearForm()).setNegativeButton("إلغاء",null).show());
        setContentView(scroll);
    }

    private View header(){
        LinearLayout c=card(); c.setPadding(dp(18),dp(18),dp(18),dp(18)); LinearLayout top=new LinearLayout(this); top.setOrientation(LinearLayout.HORIZONTAL); top.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); top.setGravity(Gravity.CENTER_VERTICAL);
        TextView logo=new TextView(this); logo.setText("IGP"); logo.setTextColor(Color.WHITE); logo.setTextSize(18); logo.setTypeface(Typeface.DEFAULT_BOLD); logo.setGravity(Gravity.CENTER); logo.setBackground(round(GREEN,18,0,0)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(58),dp(58)); lp.leftMargin=dp(12); logo.setLayoutParams(lp); top.addView(logo);
        LinearLayout tw=new LinearLayout(this); tw.setOrientation(LinearLayout.VERTICAL); tw.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1)); TextView co=text("Infinity Green Power",16,true,GREEN); TextView title=text("Solar Form Maker",24,true,TEXT); TextView ar=text("استمارة عرض سعر احترافية وسريعة للمنظمين",13,false,MUTED); tw.addView(co);tw.addView(title);tw.addView(ar);top.addView(tw);c.addView(top);
        LinearLayout tags=new LinearLayout(this); tags.setOrientation(LinearLayout.HORIZONTAL); tags.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,-2); tp.topMargin=dp(14); tags.setLayoutParams(tp); tags.addView(chip("كتالوج مواد",Color.rgb(238,244,251),NAVY)); tags.addView(chip("صور موقع",Color.rgb(234,248,240),GREEN)); tags.addView(chip("PDF",Color.rgb(238,244,251),NAVY)); c.addView(tags); return c;
    }

    private LinearLayout section(String num,String title,String sub){
        LinearLayout c=card(); LinearLayout.LayoutParams cp=(LinearLayout.LayoutParams)c.getLayoutParams(); cp.topMargin=dp(14); c.setLayoutParams(cp);
        LinearLayout h=new LinearLayout(this); h.setOrientation(LinearLayout.HORIZONTAL); h.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); h.setGravity(Gravity.CENTER_VERTICAL); TextView badge=text(num,12,true,Color.WHITE); badge.setGravity(Gravity.CENTER); badge.setBackground(round(NAVY,12,0,0)); LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(38),dp(26)); bp.leftMargin=dp(10); badge.setLayoutParams(bp); h.addView(badge); LinearLayout ht=new LinearLayout(this); ht.setOrientation(LinearLayout.VERTICAL); ht.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1)); ht.addView(text(title,18,true,TEXT)); ht.addView(text(sub,12,false,MUTED)); h.addView(ht); c.addView(h);
        View line=new View(this); line.setBackgroundColor(Color.rgb(231,238,245)); LinearLayout.LayoutParams vlp=new LinearLayout.LayoutParams(-1,dp(1)); vlp.topMargin=dp(12);vlp.bottomMargin=dp(12);line.setLayoutParams(vlp);c.addView(line); LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);c.addView(body);root.addView(c);return body;
    }

    private EditText field(LinearLayout p,String label,String hint,boolean multi,int input){ TextView l=text(label,14,true,TEXT); LinearLayout.LayoutParams ll=new LinearLayout.LayoutParams(-1,-2);ll.bottomMargin=dp(6);l.setLayoutParams(ll);p.addView(l);EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setTextColor(TEXT);e.setHintTextColor(Color.rgb(150,166,181));e.setTextDirection(View.TEXT_DIRECTION_RTL);e.setGravity(multi?Gravity.TOP|Gravity.RIGHT:Gravity.CENTER_VERTICAL|Gravity.RIGHT);e.setBackground(round(Color.WHITE,16,BORDER,1));e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setInputType(input);if(multi){e.setSingleLine(false);e.setMinLines(4);}else e.setSingleLine(true);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,multi?dp(112):dp(52));ep.bottomMargin=dp(12);e.setLayoutParams(ep);p.addView(e);return e; }
    private Spinner spinner(LinearLayout p,String label,String[] vals){TextView l=text(label,14,true,TEXT);LinearLayout.LayoutParams ll=new LinearLayout.LayoutParams(-1,-2);ll.bottomMargin=dp(6);l.setLayoutParams(ll);p.addView(l);Spinner s=new Spinner(this,Spinner.MODE_DROPDOWN);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,vals);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);s.setAdapter(a);s.setBackground(round(Color.WHITE,16,BORDER,1));s.setPadding(dp(12),dp(6),dp(12),dp(6));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(52));sp.bottomMargin=dp(12);s.setLayoutParams(sp);p.addView(s);return s;}

    private void renderItems(){itemsBox.removeAllViews();if(items.isEmpty()){itemsBox.addView(empty("لا توجد مواد مضافة","ابدأ باختيار مادة من الكتالوج أو إضافة مادة مخصصة."));return;}for(int i=0;i<items.size();i++){final int idx=i;Item it=items.get(i);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(12),dp(14),dp(12));c.setBackground(round(Color.rgb(251,253,255),18,BORDER,1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.bottomMargin=dp(10);c.setLayoutParams(cp);LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);top.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView title=text(it.material,16,true,TEXT);title.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));top.addView(title);top.addView(tag("حذف",Color.rgb(179,38,30),Color.rgb(255,240,240),v->{items.remove(idx);renderItems();}));top.addView(tag("تعديل",NAVY,Color.rgb(238,244,251),v->showItemDialog(new Item(it.material,it.model,it.capacity,it.qty,it.price),true,idx)));c.addView(top);if(!it.model.isEmpty()){TextView m=text(it.model,13,false,MUTED);LinearLayout.LayoutParams ml=new LinearLayout.LayoutParams(-1,-2);ml.topMargin=dp(4);ml.bottomMargin=dp(8);m.setLayoutParams(ml);c.addView(m);}LinearLayout ch=new LinearLayout(this);ch.setOrientation(LinearLayout.HORIZONTAL);ch.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);ch.addView(chip("السعة: "+val(it.capacity),Color.rgb(238,244,251),NAVY));ch.addView(chip("الكمية: "+val(it.qty),Color.rgb(234,248,240),GREEN));ch.addView(chip("السعر: "+(it.price.isEmpty()?"—":it.price),Color.rgb(255,246,232),Color.rgb(138,90,0)));c.addView(ch);itemsBox.addView(c);}}

    private void showCatalog(){final Dialog d=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(14),dp(14),dp(14));EditText search=new EditText(this);search.setHint("ابحث: Deye, Huasun, Roypow, كيبل...");search.setBackground(round(Color.WHITE,14,BORDER,1));search.setPadding(dp(12),dp(10),dp(12),dp(10));search.setTextDirection(View.TEXT_DIRECTION_RTL);box.addView(search,new LinearLayout.LayoutParams(-1,dp(48)));ListView list=new ListView(this);LinearLayout.LayoutParams ll=new LinearLayout.LayoutParams(-1,dp(430));ll.topMargin=dp(10);box.addView(list,ll);ArrayList<Product> filtered=new ArrayList<>(catalog);ArrayList<String> names=new ArrayList<>();for(Product p:filtered)names.add(p.display());ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,names);list.setAdapter(a);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int af){}public void onTextChanged(CharSequence s,int st,int b,int c){String q=s.toString().trim().toLowerCase(Locale.ROOT);filtered.clear();names.clear();for(Product p:catalog)if(q.isEmpty()||p.searchable().contains(q)){filtered.add(p);names.add(p.display());}a.notifyDataSetChanged();}public void afterTextChanged(Editable e){}});list.setOnItemClickListener((p,v,pos,id)->{Product x=filtered.get(pos);d.dismiss();showItemDialog(new Item(x.material,x.model,x.capacity,"1",""),false,-1);});d.setContentView(box);d.show();Window w=d.getWindow();if(w!=null)w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.94),WindowManager.LayoutParams.WRAP_CONTENT);}

    private void showItemDialog(Item base,boolean materialEditable,int editIndex){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(8),dp(16),0);EditText material=dialogField(box,"المادة","اسم المادة");material.setText(base.material);material.setEnabled(materialEditable);EditText model=dialogField(box,"الماركة / الموديل","مثال: Deye 8kW");model.setText(base.model);EditText cap=dialogField(box,"السعة / القياس","مثال: 620W أو 16kWh");cap.setText(base.capacity);EditText qty=dialogField(box,"الكمية","1");qty.setText(base.qty.isEmpty()?"1":base.qty);EditText price=dialogField(box,"السعر (اختياري)","مثال: 900");price.setText(base.price);new AlertDialog.Builder(this).setTitle(editIndex>=0?"تعديل المادة":"إضافة مادة").setView(box).setPositiveButton(editIndex>=0?"حفظ":"إضافة",(d,w)->{Item n=new Item(t(material),t(model),t(cap),t(qty),t(price));if(n.material.isEmpty()){Toast.makeText(this,"يرجى إدخال اسم المادة",Toast.LENGTH_SHORT).show();return;}if(editIndex>=0)items.set(editIndex,n);else items.add(n);renderItems();}).setNegativeButton("إلغاء",null).show();}
    private EditText dialogField(LinearLayout p,String label,String hint){p.addView(text(label,13,true,TEXT));EditText e=new EditText(this);e.setHint(hint);e.setTextDirection(View.TEXT_DIRECTION_RTL);e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setBackground(round(Color.WHITE,14,BORDER,1));e.setPadding(dp(12),dp(10),dp(12),dp(10));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(46));lp.bottomMargin=dp(8);e.setLayoutParams(lp);p.addView(e);return e;}

    private void pickImages(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,PICK_IMAGES);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==PICK_IMAGES&&res==RESULT_OK&&data!=null){if(data.getClipData()!=null){ClipData cd=data.getClipData();for(int i=0;i<cd.getItemCount();i++)addPhoto(cd.getItemAt(i).getUri(),data.getFlags());}else if(data.getData()!=null)addPhoto(data.getData(),data.getFlags());renderPhotos();saveDraft();}}
    private void addPhoto(Uri uri,int flags){if(uri==null)return;try{getContentResolver().takePersistableUriPermission(uri,flags&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(Exception ignored){}if(!photoUris.contains(uri))photoUris.add(uri);}
    private void renderPhotos(){photosBox.removeAllViews();if(photoUris.isEmpty()){photosBox.addView(empty("لم يتم إرفاق صور","يمكن إضافة صورة أو أكثر لمكان التركيب أو النظام الحالي."));return;}for(int i=0;i<photoUris.size();i++){final int idx=i;LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);row.setPadding(dp(12),dp(10),dp(12),dp(10));row.setBackground(round(Color.rgb(251,253,255),16,BORDER,1));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.bottomMargin=dp(8);row.setLayoutParams(rp);TextView nm=text("📷  "+displayName(photoUris.get(i)),13,false,TEXT);nm.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));row.addView(nm);row.addView(tag("حذف",Color.rgb(179,38,30),Color.rgb(255,240,240),v->{photoUris.remove(idx);renderPhotos();}));photosBox.addView(row);}}

    private void saveDraft(){SharedPreferences.Editor e=getSharedPreferences("pro_draft",0).edit();e.putString("client",t(clientName)).putString("phone",t(phone)).putString("location",t(location)).putString("date",t(date)).putString("kw",t(sizeKw)).putString("notes",t(notes)).putString("organizer",t(organizer));e.putInt("system",systemType.getSelectedItemPosition()).putInt("phase",phase.getSelectedItemPosition()).putBoolean("installation",installation.isChecked()).putBoolean("transport",transport.isChecked()).putString("items",serializeItems()).putString("photos",serializePhotos()).apply();}
    private void loadDraft(){SharedPreferences p=getSharedPreferences("pro_draft",0);clientName.setText(p.getString("client",""));phone.setText(p.getString("phone",""));location.setText(p.getString("location",""));String d=p.getString("date","");if(!d.isEmpty())date.setText(d);sizeKw.setText(p.getString("kw",""));notes.setText(p.getString("notes",""));organizer.setText(p.getString("organizer",""));systemType.setSelection(p.getInt("system",0));phase.setSelection(p.getInt("phase",0));installation.setChecked(p.getBoolean("installation",false));transport.setChecked(p.getBoolean("transport",false));items.clear();String is=p.getString("items","");if(!is.isEmpty())for(String r:is.split("\\u001E")){String[] c=r.split("\\u001F",-1);if(c.length>=5)items.add(new Item(c[0],c[1],c[2],c[3],c[4]));}photoUris.clear();String ps=p.getString("photos","");if(!ps.isEmpty())for(String s:ps.split("\\u001E"))if(!s.isEmpty())photoUris.add(Uri.parse(s));renderItems();renderPhotos();}
    private String serializeItems(){StringBuilder b=new StringBuilder();for(Item i:items){if(b.length()>0)b.append('\u001E');b.append(clean(i.material)).append('\u001F').append(clean(i.model)).append('\u001F').append(clean(i.capacity)).append('\u001F').append(clean(i.qty)).append('\u001F').append(clean(i.price));}return b.toString();}
    private String serializePhotos(){StringBuilder b=new StringBuilder();for(Uri u:photoUris){if(b.length()>0)b.append('\u001E');b.append(u.toString());}return b.toString();}
    private String clean(String s){return s==null?"":s.replace("\u001E"," ").replace("\u001F"," ");}
    private void clearForm(){getSharedPreferences("pro_draft",0).edit().clear().apply();clientName.setText("");phone.setText("");location.setText("");sizeKw.setText("");notes.setText("");organizer.setText("");systemType.setSelection(0);phase.setSelection(0);installation.setChecked(false);transport.setChecked(false);date.setText(new SimpleDateFormat("yyyy/MM/dd",Locale.US).format(new Date()));items.clear();photoUris.clear();renderItems();renderPhotos();}

    private void createPdf(){try{File dir=getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS);if(dir==null)throw new Exception("Storage unavailable");if(!dir.exists())dir.mkdirs();String safe=t(clientName).replaceAll("[^\\p{L}\\p{N}_-]","_");if(safe.isEmpty())safe="client";File file=new File(dir,"Solar_Form_"+safe+"_"+System.currentTimeMillis()+".pdf");PdfDocument doc=new PdfDocument();Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);PdfDocument.Page page=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=page.getCanvas();c.drawColor(Color.WHITE);p.setColor(TEXT);p.setTextAlign(Paint.Align.RIGHT);p.setTextSize(22);p.setTypeface(Typeface.create("sans",Typeface.BOLD));c.drawText("استمارة طلب عرض سعر منظومة شمسية",560,40,p);p.setTextSize(13);p.setColor(GREEN);c.drawText("Infinity Green Power",560,62,p);int y=96;y=pdfSection(c,p,y,"معلومات العميل");y=pdfLine(c,p,"اسم العميل",t(clientName),y);y=pdfLine(c,p,"رقم الهاتف",t(phone),y);y=pdfLine(c,p,"الموقع",t(location),y);y=pdfLine(c,p,"التاريخ",t(date),y);y=pdfSection(c,p,y+6,"معلومات المنظومة");y=pdfLine(c,p,"نوع المنظومة",spin(systemType),y);y=pdfLine(c,p,"السعة المطلوبة",t(sizeKw)+(t(sizeKw).isEmpty()?"":" kW"),y);y=pdfLine(c,p,"الطور",spin(phase),y);y=pdfSection(c,p,y+6,"المواد المطلوبة");for(Item i:items){y=pdfLine(c,p,i.material,(i.model+"  "+i.capacity+"  ×"+i.qty+(i.price.isEmpty()?"":"  $"+i.price)).trim(),y);}y=pdfSection(c,p,y+6,"معلومات إضافية");y=pdfLine(c,p,"التركيب",installation.isChecked()?"نعم":"لا",y);y=pdfLine(c,p,"النقل",transport.isChecked()?"نعم":"لا",y);y=pdfLine(c,p,"منظم الكشف",t(organizer),y);y=pdfLine(c,p,"عدد الصور",String.valueOf(photoUris.size()),y);p.setColor(MUTED);p.setTextSize(10);p.setTextAlign(Paint.Align.RIGHT);c.drawText("ملاحظات: "+trim(t(notes),70),560,y+18,p);p.setColor(GREEN);p.setTextAlign(Paint.Align.CENTER);c.drawText("Generated by Solar Form Maker",297,822,p);doc.finishPage(page);
        for(int i=0;i<photoUris.size();i++){Bitmap bmp=decode(photoUris.get(i));if(bmp==null)continue;PdfDocument.Page pg=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,i+2).create());Canvas cc=pg.getCanvas();cc.drawColor(Color.WHITE);p.setTextAlign(Paint.Align.RIGHT);p.setTextSize(20);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setColor(TEXT);cc.drawText("صورة الموقع / المنظومة",560,42,p);float sc=Math.min(500f/bmp.getWidth(),680f/bmp.getHeight());int nw=(int)(bmp.getWidth()*sc),nh=(int)(bmp.getHeight()*sc),left=(595-nw)/2,top=100+Math.max(0,(680-nh)/2);cc.drawBitmap(bmp,null,new Rect(left,top,left+nw,top+nh),null);doc.finishPage(pg);bmp.recycle();}
        FileOutputStream out=new FileOutputStream(file);doc.writeTo(out);out.close();doc.close();Uri uri=new Uri.Builder().scheme("content").authority(getPackageName()+".provider").appendPath(file.getName()).build();Intent sh=new Intent(Intent.ACTION_SEND);sh.setType("application/pdf");sh.putExtra(Intent.EXTRA_STREAM,uri);sh.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(sh,"مشاركة النموذج"));}catch(Exception ex){Toast.makeText(this,"تعذر إنشاء PDF: "+ex.getMessage(),Toast.LENGTH_LONG).show();}}
    private int pdfSection(Canvas c,Paint p,int y,String s){p.setColor(NAVY);c.drawRoundRect(35,y,560,y+24,10,10,p);p.setTextAlign(Paint.Align.RIGHT);p.setTextSize(12);p.setColor(Color.WHITE);p.setTypeface(Typeface.create("sans",Typeface.BOLD));c.drawText(s,550,y+17,p);return y+34;}
    private int pdfLine(Canvas c,Paint p,String l,String v,int y){p.setTextAlign(Paint.Align.RIGHT);p.setTextSize(10);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setColor(TEXT);c.drawText(l+" :",555,y+15,p);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));c.drawText(v.isEmpty()?"—":trim(v,46),430,y+15,p);p.setColor(Color.rgb(230,238,244));c.drawLine(35,y+24,560,y+24,p);return y+28;}

    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(round(Color.WHITE,24,BORDER,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(2);c.setLayoutParams(lp);if(Build.VERSION.SDK_INT>=21)c.setElevation(dp(2));return c;}
    private GradientDrawable round(int fill,int radius,int strokeColor,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke>0)d.setStroke(dp(stroke),strokeColor);return d;}
    private TextView text(String s,int size,boolean bold,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setTextDirection(View.TEXT_DIRECTION_RTL);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}
    private TextView small(String s){TextView t=text(s,12,false,MUTED);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(10);t.setLayoutParams(lp);return t;}
    private TextView chip(String s,int bg,int fg){TextView t=text(s,12,true,fg);t.setBackground(round(bg,14,0,0));t.setPadding(dp(10),dp(7),dp(10),dp(7));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.leftMargin=dp(8);t.setLayoutParams(lp);return t;}
    private TextView tag(String s,int fg,int bg,View.OnClickListener l){TextView t=text(s,12,true,fg);t.setBackground(round(bg,12,0,0));t.setPadding(dp(10),dp(6),dp(10),dp(6));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.leftMargin=dp(8);t.setLayoutParams(lp);t.setOnClickListener(l);return t;}
    private View empty(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(14),dp(14),dp(14));c.setBackground(round(Color.rgb(250,252,254),16,BORDER,1));c.addView(text(a,14,true,TEXT));TextView s=text(b,12,false,MUTED);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(4);s.setLayoutParams(lp);c.addView(s);return c;}
    private Button primary(String s,int color){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(color,18,0,0));b.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(54)));return b;}
    private Button smallButton(String s,int fill,int textColor){Button b=new Button(this);b.setText(s);b.setTextColor(textColor);b.setTextSize(13);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(fill,16,fill==Color.WHITE?BORDER:fill,fill==Color.WHITE?1:0));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(44),1);lp.leftMargin=dp(4);lp.rightMargin=dp(4);b.setLayoutParams(lp);return b;}
    private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private String t(EditText e){return e.getText().toString().trim();} private String val(String s){return s==null||s.isEmpty()?"—":s;} private String spin(Spinner s){String v=String.valueOf(s.getSelectedItem());return v.startsWith("اختر")?"":v;} private String trim(String s,int n){if(s==null)return"";return s.length()<=n?s:s.substring(0,n-1)+"…";}
    private String displayName(Uri u){try{Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&i>=0){String n=c.getString(i);c.close();return n;}c.close();}}catch(Exception ignored){}return u.getLastPathSegment()==null?"image":u.getLastPathSegment();}
    private Bitmap decode(Uri u){try{InputStream is=getContentResolver().openInputStream(u);BitmapFactory.Options b=new BitmapFactory.Options();b.inJustDecodeBounds=true;BitmapFactory.decodeStream(is,null,b);if(is!=null)is.close();int sample=1;while(b.outWidth/sample>1000||b.outHeight/sample>1000)sample*=2;BitmapFactory.Options o=new BitmapFactory.Options();o.inSampleSize=sample;InputStream is2=getContentResolver().openInputStream(u);Bitmap bmp=BitmapFactory.decodeStream(is2,null,o);if(is2!=null)is2.close();return bmp;}catch(Exception e){return null;}}
}