plugins { id 'com.android.application' }

android {
    namespace 'com.infinitygreenpower.solarform'
    compileSdk 35

    signingConfigs {
        stableDebug {
            storeFile file("$rootDir/signing/solarform-debug.keystore")
            storePassword 'SolarForm123'
            keyAlias 'solarform'
            keyPassword 'SolarForm123'
        }
    }

    defaultConfig {
        applicationId 'com.infinitygreenpower.offerstudio'
        minSdk 23
        targetSdk 35
        versionCode 31
        versionName '4.8.1'
    }

    sourceSets {
        main {
            java {
                exclude '**/OfferStudioV490Activity.java'
                exclude '**/OfferStudioV500Activity.java'
                exclude '**/OfferStudioV510Activity.java'
                exclude '**/OrganizerRebuild*.java'
            }
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableDebug
        }
    }
}
