plugins { id 'com.android.application' }

android {
    namespace 'com.infinitygreenpower.solarform'
    compileSdk 35

    signingConfigs {
        stableDebug {
            storeFile file("$rootDir/signing/solarform-debug.keystore")
            storePassword 'SolarForm123'
            keyAlias 'solarform'
            keyPassword 'SolarForm123'
        }
    }

    defaultConfig {
        applicationId 'com.infinitygreenpower.offerstudio'
        minSdk 23
        targetSdk 35
        versionCode 11
        versionName '4.1.1'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableDebug
        }
    }
}
